### ISSUE TITLE
[Bug] Problems with the Auto-download

### ISSUE THREAD

**Issue by AgileGhost** [inorichi/tachiyomi#3094] opened 2020-05-06 09:03 UTC
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: LG k40s

### Bug behavior
New manga updates don't automatically download when the option is enabled and when the correct category is selected. In my case, my category 'Reading' doesn't automatically download any new chapters even when it is selected in the downloads settings. It is very unlikely that the app is getting killed in the background due to it auto-updating and downloading manually set chapters in the background. (also added to power saving exclusions as well.) The settings haven't been touched since before 0.9.0 and had no problems with it back then.

While talking to Ainz-sama on discord, I said that my manga is in multiple categories and at all of them contain at least two categories. (eg, reading, all) I also suggested that having them in multiple categories might be causing some type of interference with the downloading and he seemed to agree with that.

- Attached my 'downloads' settings just in case you need it.

![Screenshot_20200506-183400](https://user-images.githubusercontent.com/61676371/81159283-28460800-8fcc-11ea-9dae-24e4be79d264.png)

**Comment by arkon** [comment] 2020-05-06 12:14
Probably a duplicate of #2325

**Closed** 2020-05-07 03:00 UTC
Labels: bug
