### ISSUE TITLE
[Feature Request] Tracking for LeagueOfComicGeeks

### ISSUE THREAD

**Issue by pokego12345** [inorichi/tachiyomi#2390] opened 2019-12-24 04:58 UTC
Hello! This is a bit unorthodox and not a high priority or anything, but since Tachiyomi can be used to read comics via the readcomicsonline extension, I was wondering if it would be possible to add tracking for LeagueOfComicGeeks, the largest/most active comic tracking database? Here it is: https://leagueofcomicgeeks.com/

I am very much a beginner to these kinds of things and I imagine the code required for this would be a lot different from a standard manga site, but I thought I would suggest the option anyway. Thank you!

Edit: Should have probably added some helpful info. If this does sound like something that would be interesting, the comics community normally works in a pull format, meaning they "pull" comics in advance. However, LOCG does have a "read" option for individual issues, which is what I assume what be used for tracking. Of course, the complication there is that it's by issue, not all stockpiled into one medium to individually increase the chapter count. Each issue read is it's own set of information in the database.

**Comment by zbhoy** [comment] 2019-12-24 08:31
So I read comics as well and having extensively researched comic tracking services, I can comfortably say they all suck. 

The reason LCG won't ever be integrated isn't because of anyone at Tachiyomi. It's because they don't offer an API. No comic tracking site does. So you can't integrate with them. 

One day there will be a service for comics as good as MAL/Anilist but until then, no tracking in Tachi

**Comment by arkon** [comment] 2019-12-26 17:42
Duplicate of #2356

**Closed by arkon** 2019-12-26 17:42 UTC
Labels: feature
