### ISSUE TITLE
[Feature Request] Arrow key mappings for incremental page scrolling.

### ISSUE THREAD

**Issue by BonfireOfDreams** [inorichi/tachiyomi#2288] opened 2019-10-19 03:28 UTC
**App version: 0.8.4**

**Android version: 9**

**Request: Add functionality for users to map arrow keys for image scrolling**

**Other details:**
I use tachiyomi through my TV via Samsung Dex. I also prefer having my pager scale type set to fit width.  In order to view content using this method I use an air mouse.  It works, but is less than ideal. Up and down arrow keys currently have the same functionality as the left and right arrow keys, so I would like to map them for page scrolling instead.

**Comment by arkon** [comment] 2020-03-07 22:39
Duplicate of #2220

**Closed by arkon** 2020-03-07 22:39 UTC
