### ISSUE TITLE
[Bug] "Page list is empty"

### ISSUE THREAD

**Issue by Killua41** [inorichi/tachiyomi#2839] opened 2020-04-08 22:06 UTC
Version: 0.8.5
Android version: 7.0
Device: Huawei P9 lite

When I try to read a manga in my library with the extension Mangaworld (italian) it says "page list is empty". Also when I open Mangaworld catalog it is just a black window and no manga appears.
I have updated all extensions and cleared caches and cookies, and the extension is uploaded. 
All the other extensions that I use works, only Mangaworld has this issue.

**Comment by arkon** [comment] 2020-04-08 22:43
Wrong repo.

Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2618

**Closed by arkon** 2020-04-08 22:43 UTC
Labels: bug
