### ISSUE TITLE
[Feature Request] Fingerprint Gestures for Scrolling

### ISSUE THREAD

**Issue by garvit-here** [inorichi/tachiyomi#3907] opened 2020-10-06 11:30 UTC
Hi there! I know that you guys are working really hard , I am not a coder myself but I know that it is a demanding job.  
We all know that now most phones come with a physical fingerprint scanner  I thought of a cool feature that utilizes fingerprint scanner.
IT IS FINGERPRINT GESTURES FOR SCROLLING OR SOME OTHER TASKS. Like swipe upward or downward on the sensor to move to  forward or backward page or simply increase or decrease brightness.
## Why/User Benefit/User Problem
It will add a "cool" factor to Tachiyomi and make scrolling through pages a very easy and efficient task. 
## What/Requirements
It will utilize Fingerprint scanner in the phone.
Sorry if this is badly formatted cuz I could not understand what is what.

**Comment by arkon** [comment] 2020-10-06 12:14
Duplicate of #1832

**Closed by arkon** 2020-10-06 12:14 UTC
Labels: feature
