### ISSUE TITLE
[Feature Request] Option to Change Icon Positions in Bottom Nav Bar.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#2645] opened 2020-03-01 07:37 UTC
### Why/User Benefit/User Problem
You think maybe we could get the option to change the positions of the icons in the bottom nav bar? I'd like my library icon in the middle, it'd be pretty cool if I could change that.

### What/Requirements
I think the devs could implement a menu/sub-menu in Settings for sorting the positions in bottom nav bar where we would drag-and-drop the icons to our favourite position (**exactly** like how we sort our Categories).

**Comment by jimmymidgett** [comment] 2020-03-04 00:35
Hello world @
Duplicate of #

**Comment by arkon** [comment] 2020-04-18 23:47
I'm against this since it adds a considerable amount of logic bloat. I'm open to separate suggestions on better ordering though, if there's strong arguments for that.

**Closed by arkon** 2020-04-18 23:47 UTC
Labels: feature
