### ISSUE TITLE
[Feature request] Link redirect to Tachiyomi

### ISSUE THREAD

**Issue by hafizhmakmur** [inorichi/tachiyomi#1301] opened 2018-03-12 05:27 UTC
**App version:**
0.7.0

**Issue/Request:**
Make the app able to detect manga site links and open it in Tachiyomi. It will make it useful if sometimes someone announce an update in r/manga and linking mangadex, so you don't have to go out of Reddit and open Tachiyomi manually, but instead it will immediately open Tachiyomi with relevant chapter. Maybe dont have to be mangadex but all manga site thats already registered in Tachiyomi, by extension or by default.

**Other details:**
Maybe also add option for each manga site to redirect to Tachiyomi or not. I have xkcd reader in Tachiyomi but I still want to read it not on Tachiyomi but somewhere else.

**Comment by ddmgy** [comment] 2018-03-12 14:04
Duplicate of #341.

**Comment by hafizhmakmur** [comment] 2018-03-12 14:28
Hmh, okay. But the thread from 2 years ago is still opened. Is there still any hope then?

**Comment by CarlosEsco** [comment] 2018-03-12 14:38
This will get closed because it's a duplicate. There is no guarantee any request for features get implemented

**Closed** 2018-03-12 14:41 UTC
