### ISSUE TITLE
[Feature Request] Auto-download future chapters after finishing chapter.

### ISSUE THREAD

**Issue by TheColorman** [inorichi/tachiyomi#3210] opened 2020-05-19 12:53 UTC
### Why/User Benefit/User Problem
In case the user/source has a slow connection, reading non-downloaded chapters becomes a hassle, and downloading every single chapter isn't always feasible. This feature will make sure there are always chapters downloaded, so there's never any waiting around.

### What/Requirements
The feature will have a toggle and a chapter count.
If enabled, it will automatically download as my chapters as specified in the settings after every finished chapter. 
Example: Chapter count is set to 3. Chapter 34 has just been marked as read, so now the app will check chapter 35, 36 and 37, and download them if they aren't already downloaded.

**Comment by arkon** [comment] 2020-05-19 12:56
Duplicate of #321

**Closed by arkon** 2020-05-19 12:56 UTC
Labels: feature
