### ISSUE TITLE
[Feature Request] Custom directory location for your local manga

### ISSUE THREAD

**Issue by IAMNOTRANA** [inorichi/tachiyomi#3943] opened 2020-10-15 08:13 UTC
Custom directory.
It would be great if we could set a custom location for our local manga, default one is fine but it become pain in the ass to have a neat and clean folders to keep things tidy, its probably not the most requested feature but having such basic option would be great for local manga users.

Gibe some love to local manga, dammit.

**Comment by scb261** [comment] 2020-10-15 08:15
Duplicate of #2086

**Closed** 2020-10-15 12:03 UTC
Labels: feature
