### ISSUE TITLE
[Feature Request] collapsible sub category (group multiple sources per manga)

### ISSUE THREAD

**Issue by nakohlyth** [inorichi/tachiyomi#2880] opened 2020-04-16 14:40 UTC
### Why/User Benefit/User Problem
There is differents cases : 
-sometimes chapters on some sources are missings
-some pages doesn't charge properly
-some sources are not updated regularly while others are
-and adding to this names sometimes differ on some sources

so I often have many different sources for the same manga, but it would be hell to make a category just for this making group would greatly improve the handling of those situation when you have to change source

### What/Requirements

The possibility to make collapsible group inside a category.
eventually adding the last read chapter number and the source as a hint next to the title for each one.
or a favorite badge for the preferred source.

**Comment by arkon** [comment] 2020-04-16 15:28
Duplicate of #1803

**Closed by arkon** 2020-04-16 15:28 UTC
Labels: feature
