### ISSUE TITLE
[Bug] selection remains after tapping download

### ISSUE THREAD

**Issue by pajiraw** [inorichi/tachiyomi#3070] opened 2020-05-04 21:49 UTC
# Device information
* Tachiyomi version: 0.9.2
* Android version: 8.1

when selecting a chapter then tapping download, the selection remains and therefore we have to clear selection manually.

**Comment by arkon** [comment] 2020-05-04 22:15
Duplicate of #3004

**Closed by arkon** 2020-05-04 22:15 UTC
Labels: bug
