### ISSUE TITLE
[Feature request] Tracking volumes instead of chapters

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [inorichi/tachiyomi#1764] opened 2018-12-06 22:29 UTC
Some manga formats are in volumes instead of chapters. Obviously, the volumes are incredibly of a much smaller value than chapters (e.g. 200+ chapters can be in volumes of only 20+, etc etc).

Now, I've tried finishing a volume and the value in Tracking didn't even update. Hoping this feature will be considered in a future version.

Tachiyomi version: 0.8.0

**Comment by metroid112** [comment] 2018-12-07 17:15
What manga "format" is in volumes? I know there's a few manga out there that the translations have posted the entire volume as a chapter but besides that I don't know what is this thing you mention.

**Comment by eji30** [comment] 2018-12-07 17:19
![Saint Seiya](https://i.imgur.com/5N6Klff.jpg)

**Comment by eji30** [comment] 2018-12-07 17:21
![Saint Seiya volumes](https://i.imgur.com/G2waQ1M.jpg)

**Comment by eji30** [comment] 2018-12-08 12:32
@metroid112
![Saint Seiya](https://i.imgur.com/59FOlMl.jpg)
![](https://i.imgur.com/IvGmCLL.jpg)

**Comment by metroid112** [comment] 2018-12-10 12:31
Yeah it's not the manga's format per se (Saint Seiya like 99% of manga, released on a chapter by chapter basis), but rather a thing from the people that uploaded the chapter itself on the site (Translator or aggregator).

If you want to update volumes on MAL, there's already an issue for that at #505

**Comment by eji30** [comment] 2018-12-10 12:45
@metroid112
I see. Thanks.

**Comment by arkon** [comment] 2020-01-04 20:47
Duplicate of #505

**Closed by arkon** 2020-01-04 20:47 UTC
