### ISSUE TITLE
Bug with scroll diagonally

### ISSUE THREAD

**Issue by LendLord** [inorichi/tachiyomi#231] opened 2016-03-26 07:47 UTC
Hi, there is really annoying bug with scroll. When you scroll page and move finger diagonally then nothing will happend, like there is a dead zone. 
To reproduce bug you need viewer one of: left to right, default, right to left and page that is longer than screen height, so if you move finger diagonally then nothing will happen. 

Here is the video of the bug. 
https://goo.gl/photos/AhuYnmHqHW2nqWr48
---
Version: r584 or v0.1.4
Nexus 5, Android 6.0.1, Root, Custom Rom

**Comment by j2ghz** [comment] 2016-03-26 10:27
But what should happen with diagonal scrolling? Scroll? Scroll & change chapter? Change chapter?

**Comment by LendLord** [comment] 2016-03-26 10:31
I think scroll=) and when I accidently(pretty often) move finger diagonally I expect scroll, anyway there must be no dead zone.

**Comment by inorichi** [comment] 2016-03-26 12:01
It looks like the expected behavior to me, that's how the `ViewPager` works. It's probably needed to override gesture events, I've tried changing some of the initial values and none of them helped.

**Comment by LendLord** [comment] 2016-03-26 12:09
Sounds like this problem is really hard to solve =) 
Hope someday it will be solved;)

**Comment by iBaer** [comment] 2016-04-07 07:49
I thought I was the only one who noticed this, since it isn't fixed in any of the debug versions as of yet.

As @LendLord mentioned the proper behaviour should be that it should simply scroll. It should only change the page when the degree is in a range of like 75° to 105° and 255° to 285°. In between it should simply scroll vertically (or if possible vertically and horizontally)

I'm neither a Java nor a Kotlin developer, but I might bother to look for a solution in case the main contributors need some help.

**Comment by inorichi** [comment] 2016-04-07 11:19
If you want to look into it, edit [this class](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/horizontal/HorizontalPager.kt). Put the cursor in  `ViewPager` and hit Ctrl+B, copy the entire class, fix the package and change the class name. Then inherit from that custom `ViewPager`. In `pager/vertical` it's done like that.

You probably want to look at `onInterceptTouchEvent` and `onTouchEvent`.

**Comment by iBaer** [comment] 2016-04-09 10:56
Just a quick status.

The problem seems to lie indeed in the `ViewPager` class and there in the `onInterceptTouchEvent` method (maybe it might be prevented even before that, I'm still testing stuff, my android emulator is really slow though).
Copying the whole class results in a lot of other classes from the same library to be copied as well, since they aren't public. I'll see what I can do to fix the problem now and commit something once I'm pleased with the result.

**Comment by inorichi** [comment] 2016-04-09 15:39
You shouldn't need to copy more classes. [VerticalViewPagerImpl](https://github.com/inorichi/tachiyomi/tree/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/vertical) is literally the same ViewPager but changing x with y and it works fine alone.

**Comment by iBaer** [comment] 2016-04-09 18:35
Yes, I realized that rather late and that's what I wanted to try out now.
I'm not sure yet what I did wrong the first time, when I tried to recreate a custom ViewPager.

**Comment by inorichi** [comment] 2016-04-11 17:02
Sorry, I didn't notice you were editing the post (I don't get notifications).

The change is simple so I'll include this for the next release.

**Comment by iBaer** [comment] 2016-04-11 17:15
No worries. The fix is indeed really simple. It took me some time to figure out the project structure and the android debugger.

@LendLord If you could test this and give some feedback, it would be nice. On my device it was really good.

**Comment by LendLord** [comment] 2016-04-11 20:09
wow, its really great!  Thank you=)

**Comment by iBaer** [comment] 2016-04-11 20:28
Yes, I realized that as well.
I wasn't able to make out this dead zone from the data I got.
I might play around with the values again. It should be much better now though, since (for me) the dead zone isn't reachable with natural movement.

**Comment by LendLord** [comment] 2016-04-11 20:30
Yes, now it's almost perfect, thank you=)

**Closed** 2016-04-15 13:33 UTC

**Comment by iBaer** [comment] 2016-09-05 22:18
I made another pull request for the library.
I think there are less dead zones now.

https://github.com/inorichi/subsampling-scale-image-view/pull/2
