### ISSUE TITLE
Batch Download of mangas

### ISSUE THREAD

**Issue by FreakyGamer** [inorichi/tachiyomi#2620] opened 2020-02-23 11:31 UTC
It would be nice if i could select multiple mangas in my library and then just press one button to download all mangas wich i marked.

As it right now i have to open every manga i want to download and then select download all and it's a bit time consuming

**Comment by arkon** [comment] 2020-02-23 15:16
Duplicate of #353

**Closed by arkon** 2020-02-23 15:16 UTC
Labels: feature
