### ISSUE TITLE
[Feature Request] Filter by Tracked/Not Tracked

### ISSUE THREAD

**Issue by chunkles** [inorichi/tachiyomi#3212] opened 2020-05-20 04:17 UTC
### Why/User Benefit/User Problem
So users can keep track of what is being tracked via their linked tracking service.

### What/Requirements
Can be added under the filters tab in the library

**Comment by arkon** [comment] 2020-05-20 11:54
Duplicate of #1899

**Closed by arkon** 2020-05-20 11:54 UTC
Labels: feature
