### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by JohnPalace** [inorichi/tachiyomi#1247] opened 2018-02-12 01:04 UTC
When Zooming in Webtoon mode, could you make it so that the image area also expands? Currently, you zoom the image but it remains confined to a tiny box of its former size.

**Comment by Inervo** [comment] 2018-06-09 08:44
I would also love this feature. It's hard to look at a zoomed image in the initial image area

**Comment by arkon** [comment] 2020-01-04 21:19
Duplicate of #1822

**Closed by arkon** 2020-01-04 21:19 UTC
