### ISSUE TITLE
[Feature Request] <Expand the History tab list limit past last 25 manga read>

### ISSUE THREAD

**Issue by Alamand1** [inorichi/tachiyomi#3770] opened 2020-09-09 01:04 UTC
## Why/User Benefit/User Problem
Currently the main app only records the last 25 manga read which can lead to avid readers having to reformat the library organization to "last read" just to easily find a manga that they might have read only 5 days ago. A history page that's expanded to 100 or even 200+ would make finding recent manga a non issue and could even help people find past series to catch up on or complete before they start expanding their list of active manga being read. I was told limitless history is on J2K but I think it would be a good feature for all platforms.

## What/Requirements
Essentially the list limit on the history page could be expanded to 100 or 200 instead of ending at 25. That or there could be an option in settings to manually set the list cap on the history page or make it limitless.

**Comment by arkon** [comment] 2020-09-09 02:09
Duplicate of #2877

**Closed by arkon** 2020-09-09 02:09 UTC
Labels: feature
