### ISSUE TITLE
[Feature Request] Add tracking from Mangalib pleaseAdd tracking from Mangalib please! 

### ISSUE THREAD

**Issue by MM001-r** [inorichi/tachiyomi#3835] opened 2020-09-23 07:05 UTC
**PLEASE READ THIS**
 Please add a feature so that Tachiomi can pass on the manga reading information to the Mangalib website 
---

## Why/User Benefit/User Problem
I keep a list of reading, and constantly go to the Site Mangalib and celebrate how much I read the chapters and this is long and uncomfortable. I hope for your help! 
## What/Requirements
This feature should transmit to the site with my account information about reading and the status of the mangaThis feature should transmit to the site with my account information about reading and the status of the manga.

**Comment by arkon** [comment] 2020-09-23 12:19
Duplicate of #2693

**Closed by arkon** 2020-09-23 12:19 UTC
Labels: feature
