### ISSUE TITLE
Auto Download Next Chapters while reading

### ISSUE THREAD

**Issue by FadedShadow589** [inorichi/tachiyomi#321] opened 2016-06-01 19:29 UTC
The option to bulk download chapters from the menu is great. However, while reading it becomes tedious to switch out and select it, or if one forgets and moves to an area without Wifi between reads, suddenly not having any more chapters left. 

It would be greatly appreciated if there was an option to automatically keep downloaded X (0, 1, 3, 5, etc) chapters ahead once you finished reading a chapter. Say I finished reading chapter 15, it would have already downloaded 16 and 17, then start ch 18 when 15 is marked as read (if the option were to keep 3 downloaded).

**Comment by lenisko** [comment] 2018-11-15 00:02
It's really good feature, been using it on other reader from a long time. Would be great to see it in tachiyomi as well :-)

**Comment by Sazaju** [comment] 2020-01-03 14:33
I support this feature too.

Somehow, the downloads feature of Tachiyomi are smart, since it allows to automatically download and automatically mark as read & delete the chapters. However, they have been mainly thought for cases where the reader is up to date: when a new chapter is out, it is downloaded, and once read, it is deleted. However, it is not made for new comers: I recently started Zettai Karen Children, which is about hundreds of chapters. On this one, I have to manually request the downloads because downloading automatically "the next non-downloaded chapter" is not available. A more current series is Domestic Girlfriend, 256 chapters and still running. Same problem, but in addition (because it is in the same category than the ones I want to keep up to date) it downloads  the last chapters while I am far to reach them yet. So in addition to download the next chapters manually, I have to delete the last ones manually... would be better to not download them from the start.

I woul suggest to adapt the download strategy to download the next non-downloaded chapter. With no limit (download until the last available chapter, like now) or with limit (wait to remove a chapter before to download a new one.

This way, one could keep a constant and customized cache of chapters at hand. With the auto restart requested in other issues, that would be quite the feature.

**Comment by arkon** [comment] 2020-08-01 20:55
Duplicate of #3295

**Closed by arkon** 2020-08-01 20:55 UTC
Labels: feature

**Comment by CarlosEsco** [comment] 2020-08-01 21:12
@arkon did you mean to close the older one?

**Comment by arkon** [comment] 2020-08-01 21:13
No, the newer one has more discussion/an associated PR.
