### ISSUE TITLE
Source swapping

### ISSUE THREAD

**Issue by aeli2** [inorichi/tachiyomi#269] opened 2016-04-20 04:35 UTC
It'd be nice if i could move my reading status and bookmark from one reader site to another (i.e. if one site is having problems, i can continue reading on another site without trouble)

**Comment by jsilvermist** [comment] 2016-04-24 23:47
+1 for the concept, but in practice not all sites label the chapters the same, some might have for example:
1, 1.1, 2, 3
where as another might have:
0, 1, 2, 3
Aside this the technical difficulties caused by this, it would be a nice feature.

**Comment by iBaer** [comment] 2016-04-26 13:57
What @jsilvermist said.
You could try to sync it similar to the MAL update process (e.g. if chapter 27 would be marked as read, it would mark the chapter 27 for the other site, no matter if it is correct or not), but there would be no guarantee that the reading status will will be for the same chapter in the end.

**Comment by NoodleMage** [comment] 2018-01-13 16:11
Implemented in migration commit

**Closed by NoodleMage** 2018-01-13 16:11 UTC
Labels: feature
