### ISSUE TITLE
downloads dir

### ISSUE THREAD

**Issue by Memi2** [inorichi/tachiyomi#1579] opened 2018-08-11 17:36 UTC
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**0.7.4 tachiyomi ( for android)

**Issue/Request:**

I apologize in advance if there are errors in the text, as I use a translator from Russian to English.

When you try to download manga for offline reading, an error appears in the notifications "Downloads dir or download dir (I don't recall)" .
This error appeared 10.08.2018 at 19: 48, and ended about 10.08.2018 at 20: 13.
At the moment everything is working, but I don't know if this error will appear again, and what is the reason for this error.

The app well I really like already read a lot of manga, and it was unexpected when this error appeared.

**Comment by arkon** [comment] 2020-01-04 21:49
Duplicate of #1604

**Closed by arkon** 2020-01-04 21:49 UTC
