### ISSUE TITLE
Local Manga Cover and Description

### ISSUE THREAD

**Issue by Rait0** [inorichi/tachiyomi#705] opened 2017-03-11 10:20 UTC
Cover
Placing a cover.jpg file in the root folder of the manga will load the cover in app. 
Tachiyomi/local/Mangatitle/cover.jpg

Description
I have the same idea.  Placing a txt file desc.txt will load a description in app.  Or just give as an ability to edit description in app. 

I just updated the app.  Love the new features and enhancements thank you very much! :) 

Version: v0.5.0
(Android 6.0)

**Comment by inorichi** [comment] 2017-03-11 15:07
Duplicate of #698. We'll probably read them from a file.

**Closed by inorichi** 2017-03-11 15:07 UTC
