### ISSUE TITLE
[Bug] <ReadManhwa> <Not showing nsfw content>

### ISSUE THREAD

**Issue by hunter643** [inorichi/tachiyomi#3634] opened 2020-08-08 15:36 UTC
### Device information
* Tachiyomi version: 0.10.3
* Android version: 9
* Device: Samsung j7 Core

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Shows NSFW contents on the top.

### Actual behavior
No NSFW

### Other details
![117236704_237223167352481_3716333985696455739_n](https://user-images.githubusercontent.com/69393812/89714272-05aefb00-d9d0-11ea-9fd0-7e66fc063fdd.jpg)

**Comment by arkon** [comment] 2020-08-08 15:40
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/4050

**Closed by arkon** 2020-08-08 15:40 UTC
Labels: bug
