### ISSUE TITLE
[Feature Request] Save downloaded chapters as CBZ

### ISSUE THREAD

**Issue by TyranitarTar** [inorichi/tachiyomi#1943] opened 2019-03-28 08:42 UTC
If this feature isn't too hard to implement, I'd love if this was an option in the app

**Comment by nille02** [comment] 2019-03-30 18:16
I would Love it too, they are just uncompressed Zip archives.

**Comment by inorichi** [comment] 2019-03-31 12:40
Duplicate of #918. It won't be possible until 1.x due to compatibility reasons (we can't use Android's Storage Access Framework for compressed files because we need random file access).

**Closed by inorichi** 2019-03-31 12:40 UTC
