### ISSUE TITLE
[Feature Request] Write short description here

### ISSUE THREAD

**Issue by sasharip** [inorichi/tachiyomi#3126] opened 2020-05-08 22:58 UTC
### User Problem
Can you add a background download of currently reading manga to reduce wait till page will download?with a adjustable number of chapters, of course

I know u can download manually, but is tedious and not space friendly

### What feature must do
For example, if you are reading chapter 10, app will try to download 2-3 chapter ahead, to reduce waiting time.

**Comment by arkon** [comment] 2020-05-08 23:04
Duplicate of #321

**Closed by arkon** 2020-05-08 23:04 UTC
Labels: feature
