### ISSUE TITLE
[Bug] Library Update Getting Stuck

### ISSUE THREAD

**Issue by mra1412** [inorichi/tachiyomi#3145] opened 2020-05-10 13:58 UTC
### Device information
* Tachiyomi version: r2289
* Android version: 10
* Device: Samsung Galaxy S9

## Steps to reproduce
1. Open the Tachiyomi app.
2. Tap on the library refresh round arrow on the top left corner in the app.

### Expected behavior
The app should check for updates for all manga/manhua in the library one by one and stop once the complete library has been checked.

### Actual behavior
Once the app starts checking for updates in the library, it stops after 50 or 51 mangas/manhuas have been checked and just hangs and shows the latest one it has checked in the notifications.

### Other details
I have even tried removing a few mangas/manhuas in my library to check if some of them were causing issues but the result was the same.

**Comment by arkon** [comment] 2020-05-10 14:07
Duplicate of #3137

**Closed** 2020-05-10 14:07 UTC
Labels: bug
