### ISSUE TITLE
[Feature-Request] multithread download

### ISSUE THREAD

**Issue by poldi1405** [inorichi/tachiyomi#1573] opened 2018-08-08 06:17 UTC
**App version:** any

**Issue/Request:** multithread download

**Other details:** Downloading small files throttles the speed, a way of circumventing it is by downloading multiple files at once.

**Comment by einstein95** [comment] 2018-08-08 06:49
Duplicate of https://github.com/inorichi/tachiyomi/issues/1567

**Closed** 2018-08-08 10:25 UTC

**Comment by GreyCannibal** [comment] 2018-08-08 11:32
🤣🤣 the issue is serious, not getting over 400kbps

**Comment by CarlosEsco** [comment] 2018-08-08 12:00
Just download in advance or overnight

**Comment by poldi1405** [comment] 2018-08-08 13:56
Well unfortunately you can sometimes download for a limited time only (public Wi-Fi on holiday in my case)
