### ISSUE TITLE
Read partially downloaded chapters

### ISSUE THREAD

**Issue by nokutu** [inorichi/tachiyomi#1140] opened 2017-12-31 11:57 UTC
I've noticed that when downloading chapters (specially from mangafox), there is sometimes one or several missing pages. Because of it, the download is never completed.

With this errored download, if I try to read the chapter it is loaded completely from the internet. I think it would be much better if it tried to use the local files, and, if a page is missing, try to load it from the internet.

**Comment by FreeSalad** [comment] 2018-01-08 20:13
One temporary fix for this is going into the chapter's directory, renaming the tmp file of the page being downloaded to its target name and restarting Tachiyomi. It will then detect the chapter as if it was fully downloaded.

**Comment by nokutu** [comment] 2018-01-08 20:14
Yes, I've actually been doing this for a while. The issue is that you don't know which page or pages you are missing, as the app seems to ignore the numbering of the files.

**Comment by shogunreaper** [comment] 2018-01-19 16:52
yes i would like this as well.

why doesn't it just rename the images as they are downloaded instead of waiting until all of them are?

**Comment by wopian** [comment] 2018-01-19 18:00
The downloaded images are also kept in the temporary directory used by the downloader: `{source}/{chapterNo}_{chapterTitle}_tmp/001.jpg`

**Comment by inorichi** [comment] 2018-04-07 19:06
> why doesn't it just rename the images as they are downloaded instead of waiting until all of them are?

Because a chapter isn't downloaded until all its images are.

Anyways this is caused by a faulty catalogue, the downloader is working as expected.

**Closed by inorichi** 2018-04-07 19:06 UTC
