### ISSUE TITLE
A little tip for the users and possibly an improvement for the app

### ISSUE THREAD

**Issue by menixator** [inorichi/tachiyomi#917] opened 2017-07-30 11:52 UTC
When you download manga from the app, and if you have Google's backup feature is enabled, it tends to pick up every single chapter as a separate folder. If you download manga in bulk you'll probably be overwhelmed by the amount of notifications asking permission to backup the folders. Moreover, you'll quickly get frustrated by the amounts of photos that get picked up by the photos app.

A quick way around this is to add an empty `.nomedia` file into the Tachiyomi folder. All the manga chapters will be ignored. Tachiyomi could implement this through the application if this seems like a good idea.

**Comment by j2ghz** [comment] 2017-07-30 11:59
Duplicate of #148 #726 #812

**Closed** 2017-07-30 14:20 UTC
