### ISSUE TITLE
Selecting then unselecting crash

### ISSUE THREAD

**Issue by kyoukaya** [inorichi/tachiyomi#807] opened 2017-05-21 12:05 UTC
Selecting a series in the My Library tab, switching to another tab, and then unselecting will cause a crash.

Version: v0.5.2 on Android 7.1.2

**Comment by inorichi** [comment] 2017-05-21 17:58
I can't reproduce this issue in master, it's probably already fixed.

**Comment by inorichi** [comment] 2017-05-29 07:57
Closing because it doesn't crash anymore.

**Closed by inorichi** 2017-05-29 07:57 UTC
