### ISSUE TITLE
[Bug] Navigation bar appear over the interface. 

### ISSUE THREAD

**Issue by Kill4Live7u7** [inorichi/tachiyomi#3641] opened 2020-08-10 14:39 UTC
### Device information
* Tachiyomi version: Stable 0.10.3
* Android version: 6.0
* Device: Huawei Mate 9 Lite

## Steps to reproduce
1. Open the chapter to read. 
2. Touch page to see the menu. 

### Expected behavior
This should show the upper menu and the "read bar" below clearly. 

### Actual behavior
The notification and navigation bar interfere and can't see it clearly. 

### Other details
![Screenshot_2020-08-10-11-38-56](https://user-images.githubusercontent.com/69468276/89794931-1cec0680-dafe-11ea-872d-f74537e60431.png)

**Comment by arkon** [comment] 2020-08-10 14:45
Duplicate of #3586, already fixed for the next release.

**Closed by arkon** 2020-08-10 14:45 UTC
Labels: bug
