### ISSUE TITLE
[Bug] Chapter Transition sometimes shows up even if "Always show chapter transition" is turned off

### ISSUE THREAD

**Issue by X9VoiD** [inorichi/tachiyomi#2728] opened 2020-03-17 11:20 UTC
### Device information
* Tachiyomi version: 0.8.5-1920
* Android version: 9.0

## Steps to reproduce
1. No clear steps to reproduce other than it is happening more frequently with a slow network and manhwas/webtoon. Check "other details" below.

### Expected behavior
"Always show chapter transition" is turned off so there shouldn't be any chapter transitions for a seamless reading experience.

### Actual behavior
But sometimes the chapter transition shows up briefly, then disappears after a while (or maybe disappears after the last page loads, check "other details"), offsetting the scroll of the current manhua/webtoon.

### Other details
Just a guess but the chapter transition shows up mistakenly when the last page of the current chapter is not loaded yet and the user already reached the end of the chapter.

**Comment by CarlosEsco** [comment] 2020-03-17 11:28
If your connection is slow and it can't load the next chapters page within the last 3 pages of the current chapter. It is going to show.

**Comment by arkon** [comment] 2020-03-17 12:18
We should probably word it better, but this is expected behaviour.

**Comment by morcefaster** [comment] 2020-03-17 16:40
The opposite of "Always show page transition" is "Not always show page transition" (i.e. sometimes show). It will still appear when the next chapter is not loaded and that's expected, but there _are_ some issues that can make it appear and disappear when unneeded too, such as #2727.

I'm now investigating that issue and will also see if preloading can be made better.

**Comment by CarlosEsco** [comment] 2020-03-17 16:47
@morcefaster  it already preloads.  If you have a slow connection and read fast there's not much to do.    Just pre download chapters is best solution

**Comment by morcefaster** [comment] 2020-03-17 17:03
> @morcefaster it already preloads. If you have a slow connection and read fast there's not much to do. Just pre download chapters is best solution

I know it preloads, hence I said if it can be made "better". I believe there might be some bugs around it, maybe with observers, that cause wrong chapters/pages to preload or load/preload out of order.

I see aforementioned issues on pre-downloaded chapters (I always download them ahead of time).

**Comment by morcefaster** [comment] 2020-03-17 23:35
Related issue: #2727

Both these issues are caused by a race condition in chapter (pre-)loading. 

While the transition page will still show up if the chapter **really** isn't loaded yet, it most commonly shows up with this bug right now.

**Comment by morcefaster** [comment] 2020-03-18 22:57
This can be closed. Wrongful appearances fixed with #2731, appearing when page is still loading is by design.

**Closed** 2020-03-18 23:38 UTC
Labels: bug
