### ISSUE TITLE
[Bug] Some local manga volumes have wrong page order

### ISSUE THREAD

**Issue by blunderedbishop** [inorichi/tachiyomi#3041] opened 2020-05-02 17:42 UTC
## Device information
* Tachiyomi version: 0.9.1
* Android version: 10

## Steps to reproduce
1. Open up a local manga volume in the reader. 

### Expected behavior
Volume pages should be ordered as one would expect: the cover is the first page, if there are some spreads (two pages) that have been merged as one you find them in the right spot. Version 0.8.5 acted as expected.

### Actual behavior
Some volumes are ordered as expected. Some are not: you'll find the cover as the last page, if there are merged pages or other particular pages (i.e. autor's note, table of contents, side stories) the order will be even more messed up. 
Opening up the CBZ archives with 7zip in Windows sorts the pages in the intended order, just as what used to happen in 0.8.5. It seems then the way page names are handled has changed and sometimes it does not sorts them the right way.

I'll provide some screenshot as soon as possible.

**Comment by arkon** [comment] 2020-05-02 18:20
Duplicate of #3034

**Closed by arkon** 2020-05-02 18:20 UTC
Labels: bug
