### ISSUE TITLE
[Bug] ReadManhwa source

### ISSUE THREAD

**Issue by Sajeeb97** [inorichi/tachiyomi#3069] opened 2020-05-04 21:43 UTC
### Device information
* Tachiyomi version: ?
* Android version: ?
* Device: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Webview doesnt load the ReadManhwa site

**Comment by arkon** [comment] 2020-05-04 21:44
Please follow the instructions next time.

Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3008

**Closed by arkon** 2020-05-04 21:44 UTC
Labels: bug
