### ISSUE TITLE
[bug] Kissmanga isn't loading

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#172] opened 2016-02-22 00:36 UTC
Kissmanga doesn't seem to be loading in the app, the other ones all load fine.

When i visited the site through my browser it had a browser\bot check type thing going on

```
Please wait 5 seconds...
Make sure to enable cookies and javascript.
This site does not work with "Mini browsers" (e.g. UC mini, Opera mini...)
```

so that's probably why.

---
Version: v0.1.4

**Comment by jedinat** [comment] 2016-02-22 01:18
It loads just fine for me.

**Comment by wopian** [comment] 2016-02-22 02:54
>Also how can i make the default order for chapters be ascending instead of descending?

@shogunreaper make a separate issue for this.

**Comment by shogunreaper** [comment] 2016-02-22 07:05
> It loads just fine for me.

still doesn't for me.

**Comment by Bloodwork** [comment] 2016-02-22 07:34
Loads fine for me.

**Comment by shogunreaper** [comment] 2016-02-23 19:41
there a way to debug or create a log?

**Comment by inorichi** [comment] 2016-02-23 23:58
The best option would be to install Android Studio and trying with the debugger. 

Getting a log of network packets with some tool may also help. Though I haven't tried anything for android so I don't know.

**Comment by shogunreaper** [comment] 2016-02-24 19:19
eh idk how to use that program

i meant creating a log with the app itself saying why it's not loading.

**Comment by JohnFlowerful** [comment] 2016-02-24 19:59
Since most (all?) people can load Kissmanga, it'd be better to check your network first.

**Comment by shogunreaper** [comment] 2016-02-24 20:09
my network is fine the site loads in the browser.

does anyone else get the javascript checking when visiting it?

**Comment by j2ghz** [comment] 2016-02-24 20:11
I do, but I don't use it because of the often changing urls (thus sometimes resetting read status) issue

**Comment by inorichi** [comment] 2016-02-25 15:38
Try with 50b97fa (latest debug). It will display the error on screen, if the message isn't enough, get a logcat of the app. Probably this app can get it (I haven't used it) https://play.google.com/store/apps/details?id=org.jtb.alogcat&hl=es

**Comment by shogunreaper** [comment] 2016-02-25 18:08
the debug version on the front page is what i'm supposed to use right?

this - http://tachiyomi.kanade.eu/latest/app-debug.apk

I tried it, i don't get any error messages coming up.

**Comment by inorichi** [comment] 2016-02-25 18:10
My guess is you are getting an empty page somehow. Try again disabling wifi/3g. You should see the message.

**Comment by shogunreaper** [comment] 2016-02-25 18:35
how am i supposed to load the page without the internet?

nothing happens, just a very quick loading circle appears then the same white page.

same happens to all of them without the internet.

I swear it's something to do with that javascript checking they are doing...

**Comment by inorichi** [comment] 2016-02-25 18:52
It was to make sure you are seeing a message. I have tested it and I see one when no network is available. Your version should be r513.

**Comment by shogunreaper** [comment] 2016-02-25 19:13
I'm not on that version

I downloaded from

http://tachiyomi.kanade.eu/latest/app-debug.apk

and it says i'm on version r504 in About

**Comment by inorichi** [comment] 2016-02-25 19:37
My fault. The link should be fixed now.

**Comment by shogunreaper** [comment] 2016-02-25 19:59
With kissmanga i get "failed to connect to /93.174.95.110:80"

With mangafox\mangahere i get this error

Unable to resolve host "mangafox.me" no address associated with hostname
Unable to resolve host "mangahere.co" no address associated with hostname

**Comment by inorichi** [comment] 2016-02-25 20:15
And the first error happens even with network enabled?

**Comment by JohnFlowerful** [comment] 2016-02-25 20:29
Aren't all kissmanga requests being routed through CloudFlare?

**Comment by shogunreaper** [comment] 2016-02-25 20:30
no i still don't get any error when i have wifi on.

**Comment by inorichi** [comment] 2016-02-25 20:33
It bypasses cloudflare accessing by IP so the javascript check is not the problem. I don't know what's the problem, and it's even harder to know/fix if I can't reproduce.

**Comment by shogunreaper** [comment] 2016-02-25 20:47
so its something to do with how you bypass it i think, since i can visit in my browser fine.

though its weird... i just used a vpn on my tablet and was able to load it.

**Comment by Sunnygrg** [comment] 2016-03-05 04:55
Just downloaded this app. I am getting the same issue. Every other source works fine though.

**Comment by null-dev** [comment] 2016-03-10 01:33
I can confirm this is happening after downloading a lot from KissManga in a short duration. Do you need logs inorichi?

**Comment by inorichi** [comment] 2016-05-15 20:56
It should work now 6e8a41f.

Covers won't load (unless they are already cached) until the details are refreshed. Either manually refresh them (pull down from the info tab) or use the clear database option (covers from library still need to be refreshed with the first option).

**Closed by inorichi** 2016-05-15 20:56 UTC
