### ISSUE TITLE
[Feature Request] A New Source for Arabic Language

### ISSUE THREAD

**Issue by HeisenMgh** [inorichi/tachiyomi#3130] opened 2020-05-09 13:58 UTC
Can I add this source in the future? It's the best source right now for Arabic Manga, the sources in the app are very poor.

The source: https://gmanga.me

Thanks for the hard work

**Comment by arkon** [comment] 2020-05-09 14:00
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/117

**Closed by arkon** 2020-05-09 14:00 UTC
Labels: feature
