### ISSUE TITLE
[Feature Request] Search in Library connects to Global Search

### ISSUE THREAD

**Issue by EnRyuuX7** [inorichi/tachiyomi#3459] opened 2020-07-12 13:14 UTC
---

### Why/User Benefit/User Problem
Improves user experience.

### What/Requirements
Search results from your library has a "Search in Catalogs" option which takes the user to the Catalog section. Something like from the AnYme app.

![Screenshot_20200712-185638](https://user-images.githubusercontent.com/33335446/87247161-d4471c00-c471-11ea-9e99-7ae75f056a7b.png)

**Comment by arkon** [comment] 2020-07-12 13:20
Duplicate of #2183

**Closed by arkon** 2020-07-12 13:20 UTC
Labels: feature
