### ISSUE TITLE
Saved pages don't actually save anywhere

### ISSUE THREAD

**Issue by Nogooduser** [inorichi/tachiyomi#710] opened 2017-03-14 11:39 UTC
I'm not sure if this is the intended behavior or if I'm just dumb but whenever I long press to save a page and I press save, despite saying the image has been saved on the notifications, it's not anywhere on my device (at least all my image galleries don't find any new images and when I look through the folders I don't either). 

What's even weirder is that when I get the notification saying the page was saved I can open it with my gallery but I can't do anything else with the image other than sharing it, which isn't what I normally want to do. 

I ask this because I'd like to be able to actually save the image onto my internal storage/SD card and/or directly open it from the notification so i can edit it. As of now only one of editor apps can edit the image via the notification bar but I have to press share and then select that app, but I'd really like to be able to use Photoshop Express to edit them if possible (if i try to share and select photoshop it aays it can't open the file). 

Hope you can clarify if this is the intended behavior or if I'm just doing something wrong. 

Version: v0.5.0
(Android 6.0.1)

**Comment by wopian** [comment] 2017-03-14 11:51
Duplicate of #704 and fixed in next release 😄

**Comment by Nogooduser** [comment] 2017-03-14 11:52
Actually I just figured out I had an issue with photoshop permissions on my phone and I can now open the images directly with it, which is pretty nice, but the images not actually saving anywhere in my storage problem is still there.

**Comment by inorichi** [comment] 2017-03-14 11:54
They are stored in `/sdcard/Pictures/Tachiyomi`. Though `/sdcard` may be different with some devices.

**Closed** 2017-03-14 21:39 UTC
