### ISSUE TITLE
[Bug] <webtoon read setting not stitching images together>

### ISSUE THREAD

**Issue by shreaper** [inorichi/tachiyomi#4017] opened 2020-11-06 23:16 UTC
## Device information
* Tachiyomi version: latest
* Android version: 9
* Device: samsung tab 3

## Steps to reproduce
1. read style = webtoon
2. browse mangadex
3. Search The First Hunter
4. Download
5. view chapter 1

### Expected behavior
This should happen 
The first hunter chapter 1 will display using reader setting webtoon which is like vertical but stitches all the images together into one stream.

### Actual behavior
This happened instead.
The first hunter chapter 1 displayed images that are not all together and showing black background inbetween images

## Other details
[Additional details and attachments.](https://media.discordapp.net/attachments/737251726674886686/774409363741343755/tachiyomi.jpg?width=416&height=677)
Photo of described problem (no idea how to do screenshots)

**Comment by arkon** [comment] 2020-11-22 21:01
Duplicate of #2736

**Closed by arkon** 2020-11-22 21:01 UTC
Labels: bug
