### ISSUE TITLE
[Feature Request] Automatic Background Color

### ISSUE THREAD

**Issue by ThatGuyAgain42** [inorichi/tachiyomi#2553] opened 2020-01-31 12:00 UTC
### I just got this app and noticed there was no automatic background color
    Adding this feature would be aesthetically pleasing and simple to implement

### How I would implement this
    Simply check what color is the the first pixel in the image. Since most manga have borders and not many manga are colored just check if the first pixel in the image is closer to black or white. Then make the background color black/white depending on the result.

**Comment by ThatGuyAgain42** [comment] 2020-01-31 12:14
Just to be safe you could average out the entire first row of pixels and the bottom row of pixels

**Comment by arkon** [comment] 2020-03-07 23:29
Duplicate of #584

**Closed by arkon** 2020-03-07 23:29 UTC
Labels: feature
