### ISSUE TITLE
[Feature request] Reader scrolling speed

### ISSUE THREAD

**Issue by lenisko** [inorichi/tachiyomi#1649] opened 2018-10-06 04:22 UTC
Setting with scrolling speed multiplier on webtoon reader would be great. Sometimes stripes are too long to swipe them like crazy :)

**Comment by Amazingduf** [comment] 2018-10-06 07:06
Yeah, that would be really helpful, also, please make the scrolling more smooth.

**Comment by hXtreme** [comment] 2019-05-22 11:14
I was wondering if webtoons could have an auto-scroll feature.

**Comment by arkon** [comment] 2020-04-26 22:41
Duplicate of #2785, which is clearer.

**Closed by arkon** 2020-04-26 22:41 UTC
