### ISSUE TITLE
Genre tags bug

### ISSUE THREAD

**Issue by CarlosEsco** [inorichi/tachiyomi#1196] opened 2018-01-19 01:34 UTC
Latest dev
Descriptions that are too long force genre tags to be cut off instead of scrolling the field.
![image](https://user-images.githubusercontent.com/2092019/35130485-1846d3d0-fc8f-11e7-8207-b8f05de52a9d.png)

This source has issues with tags being just one 
![image](https://user-images.githubusercontent.com/2092019/35130487-1dbb5890-fc8f-11e7-87eb-7eb1c775618c.png)

**Comment by Flat** [comment] 2018-01-19 03:10
Wrapping the bottom half in a ScrollView[1] should fix it easily enough.

1. https://developer.android.com/reference/android/widget/ScrollView.html

**Comment by LinkCable** [comment] 2018-01-19 03:51
Oh boy, that second one. My instinct was parse on space or capitals but School Life breaks that, is there a way to get a list of genres from each site that we could use as a dictionary to reference or something?

**Comment by QuestofIranon** [comment] 2018-01-19 04:09
Looks like it's only a problem with readmangatoday at least...

**Comment by QuestofIranon** [comment] 2018-01-20 03:43
The bottom half was already in a scroll view, I just moved the tags inside of the scrollable part.

**Comment by CarlosEsco** [comment] 2018-01-20 03:59
I thought description was in a scroll view was just to lazy to check and couldn't find any manga with large enough description in my library 😀

**Comment by QuestofIranon** [comment] 2018-01-20 04:00
@LinkCable There are genre lists hard coded in each source's specification for the online sources. I could potentially parse using those, but it would require me changing some things in the code for sources. 

Would this present a problem? (I think I should just need to add "getGenreList()" to the source interface and make it public everywhere instead of private so I can access the list while parsing. I just wasn't sure if it would cause an issue with extensions/ custom sources that I've overlooked.

**Comment by CarlosEsco** [comment] 2018-01-20 04:08
Wouldn't that require every source to be modified to remove the private access?

**Comment by CarlosEsco** [comment] 2018-01-20 04:21
@QuestofIranon when a genre is clicked is it actually doing a global filtered search for the genre or is doing a text search? Cause if it's just a text search I say just split on space.  Does it really matter if school life is one tag or two

**Comment by 444nonymous** [comment] 2018-01-20 04:48
What about single click for individual genre search and "Genres" word click for multiple genre search? So if genres are Action and Fantasy, click to search Action or Fantasy, click "Genres" to search Action + Fantasy. There should be a a clickable Genres word preceding the genre list. 

"Genres: (Action) (Fantasy)" -> I clicked one genre -default look-
"Genres: (Action + Fantasy)" -> I clicked "Genres" word -maybe 1 long click that opens the search. Or 2 clicks: First click in "Genres" word to change form  "(Action) (Fantasy)" to  "(Action + Fantasy)", second anywhere in the genre list (Action + Fantasy) to open the search.

It could also be done for other fields like author and artist. 

And I think it's better to keep the genre list at top with the current font size (small)

**Comment by bbtora** [comment] 2018-01-20 15:26
> when a genre is clicked is it actually doing a global filtered search for the genre or is doing a text search?

From what I've tested, I can confirm that the latter action is being performed and I don't think this is what everyone has in mind for this feature.

**Comment by CarlosEsco** [comment] 2018-01-20 15:41
Yea thinking about it more i dont think its even possible to do a global filtered search.  Most sites either have no search by genre available or genres dont match it would be a nightmare to try to filtered search globally

**Comment by 444nonymous** [comment] 2018-01-20 17:38
At least a search in the same site would do. It helps finding manga by the same genre.

**Comment by CarlosEsco** [comment] 2018-01-20 17:57
Maybe click to search same source filtered long click to text search global.  Though not all sources that show genres have search by genre

**Comment by QuestofIranon** [comment] 2018-01-20 18:43
I intended to look more into doing a global filter search but it seemed a bit out of scope for the changes in the previous PR (and probably the new one as well) As @CarlosEsco said I don't think it would be possible without it only partially working and larger changes to the global search feature.

I could do click to filter search, long click to global search, but that would conflict with the long click to copy feature on other fields.

**Comment by QuestofIranon** [comment] 2018-01-20 21:12
Since the genre lists for each source are hardcoded anyway, maybe they could be normalized for the application/ search functionality?

**Comment by CarlosEsco** [comment] 2018-01-20 21:54
If you did that I think each source would need to map the hardcoded genre to the normalized version and also do the reverse for filter right? Seems like a lot of work

**Comment by QuestofIranon** [comment] 2018-01-21 00:43
Yeah, but it might be worth looking into for the future.

**Comment by CarlosEsco** [comment] 2018-01-21 00:44
Agreed

**Comment by LakotaGray** [comment] 2018-01-21 06:42
Most sources have the option to do a genre search with additional filters along with it. A-Z, # of chapters, newest update etc. So if someone is looking for latest of particular genres, that can be done on most sites. However it’s unlkely to be viable in a global search due to the variance in said options from site to site. Mangahere, MangaPark and MangaGo can set genres with the additional filter of lastedt release, but KissManga doesn’t.

**Comment by bbtora** [comment] 2018-01-22 04:21
Text search for genres in global search seem kinda dumb to me (sorry to say). 

Searching "mystery" got me this.

![img_20180122_094951](https://user-images.githubusercontent.com/23010526/35205258-c2b42238-ff59-11e7-884f-55a91d73e149.jpg)
![img_20180122_095008](https://user-images.githubusercontent.com/23010526/35205259-c6832c6a-ff59-11e7-927e-0305d70842b0.jpg)

**Comment by QuestofIranon** [comment] 2018-01-22 05:38
Would it be better to just do a filter search on the current source?

**Comment by CarlosEsco** [comment] 2018-01-22 12:18
I thinks so

**Comment by QuestofIranon** [comment] 2018-01-22 18:58
I'll go with that. I might apply it to all of the fields except title since they all face similar issues with global search. Any objections?

**Comment by inorichi** [comment] 2018-01-22 19:18
Yeah, that might be the best option. I doubt global search with genres will ever be a thing. We'd have to hardcode in the application a big list and map them manually for each source, besides the genres variance across different sites @LakotaGray already mentioned.

But other filters like author and artist could be added in the next extensions lib iteration to allow a proper global search.

**Comment by QuestofIranon** [comment] 2018-01-22 20:33
For now I'll do non-global filter. What is the expected ETA for the next extensions lib iteration?

**Comment by inorichi** [comment] 2018-03-09 20:43
It was autoclosed by github but it's not done yet.

**Comment by inorichi** [comment] 2018-04-05 20:05
Should be fixed in e0d6802

**Closed by inorichi** 2018-04-05 20:05 UTC

**Comment by inorichi** [comment] 2018-04-05 20:08
[Actually wasn't](https://github.com/inorichi/tachiyomi/commit/69f51b88bf04eafea377296127a11b552b56424e) :sweat_smile:

**Comment by 444nonymous** [comment] 2018-06-02 05:04
@QuestofIranon 
@CarlosEsco
@inorichi

If global search by genre is not an option, why not change it for something simple and useful like a short genre description? So when you click a genre tag you get a pop-up text description. Like the ones in -> http://www.anime-planet.com/manga/tags

**Comment by CarlosEsco** [comment] 2018-06-02 11:10
Do they have an API?  I only ask cause that a crap ton of genres to store locally just for something that someone can Google assuming they don't already know what it is.

**Comment by wopian** [comment] 2018-06-02 16:55
AnimePlanet has no API (yet), but Kitsu and possibly AniList does for the categories/genres
