### ISSUE TITLE
Issues with "Hide Status Bar" option. 

### ISSUE THREAD

**Issue by MrAmnesiac** [inorichi/tachiyomi#359] opened 2016-06-20 18:18 UTC
Even with "Hide Satus Bar" on, the status bar reappears whenever I thouch the screen (like to scroll), never auto-hides again.

![screenshot_2016-06-20-19-14-08](https://cloud.githubusercontent.com/assets/19335590/16205428/b4f545e4-371b-11e6-96da-5d772d0a335d.png)

Version: v0.2.2-1
Android 4.2.2  - Samsung Duo GT-S7582

I also want to thank you for your work, great software! I absolutely love it!

**Comment by inorichi** [comment] 2016-06-26 00:42
Can you test [this build](https://teamcity.kanade.eu/repository/download/tachiyomi_Build/562:id/app-debug.apk?guest=1)? You don't need to uninstall the stable release. The setting is now "Fullscreen".

**Comment by MrAmnesiac** [comment] 2016-06-26 21:48
Sorry for the delay, 
The issue presists with that apk

**Comment by inorichi** [comment] 2016-06-26 23:57
[One more try](https://teamcity.kanade.eu/repository/download/tachiyomi_Build/565:id/app-debug.apk)

Are you using a custom OS or the stock one?

**Comment by Syborg49** [comment] 2016-06-27 00:11
@inorichi it seems to be a problem with the 4.2.2 version of Android, I used to have the exact problem [81] (https://github.com/inorichi/tachiyomi/issues/81) but then I upgraded to a 5.1 device, that issue is gone now.

**Comment by inorichi** [comment] 2016-06-27 00:41
Alright, I've reproduced this issue in the emulator and [this commit](https://github.com/inorichi/tachiyomi/commit/6abe752905e953cb6cce573bb51ccfcfc641dda7) fixes it. [Here's the build](https://teamcity.kanade.eu/repository/download/tachiyomi_Build/566:id/app-debug.apk?guest=1) for that commit. I would appreciate a fix confirmation of @MrAmnesiac before closing and merging those changes branch into master.

**Comment by MrAmnesiac** [comment] 2016-06-27 13:10
That one works!
Thank you @Syborg49 for helping with the diagnoses and thank you @inorichi for all your work.

**Closed** 2016-06-27 14:45 UTC
Labels: bug
