### ISSUE TITLE
[Feature Request] Random Library Button

### ISSUE THREAD

**Issue by CherryMonster222** [inorichi/tachiyomi#3713] opened 2020-08-24 15:49 UTC
This feature will help people like me with large number of Mangas in the library who cant decide what to read.

This could be a simple button that chooses a random manga to open from the current category that is open in the library view. A similar future to AnymeX where it chooses a random anime from the plan to watch.

**Comment by scb261** [comment] 2020-08-24 15:57
Duplicate of #1248

**Closed** 2020-08-24 16:08 UTC
Labels: feature
