### ISSUE TITLE
[Feature Request] please implement a way to stitch two pages together for a 2-page spread

### ISSUE THREAD

**Issue by sillysack69** [inorichi/tachiyomi#3147] opened 2020-05-10 15:51 UTC
### Why/User Benefit/User Problem
Manga often have 2-page spreads that the cleaners don't stitch together to form a complete spread and are just put as two different pages. This makes reading that spread disjointed and unintuitive, often causing me to flip the same 2 pages back and fourth to read the whole thing. It just makes the whole experience really jarring and takes me out of the moment to realize the inability to view both pages at once. It would be a blessing if these two pages could be viewed simultaneously so as to create a false spread. I really do think that this is a common issue and one that should not be too difficult to implement (not that I'm a dev myself).

### What/Requirements
This could be implemented as an option in the settings icon in the right hand side corner of the image viewer of tachiyomi which would be listed along side the rotation, background color etc. options in the pull up menu. You could just enable this as a switch to stitch the current and next pages to together along with the ability to invert the option (next page+current as opposed to current page+next page). And since you turned on the option for only those specific pages, tachiyomi could remember which ones are to be viewed simultaneously, and so you could do this for any number of 2-page spreads in a chapter. I hope that's clear enough.

**Comment by arkon** [comment] 2020-05-10 16:15
Duplicate of #149

**Closed by arkon** 2020-05-10 16:15 UTC
Labels: feature
