### ISSUE TITLE
[Feature Request] Unread counter for categories

### ISSUE THREAD

**Issue by MrEthelWulf** [inorichi/tachiyomi#3493] opened 2020-07-20 07:13 UTC
### Why/User Benefit/User Problem
I have created a "Completed" category where I put all the manga I've read which have completed. But sometimes they have omakes or twitter extras updates which I often miss out on because I generally don't open that category.

### What/Requirements
So it'd be great if we can have an unread counter on the different categories, counting the number of manga, comics, etc. in which chapters are still unread by the user. It'd work similar to how we have a counter for an extension updates still pending to be done.

**Comment by arkon** [comment] 2020-07-20 12:12
Duplicate of #2556

**Closed by arkon** 2020-07-20 12:12 UTC
Labels: feature
