### ISSUE TITLE
No option to download in different formats 

### ISSUE THREAD

**Issue by Anutrix** [inorichi/tachiyomi#1744] opened 2018-11-22 16:01 UTC
No option to download in different formats like cbz, cbr, etc. Sinces these are just regular compressed files so it should be easy to implement. Is it already there? I couldn't find options in settings.

**Comment by CarlosEsco** [comment] 2018-11-22 16:06
No current framework is there  for compressing images

**Comment by CarlosEsco** [comment] 2018-11-22 16:33
Again just cause there is a library built in to Android for zipping doesn't mean the tachiyomi framework can fit it in as there is no current framework without a lot of rewriting code

**Comment by Anutrix** [comment] 2018-11-22 16:47
I haven't seen the source yet so I am sry if I am wrong. But isn't it possible to write isolated zipping code which just zips the files once everything is downloaded individually in proper folders.

**Comment by Flat** [comment] 2018-11-22 16:50
You would then need to integrate that code into the downloader. Setup a callback to when the download completes. Add various settings in the UI and settings code etc. PRs welcome.

**Comment by Anutrix** [comment] 2018-11-22 17:09
I have exams right now. Will start working on it in a week. Thx. Awesome project.

**Comment by Flat** [comment] 2018-11-22 17:50
Most dev work currently is for the rewrite or branch 1.x. If you do decide to implement this I would suggest waiting until 1.x is more fleshed out or making the code as generic as possible to make it easier to implement in 1.x.

**Comment by Anutrix** [comment] 2018-11-22 17:57
Ok

**Comment by inorichi** [comment] 2018-11-22 19:35
Creating a zip file is easy. Making it work with the Storage Access Framework without having to decompress the entire zip first is not.

On 1.x I plan to drop support for custom download directories, where I don't need to use SAF and chapters can be compressed.

**Comment by inorichi** [comment] 2018-11-29 12:48
Closing duplicate of #918

**Closed by inorichi** 2018-11-29 12:48 UTC
