### ISSUE TITLE
Notification info disappears at next update if no new chapters were found

### ISSUE THREAD

**Issue by bergerst** [inorichi/tachiyomi#703] opened 2017-03-09 17:25 UTC
Since activating the automatic download of chapters I don't get any notifications about new available chapters.

Without automatic download users get a message saying something like "New chapters available for ...".

The only way I am reminded of new chapters is an occasional 503 error when downloading chapters.

Could you please trigger that same notification when automatically downloading chapters?

Version: v0.5.0
Android 6

**Comment by inorichi** [comment] 2017-03-10 19:37
They are not supposed to be exclusive. Maybe the notification is dropped by the framework (there's a limit of 10 notifications per second), but I doubt that many are posted...

I've just pushed a commit to post the notification before starting downloads. I don't know if it'll help, I need confirmation.

**Comment by reconman** [comment] 2017-03-10 20:41
I've installed the debug apk and will report back in a few days when new chapters are available.

**Comment by bergerst** [comment] 2017-03-10 20:43
I've installed the debug apk and will report back in a few days when new chapters are available.

**Comment by libjared** [comment] 2017-03-20 23:06
@bergerst any update? I'm having the same problem. r1120.

**Comment by bergerst** [comment] 2017-03-20 23:13
On Thursday a couple of chapters were released but the only notification I could see was a connectivity problem of the download manager.

I don't think the commit had any effect.

**Comment by inorichi** [comment] 2017-03-21 08:49
Tested on Nougat and I can't reproduce.

**Comment by bergerst** [comment] 2017-03-23 17:31
I was able to find out more. When a chapter is downloaded it will show 2 notifications. One says that the library was updated and the other that a chapter was downloaded.

A few hours later the notifications were gone and only a "Page list is empty" notification was shown for Boku no Hero Academia. My update interval is 2 hours.

New notifications about the library updating and about downloading chapters seem to replace old ones.

**Comment by bergerst** [comment] 2017-03-23 21:08
3 hours ago Tachiyomi downloaded the new Shokugeki no Soma chapter and showed this.

![screenshot](https://dl2.pushbulletusercontent.com/30VWPECWK9q44ebqoktNRFx8jDp6cMOK/Screenshot_2017-03-23-19-17-41.png)

3 hours later the notifications are gone. No new chapters were downloaded during the second update.

**Comment by bergerst** [comment] 2017-03-23 21:26
I think I found the exact reason after thinking about it!

Look at the code at https://github.com/inorichi/tachiyomi/blob/68c4116327ea2fde74fbcd72431fdb1412b5e3bf/app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt#L288

`               // Notify result of the overall update.
                .doOnCompleted {
                    if (newUpdates.isEmpty()) {
                        cancelNotification()
                    } else {
                        showResultNotification(newUpdates, failedUpdates)
                        if (downloadNew) {
                            if (hasDownloads) {
                                DownloadService.start(this)
                            }
                        }
                    }
                }`

cancelNotification() deletes the "Update completed" notification because every notification in LibraryUpdateService.kt has the same notificationId. All of them use Constants.NOTIFICATION_LIBRARY_ID.

The reason why cancel is called is because the downloaded chapters are not detected as new anymore and are thusly not included in the "Update completed" message. If the list of updated mangas is empty then cancel will be called.

**Comment by inorichi** [comment] 2017-03-23 21:44
Now that makes sense, so it's not related to having automatic downloads enabled or not.

`cancelNotification` being called doesn't really matter, as the notification is overwritten at the moment the next update starts.

A possible workaround is using a different id for the new chapters found notification, however it will also be lost if the next update contains new chapters. 

Another one is to parse the last notification and append the new chapters.

**Comment by bergerst** [comment] 2017-03-23 21:46
If the chapters have been automatically downloaded then they aren't inserted into newUpdates anymore. Therefore newUpdates.isEmpty() is true and the notification is canceled. That is why it **is** related.

**Comment by inorichi** [comment] 2017-03-23 22:00
I'm not sure I follow. The next iteration of the library update starts with an empty `newUpdates` so I still think it doesn't have anything to do.

**Comment by bergerst** [comment] 2017-03-23 22:11
Ah, I thought update notifications would stack if chapters were found in different updates but it seems like that's not the case. Chapters are only added to newUpdates if they are not in the database yet.

I think the best way to do this is to create a new notification ID for update completed notifications and append to the message if there is one.

**Comment by inorichi** [comment] 2017-03-25 21:04
Fixed in e619870, however appending new chapters from the previous notification [is only possible since Marshmallow](https://developer.android.com/reference/android/app/NotificationManager.html#getActiveNotifications()).

**Closed by inorichi** 2017-03-25 21:04 UTC

**Comment by reconman** [comment] 2017-03-26 10:45
This morning when I woke up I had an Update completed message but with an empty message. 

Boku no Hero Academia was updated but I think the message got replaced by the empty default string specified by extras.getString(EXTRA_BIG_NOTIFICATION, "") at the next update.

**Comment by bergerst** [comment] 2017-03-26 10:46
This morning when I woke up I had an Update completed message but with an empty message.

Boku no Hero Academia was updated but I think the message got replaced by the empty default string specified by extras.getString(EXTRA_BIG_NOTIFICATION, "") at the next update.

**Comment by inorichi** [comment] 2017-03-26 10:50
I noticed it too in my tablet running Android M. I'm not sure if the empty string is causing it, because at least the text from the new notification must be shown (the result from `extras.getString` is added to the end of an existing list).

Also, the notification wasn't shown in the status bar, but only in the notifications when expanded, which makes me think there's something else wrong here.

**Comment by inorichi** [comment] 2017-03-26 13:34
I reproduced in the emulator the notification icon missing: https://gfycat.com/PositiveWholeAmphiuma
I also added a small description with a count of titles with new chapters.

I don't know if this is specific to Marshmallow, I'll keep an eye on this.

**Comment by inorichi** [comment] 2017-03-29 07:22
Fixed the issue I mentioned by canceling the progress after posting the result. I've also changed `extras.getString(EXTRA_BIG_NOTIFICATION, "")` to be a bit more consistent.

**Comment by bergerst** [comment] 2017-03-30 17:19
Sadly it's still empty with your newest commit.

http://m.imgur.com/y98fzLB

**Comment by inorichi** [comment] 2017-03-30 18:00
Big text can't be shown when there are two notifications, AFAIK. I'll push a new commit with the short description.

**Comment by bergerst** [comment] 2017-03-31 10:03
Thanks for your work, everything works now.

**Comment by inorichi** [comment] 2017-04-01 10:08
I finally discovered the reason behind the empty content. When there's only one update, big text is always ignored and only the content title is used, so I manually handled that case and it now works as expected. I also gave the notification higher priority (only the notification at the top can be expanded).
