### ISSUE TITLE
Weblate is down

### ISSUE THREAD

**Issue by Ancovens** [inorichi/tachiyomi#1286] opened 2018-03-03 07:38 UTC
https://weblate.j2ghz.com/ is down

**Comment by Flat** [comment] 2018-03-03 08:02
This is not a bug with tachiyomi. Please read the text before deleting it. Also see here https://github.com/inorichi/tachiyomi/pull/1274#issuecomment-369942801

**Comment by Ancovens** [comment] 2018-03-03 09:55
Pls update the wiki link.

**Comment by wopian** [comment] 2018-03-03 11:14
Its not currently live on the hosted projects yet - could be up to a month until that happens.

**Comment by j2ghz** [comment] 2018-03-03 11:24
Wiki updated, you can close the issue.

**Closed** 2018-03-03 11:32 UTC
