### ISSUE TITLE
[Feature Requests] Show a list of missing extensions when restoring backup

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#2305] opened 2019-10-29 03:17 UTC
App version: r1531

Android version: 9 

Currently, when backups are restored without having all required extensions installed, it just shows that error occured, and users have to open the error log to see what manga failed to restore. This is very tedious and most phones do not have inbuilt log viewer.

It would be much easier if the app shows a message box with a list of missing extensions when backup is restored without all extensions.

For example:

> Restore took 00 min, 10 sec
> 17 errors found, please install the following extensions and restore again:
> Mangahere
> Mangasee
> Webtoons.com

**Comment by joseph619** [comment] 2019-10-31 04:49
@hXtreme Can you please look into this?

**Comment by arkon** [comment] 2020-01-04 22:25
Marking as duplicate of #1810

**Closed by arkon** 2020-01-04 22:25 UTC
