### ISSUE TITLE
[Feature Request] Download Storage Display

### ISSUE THREAD

**Issue by llreizh** [inorichi/tachiyomi#3301] opened 2020-06-10 01:34 UTC
### Why/User Benefit/User Problem
When storage is full, but still downloading. Downloaded chapters in another manga often lost.

### What/Requirements
Check storage capacity. Pause download when full.

**Comment by arkon** [comment] 2020-06-21 21:34
Duplicate of #1018

**Closed by arkon** 2020-06-21 21:34 UTC
Labels: feature
