### ISSUE TITLE
Feature request: hold-press menu entry on each manga to migrate

### ISSUE THREAD

**Issue by blureshadow** [inorichi/tachiyomi#1368] opened 2018-04-13 21:17 UTC
**Request:**
Why not make the Source migration option on a by-manga basis too? as in if I hold press on a manga I can migrate that manga only, without having to check which source I have the manga from then going through the full menu.

**Comment by CarlosEsco** [comment] 2018-04-13 21:41
Duplicate of #1204

**Closed** 2018-04-13 22:04 UTC
