### ISSUE TITLE
[Feature Request]  bookmark pages

### ISSUE THREAD

**Issue by Amazingduf** [inorichi/tachiyomi#1711] opened 2018-11-07 20:51 UTC
Is it possible to implement a bookmark system for actual pages ? So you could return to that certain page again if you want and read again from that point. Like a tab with all the bookmarked pages or something like that.

**Comment by inorichi** [comment] 2018-11-14 14:09
Duplicate of #565

**Closed by inorichi** 2018-11-14 14:09 UTC
