### ISSUE TITLE
[Feature Request] Share Via Link

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3498] opened 2020-07-21 14:24 UTC
### Why/User Benefit/User Problem
IT IS EASIER TO SHARE A LINK TO A FRIEND

### What/Requirements
I don't Know If I Request it to The Extension Or In the App...
It is OK if You Add... That If you share a link like this...

https://isekaiscan.com/manga/boku-no-heya-ga-dungeon-no-kyuukeijo-ni-natteshimatta-ken/

And Press it... Is there Posibility that... Can go Directly to the App....

Another request.....

If I were to Share A Link From Google.. And Press Share...

Can you Add the Tachiyomi App... In the Share Button of the Google So that It Can Go directly to the App...

**Comment by AbdullahM0hamed** [comment] 2020-07-21 14:32
It is possible, and it belongs in the extension repo.

**Comment by arkon** [comment] 2020-07-21 14:33
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3865

**Closed by arkon** 2020-07-21 14:33 UTC
Labels: feature
