### ISSUE TITLE
[Feature Request] Download Next Chapter automatically while reading current chapter.

### ISSUE THREAD

**Issue by JonyBepary** [inorichi/tachiyomi#2915] opened 2020-04-21 00:16 UTC
Back in day while i was MR reader day had this feature. while was reading a chapter the next chapter of that manga automatically download (BTW that download was temporary when i finished that chapter it'll automatically vanish, like /temp ).
So in this process user get very smooth experience even the slow internet connection.
because i often found (specially in some scanslation site) that after reading a manga I'm waiting for another chapter fully load which is basically irritating (to solve this just download whole).
but still "Downloading Next Chapter automatically while reading current chapter." is a good feature to have.

**Comment by arkon** [comment] 2020-04-21 01:16
The app already starts preloading the next chapter into the cache when you're within the last 3 pages (in dev, last 1 page in stable).

**Comment by m-vlad** [comment] 2020-04-21 02:02
> The app already starts preloading the next chapter into the cache when you're within the last 3 pages (in dev, last 1 page in stable).

Surely if they request a change for this it means either the current approach isn't working as intended or the preload setting needs to be widened (maybe just load the next chapter as soon as you start reading a chapter, so tachi always has 2 chapters in cache)

**Comment by arkon** [comment] 2020-04-21 02:37
It was adjusted, hence the difference between stable and dev. We could potentially tweak it more, but it would've helped if the original poster had filled out the requested information in the template (i.e. the app version).

**Comment by arkon** [comment] 2020-04-26 22:15
Duplicate of #321

**Closed by arkon** 2020-04-26 22:15 UTC
Labels: feature
