### ISSUE TITLE
Making back button useful & Casting 

### ISSUE THREAD

**Issue by Studywolf20** [inorichi/tachiyomi#733] opened 2017-04-04 10:55 UTC
Features :-

1. Can you make, "to exit app we will have to press back button twice (it will prevent accidental closing of app)  also pressing back button once will open option panel (which have library,catalog, etc) actually when i keep my mobile horizontal opening that panel is little tedious 

2. Don't know if this is possible or not but Mira cast through which I can cast Manga on Android TV and volume key or my TV's Remote will be used to change pages due to this my mobile screen will be remain off( though i do use screen mirroring for that purpose but this drains my battery )

Thank you for one of the best feature that is making it possible to track my Manga on myanimelist easily even for each chapter which is also great :)
Thank you developer :) 👊😎👍

**Comment by inorichi** [comment] 2017-04-06 18:11
1. You can open the panel by dragging the left edge too. I'm against opening the panel with the panel button.

2. #646

**Comment by Studywolf20** [comment] 2017-04-06 18:35
What about giving on/off button?  for back button feature if somebody wants he/she can use it :) but No problem at all your choice ;).still 😁 thanks for making Reading Manga this much easy 👊😎👍

**Comment by arkon** [comment] 2020-01-04 21:06
Duplicate of #1005

**Closed by arkon** 2020-01-04 21:06 UTC
Labels: feature
