### ISSUE TITLE
[Feature Request] Add a flag for tracked and untracked manga in the library

### ISSUE THREAD

**Issue by loocool2** [inorichi/tachiyomi#1648] opened 2018-10-05 19:34 UTC
I have a LOT of manga (nearly 1k), and since I've had to retrack a lot of them due to the MAL API takedown, I have no idea which ones I haven't tracked and which ones I have tracked, which would save me a lot of time in the future, if MAL comes back or I want to switch to a different service

**Comment by PhaZ90771** [comment] 2019-01-12 07:01
I agree. This is especially the case when you read new manga, since more likely than not, the tracking sites haven't added that series yet.

Currently as a work around I've been tracking series through Google Keep when I start reading a series that hasn't been added to my tracking site yet.

It is very difficult to find these series after the fact, since you are forced to navigate through series one by one to track them down.

Even just having the check mark show up in the browse view would be a huge improvement.

**Comment by arkon** [comment] 2020-04-23 21:53
Duplicate of #1648

**Closed by arkon** 2020-04-23 21:53 UTC
