### ISSUE TITLE
[Feature Request] Private toggle for anilist tracking

### ISSUE THREAD

**Issue by aakash37** [inorichi/tachiyomi#3131] opened 2020-05-09 17:24 UTC
### Why/User Benefit/User Problem
This would help users to toggle the manga private as soon as tracking is added as anilist provides this feature, it would be great to have it.

### What/Requirements
A check box in the banner to toggle this feature

**Comment by arkon** [comment] 2020-05-09 17:34
Duplicate of #1671

**Closed** 2020-05-09 17:35 UTC
Labels: feature
