### ISSUE TITLE
[Feature Request] Extension Details

### ISSUE THREAD

**Issue by Mitia99** [inorichi/tachiyomi#3364] opened 2020-06-22 09:33 UTC
### Why/User Benefit/User Problem
Better extension/source management

### What/Requirements
Show multisource-multilingual details(like installed extension settings on tachiyomi preview r2447 )in extension window without having to download them.
![Screenshot_20200622_123330](https://user-images.githubusercontent.com/56766778/85272265-9cf1da80-b484-11ea-87a2-8a45e9b6b5f1.jpg)

**Comment by CarlosEsco** [comment] 2020-06-22 09:43
Details on an extension are unavailable unless it installed as the info is stored in the APK

**Comment by arkon** [comment] 2020-06-22 12:20
Duplicate of #1926

**Closed by arkon** 2020-06-22 12:20 UTC
Labels: feature
