### ISSUE TITLE
Source Error

### ISSUE THREAD

**Issue by HappyfaceJack** [inorichi/tachiyomi#1916] opened 2019-03-21 16:48 UTC
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** r1471

**Issue/Request:** identifier 'atob' undefined

**Other details:** com.squareup.duktape.DuktapeException: ReferenceError

Tried installing the latest version (0.8.1), results in same error.

**Comment by Hulkmaster** [comment] 2019-03-21 20:29
Same here

Reproduces for kissmanga and ReadComicOnline

**Comment by CarlosEsco** [comment] 2019-03-21 21:53
Duplicate of issue in extensions

**Closed by CarlosEsco** 2019-03-21 21:53 UTC
