### ISSUE TITLE
[Feature Request] Recently read option

### ISSUE THREAD

**Issue by tomodachikezo** [inorichi/tachiyomi#2944] opened 2020-04-23 20:57 UTC
---

### Device information
* Tachiyomi version: 0.8.5
* Android version: 5.1
* Device: Oppo

1. The recently read option doesnt work properly

Expected behavior, 
For example, I read a certain manga in a different app, then I decide to use this app. I would then search the manga and find the last chapter I read. Let's say I decide to d something else and return. I would click on the manga and press resume and it should go to the last chapter I pressed/reas

Actual behavior
I press the resume button,  but it would instead go to the 1st chapter since it wasn't marked as read. So I have to mark every chapter read for it to work properly. It's getting annoying.

**Comment by arkon** [comment] 2020-04-23 21:52
Duplicate of #1399

**Closed by arkon** 2020-04-23 21:52 UTC
Labels: bug

**Comment by CarlosEsco** [comment] 2020-04-23 23:11
To add you can also mark previous as read.
