### ISSUE TITLE
[Feature Request] Statistics / Tracking time

### ISSUE THREAD

**Issue by metroid112** [inorichi/tachiyomi#1320] opened 2018-03-23 04:28 UTC
I checked and while there was an issue regarding this, it was about 2 years ago, so I guess it wouldn't hurt requesting for it again since a lot has changed since then. 

Is there a chance that the app would be able to track the reading time of a certain manga (Example: it took you 3 hours to read all available chapters), and related statistics like reading speed (maybe seconds per chapter)?

It could be implemented calculating the time difference between opening a chapter and when you finally close it x chapters later (without counting the time that the screen is off) . I'm just an user so I can't figure out how it'd actually work or how feasible it is. 

Its not an urgent request, but it'd be pretty darn cool getting info like that. It's a feature I've seen on Moon Reader+ (app for reading books)

**Comment by wopian** [comment] 2018-03-23 07:07
While 2 years old, it's still a duplicate of #115

**Closed** 2018-03-24 10:00 UTC
