### ISSUE TITLE
[Bug] Unknown error when attempting bato.to source login and 403 when trying to restore from backup

### ISSUE THREAD

**Issue by 4naxagoras** [inorichi/tachiyomi#1034] opened 2017-10-13 04:27 UTC
![screenshot_2017-10-13-01-22-35](https://user-images.githubusercontent.com/13698095/31530351-3cb05816-afb6-11e7-8aa0-8811f96e8bba.png)
 
I am sure the login and password was input correctly (logging into bato.to via browser works). I don't have another Android device on hand to test whether this is device specific or not.

Device: Samsung Galaxy Tab E (SM-T113NU) running factory default Android 4.4.4. No root, xposed module or any sort of modification.
Version: latest dev build (r1246, build time 12 Oct 2017)

**Comment by LumpBloom7** [comment] 2017-10-13 08:22
Can also confirm this. Along with error 403 in catalogues when searching bato.to. Running RR 5.8.5, root, xposed.

**Comment by 4naxagoras** [comment] 2017-10-15 17:11
Update: I tried to restore the library from a backup file (full backup) and this was the log after 51 errors. I suspect both issues are related:

![screenshot_2017-10-15-15-07-51](https://user-images.githubusercontent.com/13698095/31587143-f04642a4-b1ba-11e7-9ab0-b10bb3a09947.png)

**Comment by LumpBloom7** [comment] 2017-10-15 17:32
Maybe you have been ipbanned on batoto. It doesn't affect the browser, just the API in most cases. Try going to the support forums and ask for an appeal. I did it and the next day it works perfectly.

HTTP error 403 usually stands for unauthorized access. So it it likely because of the above reason.

**Comment by Hitsun** [comment] 2017-11-06 10:53
So no solution for this yet? I'd experienced this issue twice. It's kinda fixed by the next day last time. Also, not ipbanned here. I mean, we won't be able to even access their site if we got ipbanned, no?

**Comment by mrskizzex** [comment] 2017-11-06 12:19
Error 403 happens when you try to restore backup while not logged in to batoto, its not an error with the backup system, it works as intended. I don't know why you get unknown error when logging in but i would change my passowrd to something like 12345678 and test if it works and if it does, logout and change it back and try again.

**Comment by Hitsun** [comment] 2017-11-06 12:31
I see, I'll keep that in mind. It's working now atm, just like last time. Not sure if it's a coincidence, but it happened on Sunday too this time.

**Closed** 2017-11-28 08:48 UTC
