### ISSUE TITLE
Ability to search for manga by author in tracking-page search box and "Catalogue" search box

### ISSUE THREAD

**Issue by sbstratos79** [inorichi/tachiyomi#758] opened 2017-04-17 19:51 UTC
I wish to make it so that Tachiyomi tracks my progress for a manga called "Happiness" by Oshimi Shuuzo, but since Happiness is a very common word for manga, the manga that I am looking for doesn't show up in the results in tracking page search box. Instead I get search results like  [these](https://cloud.githubusercontent.com/assets/4395586/25102017/2cc7a080-23d4-11e7-929e-bc572cc70029.png). It'd be great if we could search for manga by inputting the author's name so that all of that author's works show up in the search results. This option would also be useful for searching manga in the "Catalogue" screen. 

Version: 0.5.2

**Comment by inorichi** [comment] 2017-04-17 19:59
Duplicate of #663.

The catalogue screen already has filters, including by author (as long as it's supported by their search engine).

**Closed by inorichi** 2017-04-17 19:59 UTC
