### ISSUE TITLE
[Feature Request] A whole Tab dedicated to downloads

### ISSUE THREAD

**Issue by DragonVN03n** [inorichi/tachiyomi#2990] opened 2020-04-30 03:29 UTC
If you download a manga and haven't read the series and forget to save it to favorites, it wont appear at all. this is very annoying as you to scroll through source just to find it and add it to library. By adding A tab dedicated to Downloads, all downloads will appear in that tab even though you haven't Favorited the manga yet

**Comment by arkon** [comment] 2020-04-30 03:30
Duplicate of #412

**Closed by arkon** 2020-04-30 03:30 UTC
Labels: feature
