### ISSUE TITLE
(bug) Can't seem to download a page

### ISSUE THREAD

**Issue by QuiGonSwag** [inorichi/tachiyomi#262] opened 2016-04-19 07:17 UTC
When trying to read the manga "D.I.C.E" it doesn't seem to like the large picture size or something because when looking in browser it is fine, but when viewing with the rapid decoder it is just a black screen, and with the other decoder it says it isn't downloaded and asks me to retry, but never actually downloads. 

Version: v0.2.0
(Android)

**Comment by QuiGonSwag** [comment] 2016-04-19 07:21
Chapter 11 is a perfect example.

**Comment by wopian** [comment] 2016-04-19 10:34
What manga source? DICE works fine using ReadMangaToday.

Edit: Chapter 11 Page 2 of `DICE: the cube that changes everything` doesn't load the image using Mangahere as a source.

**Comment by QuiGonSwag** [comment] 2016-04-20 06:34
ReadMangaToday seemed to work better but still had the same issue at later chapters.

**Comment by Bloodwork** [comment] 2016-04-20 11:25
I had a similiar issue today with 0.2.0 on this page http://img.bato.to/comics/2016/04/18/s/read571510ddc14c0/img000006.png 

Tachiyomi doesn't say anything - there is no option to retry or do anything really, the page is just white in app while it loads up just fine in my browser. 

Tachiyomi indeed has problems with big pages.

**Comment by inorichi** [comment] 2016-04-20 11:44
Sometimes the image is decoded, but it refuses to render in the screen and it does not get an on error callback because it's decoded. It (most probably) has to be fixed in the subsampling library.

**Comment by inorichi** [comment] 2016-04-21 12:29
Well, this is not a bug in tachiyomi and I think the only workaround for this is to reencode the image. I'll add this option to the advanced tab, probably.

Enabling that option and using Skia would probably give the best experience.

**Closed** 2016-04-27 12:04 UTC
