### ISSUE TITLE
[Feature Request] Export and import configuration

### ISSUE THREAD

**Issue by juniornff** [inorichi/tachiyomi#2827] opened 2020-04-06 01:32 UTC
### Why/User Benefit/User Problem
I as a user that have multiples devices (also for the people that get a new device and has to re install Tachiyomi), the proccess of prepare Thachiyomi for be ready to use in other devices take more time than should be because i have to reconfigurate all the settings. If we could export that custom settings in a file and then import it in another device should be excellent. 

### What/Requirements
The option could be in the backup section, the option to export and import settings can be below the 2 first options or wherever you wanted. It can be saved as a Json file or as be convenient.

The file can be saved in the same folder as the manga backups. It does not have to be saved periodically, only when the user decides to save the configuration

**Comment by thatsmekaustubh** [comment] 2020-05-01 08:37
This could be a Sync Feature.Do it locally - zip file or Google Drive Based. 

Can expand scope of this project to next level.
Nice  @juniornff

**Comment by arkon** [comment] 2020-05-09 14:39
Duplicate of #1857

**Closed by arkon** 2020-05-09 14:39 UTC
Labels: feature
