### ISSUE TITLE
[Bug] Webtoon scroll limit hit before end of last manga page on double-tap zoom following multi-page zoom-out

### ISSUE THREAD

**Issue by geominorai** [inorichi/tachiyomi#3203] opened 2020-05-19 10:17 UTC
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Samsung Galaxy S9+

## Steps to reproduce
1. Enable webtoon or continuous vertical viewer mode
2. Open last manga chapter of a series
3. Scroll to a few pages before end of manga
4. Zoom out completely so multiple pages are visible
5. Double-tap to zoom back in
6. Attempt to scroll to last page

### Expected behavior
The last manga page should be fully visible and scrollable.

### Actual behavior
Halfway through the last or second-last manga pages is the furthest scrolling possible until changing zoom.

### Other details
[Video 1, on main](https://i.imgur.com/hn8YlGk.mp4)
[Video 2, on J2K](https://i.imgur.com/WtQgDos.mp4)

**Comment by arkon** [comment] 2020-05-19 10:40
Duplicate of #3052

**Closed by arkon** 2020-05-19 10:40 UTC
Labels: bug
