### ISSUE TITLE
Full Manga Name

### ISSUE THREAD

**Issue by cd0rw0** [inorichi/tachiyomi#1141] opened 2017-12-31 12:00 UTC
Hi

a lot of manga have long name but we cant find full name anywhere even after we open manga due limited space in title bar (refer screenshot)

since we have alot space in info page, maybe we have full name in info page 

<a href="https://ibb.co/nEod2G"><img src="https://image.ibb.co/ib1y2G/Screenshot_20171231_195006.jpg" alt="Screenshot_20171231_195006" border="0"></a>

**Comment by inorichi** [comment] 2017-12-31 12:34
If you rotate to landscape you'll see more text. I think the table view isn't going to be any better. In that screenshot, author is taking 26 characters and the toolbar 24.

**Comment by QuestofIranon** [comment] 2017-12-31 12:58
I tried it out and there isn't much of a gain in length
![screenshot](https://user-images.githubusercontent.com/2449351/34461723-edd07d4a-edf7-11e7-8cbb-03aae0fe68ff.png)

**Comment by cd0rw0** [comment] 2017-12-31 13:29
@inorichi yap know about that, it just feel awkward to rotate just to see full name 
@QuestofIranon How about 
bold & bigger size 
remove "Title" (automatically know it a name bcos its bigger then rest)
and make it 2 line ( even longer name can be seen)

**Comment by QuestofIranon** [comment] 2017-12-31 13:39
I tried something different

![image](https://user-images.githubusercontent.com/2449351/34461914-a848547c-edfd-11e7-8597-62c6d1fd90e0.png)

**Comment by Johndeep** [comment] 2018-01-10 21:21
Hmm, I think the Idea to put it into the description is quite good, but can you add an empty space between title and description? So it won't get too tight there, like this:
___
**Gaikotsu Kishi-sama.. [..]** <- maybe highlighted with little bit dark red or other "passive" color

**Description**
The protagonist.. [..]
___
This is just a fine tuning if you like. Maybe we could remove the title from the actionbar just to avoid redundancy.

**Comment by cd0rw0** [comment] 2018-01-11 00:42
@Johndeep for latest mockup & progress you should follow up here in PR #1139

**Comment by Johndeep** [comment] 2018-01-11 17:46
Oh, I did miss that, or rather, I didn't know this Issue is now somehow.. a duplicate of that?

**Closed** 2018-01-18 18:15 UTC
