### ISSUE TITLE
[Feature Request] Chapter detection within volume-based local manga

### ISSUE THREAD

**Issue by Razer1103** [inorichi/tachiyomi#3669] opened 2020-08-13 19:18 UTC
Most manga I download in bulk from sources other than those Tachiyomi extensions support, separate the manga into volumes, usually in .cbr, .cbz, .rar, or .zip format, which Tachiyomi beautifully supports reading, but it interprets "v1 (2020)" which is the volume number and release year, as 'volume 1 chapter 2020', which isn't a huge deal, but it makes automatic tracking impossible. Typically these volume archives separate chapters by one of two methods; The first method is by numbered directories. The second method is to have all pages in the root directory of the archive, and include the chapter number in the filename for the images. For example: "Title - c026 (v03) - p0122 [digital] [Scanlator].jpg". Tachiyomi can use some smarts to determine which part of the image name is the chapter number, against the volume number, page number, and year of publication if present. 

I would like Tachiyomi to detect when local manga is bundling chapters into volumes, and display the chapters in the fashion you'd expect, using parts of the file names or folder structure within the archive to determine what pages belong to what chapter.

**Comment by Razer1103** [comment] 2020-08-13 19:22
I understand an issue similar to this one is Open already, but I chose to open a new issue as mine is more of a feature request rather than a question. I understand the workaround to the previous issue, but I am requesting a feature to handle it instead.

https://github.com/inorichi/tachiyomi/issues/1117#issue-280279193

**Comment by arkon** [comment] 2020-08-13 19:24
#1117 is also a feature request. You could comment on that with anything that's different, but this sounds like it's the same request?

**Comment by arkon** [comment] 2020-08-17 13:58
Closing as duplicate of #1117

**Closed by arkon** 2020-08-17 13:58 UTC
Labels: feature
