### ISSUE TITLE
Save mangas in cbz or cbr format

### ISSUE THREAD

**Issue by wruizcanal** [inorichi/tachiyomi#2467] opened 2020-01-10 00:07 UTC
**App version:**
0.8.4
**Android version:**
9.0
**Issue/Request:**
I wish it were possible to save the comics in cbz or cbr format so as not to have the images loose in folders.

**Comment by arkon** [comment] 2020-01-10 00:12
Duplicate of #918

**Closed by arkon** 2020-01-10 00:12 UTC
