### ISSUE TITLE
Add a volume setting on MyAnimeList tracking

### ISSUE THREAD

**Issue by Rinto-kun** [inorichi/tachiyomi#649] opened 2017-01-24 09:13 UTC
The title says it, when I mark a manga in Tachiyomi as completed, it doesn't mark the actual number of volumes on MAL, it's basically a minor problem, though.

**Comment by inorichi** [comment] 2017-01-24 11:46
Duplicate of #505

**Closed by inorichi** 2017-01-24 11:46 UTC
