### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ArjixGamer** [inorichi/tachiyomi#2421] opened 2020-01-04 12:45 UTC
**App version:**
latest Dev
**Android version:**
8.0
**Issue/Request:**
[Feature Request]
**Steps to reproduce (if applicable)**

 1.Go to Download manager
 2.select a chapter
 3.delete it without clearing all the downloading list

**Other details:**
This is just my suggestion but if it has more than 40 in the queue then it will be such a pain to re-queue what was cleared so wouldnt it be beter add individual clearing off the queue?

**Comment by hXtreme** [comment] 2020-01-04 12:54
Duplicate of #809

**Closed** 2020-01-04 14:51 UTC
