### ISSUE TITLE
[Feature Request] <Automatic backup on google drive (as in "WhastApp")>

### ISSUE THREAD

**Issue by EduSFreitas** [inorichi/tachiyomi#3648] opened 2020-08-11 02:29 UTC
Currently, whenever I use a different device to read, I need to create a backup to synchronize my library and transfer the backup from one device to another.

I believe it would be much more interesting and practical if the backup was saved to the google drive for example as the "WhastApp" application does, so the application can automatically sync our library on any device when it is opened.

Thanks.

**Comment by scb261** [comment] 2020-08-11 06:42
Duplicate of #912

**Closed** 2020-08-11 12:00 UTC
Labels: feature
