### ISSUE TITLE
[Feature Request] parallel / independent downloads for different sources

### ISSUE THREAD

**Issue by asdkant** [inorichi/tachiyomi#3060] opened 2020-05-03 23:48 UTC
### Why/User Benefit/User Problem
While I understand the reasons for not doing parallel downloads on multiple chapters of a single source (avoiding IP bans, as per the FAQ), downloading from two different sources at the same time should not present an issue. The same optimization could be had for update checking.

### What/Requirements
- Chapters from different sources should be downloaded independently
- Update checking could also happen for different sources independently

**Comment by arkon** [comment] 2020-05-03 23:51
Duplicate of #2534

**Closed** 2020-05-03 23:51 UTC
Labels: feature
