### ISSUE TITLE
Folders' name of downloaded chapter become too long as it's not truncated

### ISSUE THREAD

**Issue by leehwongxing** [inorichi/tachiyomi#2312] opened 2019-11-04 06:18 UTC
**App version:** 0.8.4

**Android version:** 9 (Xiaomi Redmi 7A/MIUI 10)

**Issue/Request:** Folders' name of downloaded chapters become too long as the folders' name of series and chapters did not get truncated (properly). 

**Steps to reproduce (if applicable)**

 1. Browse LHTranslation (English) in Catalogues
 2. Download the latest chapter
 3. Open the default file browser on the phone and try to rename that chapter's folder name
4. Error happens.

![Screenshot_2019-11-04-13-13-41-200_com mi android globalFileexplorer](https://user-images.githubusercontent.com/32384712/68102399-1b553880-ff05-11e9-9eb9-5d15b7bc400e.png)

**Other details:**
This may seems to fall under Catalogue but the download function is working precisely the same across the catalogues. Guess the download code is from the main app.

**Comment by arkon** [comment] 2020-02-23 15:12
Duplicate of #2357

**Closed by arkon** 2020-02-23 15:12 UTC
