### ISSUE TITLE
[Feature Request]Tracker anime-planet.com

### ISSUE THREAD

**Issue by Fahad1998** [inorichi/tachiyomi#2039] opened 2019-05-17 20:57 UTC
Any plan to add anime-planet.com tracker?

**Comment by de-odex** [comment] 2019-05-21 10:41
tag with [Feature Request] please

**Comment by Vesnyx** [comment] 2019-05-26 00:52
Dupe of my issue here #1785 . I'm currently planning on adding this in once the app hits the 1.0 milestone. I don't know if it'll impact the authentication methods currently used and I'd rather have it done all at once. :)

**Closed** 2019-05-26 01:06 UTC
