### ISSUE TITLE
[Feature Request] "Tracking" filter for Library

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3141] opened 2020-05-10 11:22 UTC
### Why/User Benefit/User Problem
This would be helpful to view what manga you've already tracked (or what manga you haven't tracked if #3140 gets implemented).

Always useful for people with huge libraries.

**Comment by arkon** [comment] 2020-05-10 14:01
Duplicate of #1899

**Closed by arkon** 2020-05-10 14:01 UTC
Labels: feature
