### ISSUE TITLE
[SOLVED] Notch space issue on Xiaomi mi 9

### ISSUE THREAD

**Issue by tonarii** [inorichi/tachiyomi#2109] opened 2019-07-01 08:15 UTC
Hello, thanks for this great app.
I'm having an issue regarding the use of the notch. 

**App version:**
r1517
**Android version:**
miui 10.2.26.0 / android 9 pkq1.181121.001
**Issue/Request:**
issue regarding the use of the notch space in read mode
It works great in the menu and settings pages but not in reading mode. 
**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
I'm on a Xiaomi mi 9
Full screen mode activated in both app and xiaomi preferences for notch mode use.

**Comment by hXtreme** [comment] 2019-07-01 08:36
Please describe your problem accurately.

**Comment by tonarii** [comment] 2019-07-01 08:41
when i start the app, it's in full screen, for instance if i click on the menu, to change settings, i can see that the app use the notch space area. But when i start to read a manga, if i zoom in, i can see that the notch space is not used, even with the full screen mode activated.

**Comment by hXtreme** [comment] 2019-07-06 12:10
Now that you mention it, seems like I also have this problem on my Pocofone (also by Xiaomi)

**Comment by tonarii** [comment] 2019-07-07 15:28
I solved it on Neko, and that also works here (i tried on the last beta, but that should be ok on the normal release i think), it would be great to have it inside the official release in case of a new update.
I edited the styles.xml file inside the value-26 folder to add this line : 
`<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`

So here is the complet file : 
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Base.Theme.AppCompat" parent="@style/Base.V26.Theme.AppCompat" />
    <style name="Base.Theme.AppCompat.Light" parent="@style/Base.V26.Theme.AppCompat.Light" />
    <style name="Base.Widget.AppCompat.Toolbar" parent="@style/Base.V26.Widget.AppCompat.Toolbar" />
    <style name="Base.Widget.Design.AppBarLayout" parent="@style/Base.V26.Widget.Design.AppBarLayout" />
    <style name="Base.V26.Theme.AppCompat" parent="@style/Base.V23.Theme.AppCompat">
        <item name="colorError">?android:colorError</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
    <style name="Base.V26.Theme.AppCompat.Light" parent="@style/Base.V23.Theme.AppCompat.Light">
        <item name="colorError">?android:colorError</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
    <style name="Base.V26.Widget.AppCompat.Toolbar" parent="@style/Base.V7.Widget.AppCompat.Toolbar">
        <item name="android:touchscreenBlocksFocus">true</item>
        <item name="android:keyboardNavigationCluster">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
    <style name="Base.V26.Widget.Design.AppBarLayout" parent="@style/Base.V21.Widget.Design.AppBarLayout">
        <item name="android:touchscreenBlocksFocus">true</item>
        <item name="android:keyboardNavigationCluster">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
</resources>`

And now we can enjoy a full screen reading  :)

**Comment by hXtreme** [comment] 2019-07-07 15:36
Did you make a pull request for the fix? You might want to refer this issue from the request.

**Comment by tonarii** [comment] 2019-07-07 15:44
No i did not, but i will do it now.

**Comment by arkon** [comment] 2019-12-22 20:28
Duplicate of #1621

**Closed by arkon** 2019-12-22 20:28 UTC
