### ISSUE TITLE
[Feature Request] <Auto scrolling>

### ISSUE THREAD

**Issue by akchaudhary6532** [inorichi/tachiyomi#4122] opened 2020-12-13 13:03 UTC
## Why/User Benefit/User Problem
For binge readers, reading in webtoon mode, it becomes really annoying to keep scrolling manually after a while, as their hand/thumb start to hurt from continues scrolling.

## What/Requirements
User would set the speed of scrolling before turning on the feature.
In webtoon mode, when this feature is on, the screen would start scrolling automatically at the set speed, but the user can still scroll up or down and auto scrolling would resume from that location.

**Comment by scb261** [comment] 2020-12-13 13:33
Duplicate of #2093

**Closed** 2020-12-13 14:35 UTC
Labels: feature
