### ISSUE TITLE
Zoom changes when menu appears

### ISSUE THREAD

**Issue by gotson** [inorichi/tachiyomi#1859] opened 2019-02-27 05:55 UTC
**App version:**.0.8.0

**Issue/Request:** I have an issue when touching the screen to show the top and bottom menu bars, it changes the zoom setting slightly. 

I am running version `0.8.0` on a OnePlus 6T.

See screenshots before touching the screen, just after touching, and after touching a second time to remove the menu, notice the zoom is slightly bigger from the second screenshot.
It happens with both `fit to height` and `smart fit`. 

![screenshot_20190227-133754](https://user-images.githubusercontent.com/2139133/53469045-72159300-3a97-11e9-8055-52f202df4f33.jpg)
![screenshot_20190227-133804](https://user-images.githubusercontent.com/2139133/53469046-72ae2980-3a97-11e9-95c1-8f5bff0734fe.jpg)
![screenshot_20190227-133809](https://user-images.githubusercontent.com/2139133/53469047-72ae2980-3a97-11e9-9941-814693165e78.jpg)

**Steps to reproduce (if applicable)**

 1. Have page zoomed out to the maximum.
 2. Touch screen to make top/bottom menu bar appear.
 3. Touche screen again to make top/bottom menu bar disappear.

**Comment by inorichi** [comment] 2019-03-01 10:00
I can't reproduce on my OnePlus 5. I've asked a friend with a 6T and he can't reproduce either... Are you using a custom ROM or something?

**Comment by gotson** [comment] 2019-03-01 12:18
Nope, no custom rom, just stock oxygen on the latest version.

**Comment by gotson** [comment] 2019-03-02 02:25
I tested a bit more, it happens on smart fit and fit to height for double page manga when reading in portrait orientation. 
For single page manga, it happens only in fit to height in portrait orientation.

I don't have the issue when using fit to width in landscape orientation for instance.

**Comment by gotson** [comment] 2019-03-02 05:17
I just activated oneplus fullscreen mode for the app (displays on the full screen, removes the top bar and notch), and it behaves properly.

**Comment by inorichi** [comment] 2019-03-27 12:51
Closing since you found a fix. I don't think it's something I can control from the app anyways.

**Closed by inorichi** 2019-03-27 12:51 UTC
