### ISSUE TITLE
[Feature Request] Filter by Tracked/Not Tracked

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi#3561] opened 2020-08-02 05:41 UTC
Why/User Benefit/User Problem
So users can keep track of what is being tracked via their linked tracking service.

What/Requirements
Can be added under the filters tab in the library

Helpful resources
This feature is present in Sy
https://github.com/jobobby04/TachiyomiSY/commit/6a0ab3526a3d5c0f1a9966e4ee379d9579a1620f, 
https://github.com/jobobby04/TachiyomiSY/commit/e6f5ea172a88db51ae5a9771b0d359e0adee22ef, 
https://github.com/jobobby04/TachiyomiSY/commit/3aee05bf26f4147b074e88ab1386e61d0025ddfc

**Comment by scb261** [comment] 2020-08-02 08:29
Duplicate of #1899 but with useful links?

**Closed** 2020-08-02 13:46 UTC
Labels: feature
