### ISSUE TITLE
[Feature Request] Jump to Chapter list when viewing a manga from Library

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3362] opened 2020-06-21 22:50 UTC
[ This is not a request to revert changes nor to make a toggle to switch to old style. (like SY does) ]

### Why/User Benefit/User Problem
Before, when you view a manga from your library, it always directed to the Chapters tab. Now with the merged Info + Chapters tab, a huge part of the screen (~70%) is always wasted by the Info section. It could instead just jump straight to Chapters list when you're viewing from Library—emulating the previous behaviour.

**Comment by arkon** [comment] 2020-06-21 22:51
Duplicate of #3353

**Closed by arkon** 2020-06-21 22:51 UTC
Labels: feature

**Comment by vengiare** [comment] 2020-06-21 22:54
This is a different request than #3353. I'm not asking to split Info and Chapters list. I thought i clarified that already.

**Comment by vengiare** [comment] 2020-06-21 23:03
@arkon Hope you kindly re-read the suggestion.

**Comment by arkon** [comment] 2020-06-21 23:06
I know. That's the only thing I'd consider for #3353 anyway.

**Comment by vengiare** [comment] 2020-06-21 23:08
Then it should make this not a duplicate then.
