### ISSUE TITLE
All installed extentions disappear restarting

### ISSUE THREAD

**Issue by teo3300** [inorichi/tachiyomi#2488] opened 2020-01-12 01:46 UTC
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

Apparently with no reasons,  nothing differs even changing various settings or the selected sources

Extentions get installed and it's possible to use them, but after rebooting the app they disappear and need to be reinstalled to be used again

**Comment by arkon** [comment] 2020-01-12 03:30
Duplicate of #2369

**Closed by arkon** 2020-01-12 03:30 UTC
Labels: bug
