### ISSUE TITLE
Manga statistics

### ISSUE THREAD

**Issue by IamHeinous** [inorichi/tachiyomi#450] opened 2016-09-05 09:47 UTC
Version: v. 0.2.3
Android Marshmallow

Statistics:
Total Manga
Total Read Chapters
Total Read Pages (this may need a long time to update as this requires to scan for all pages online) 
Total Estimated reading time
Unread Manga Chapters

**Comment by NoodleMage** [comment] 2016-09-22 19:51
Duplicate of issue #115

**Closed by NoodleMage** 2016-09-22 19:51 UTC
Labels: feature
