### ISSUE TITLE
Adding some features about local library 

### ISSUE THREAD

**Issue by Hypeouseaus** [inorichi/tachiyomi#877] opened 2017-07-03 15:13 UTC
Local library has lacks of features that should be added.

First, **Default path setting.**
Default path to local library is limited to /tachiyomi/local.
I suggest that making it possible to modify default path on(in?) 'Settings - local'

Second, **compression file format supporting.**
Tachiyomi doesn't support compression file formats like 7z, zip, rar for local library.

Third, **Making a button for adding manga files from sdcard.**
If you want to add a manga from sdcard, You have to download zip files, open some astro-like application, then extract it to /tachiyomi/locals.

It requires too many steps. I suggest that making a button on bottom-right for adding manga files in local library. 

You can press a button, select zip/7z/rar files, add manga to local libary If there is this button.

Thank you for reading my suggestions despite of my lack of English skills.

**Comment by j2ghz** [comment] 2017-07-03 15:34
>Supported chapter formats are directories with pictures inside, ZIP/CBZ, RAR/CBR and EPUB. But expect better performance with directories and ZIP/CBZ.
- https://github.com/inorichi/tachiyomi/wiki/Local-manga
I use zip's and they work for me. Can you try again/look for errors?

**Comment by Hypeouseaus** [comment] 2017-07-03 15:51
What I'm suggesting is supporting those formats without making additional directory.

**Comment by inorichi** [comment] 2017-07-04 14:08
1) Duplicate of #662 

2) It does. A folder is still required to name the manga and generate a cover. The app is not meant for single chapter/short comics.

3) You have to download/copy them somewhere anyways first. I don't see any improvement.

**Closed by inorichi** 2017-07-04 14:08 UTC
