### ISSUE TITLE
Change last read page behavior

### ISSUE THREAD

**Issue by paulo27ms** [inorichi/tachiyomi#1547] opened 2018-07-25 21:07 UTC
**App version:** v0.7.4

Current behavior when you're reading a chapter and exit it halfway is that it counts the page you're on as read and starts you off in the next page.
This has 2 issues:
1. If you're in webtoon mode where there's no page border, you might end up having one page "open" while you're reading the previous one, meaning that when you exit you'll be 2 pages ahead of where you were. Imagine you're at the bottom of page 11, at this point Tachiyomi might show page 12 at the bottom if you scroll into it, if you exit now when you open the chapter again you'll be on page 13.
2. Chapters with 1 page. For example, Tomo-chan, when you're reading a chapter and exit, it'll mark that chapter as read and since it'll try to put you on the "next page" it ends up on the next chapter, which ends up being marked as read. **When you exit a chapter with one page, the chapter after it is marked as read automatically.**

My suggestion is to simply load the chapter on your current page, instead of marking the current page you're in as "read" and putting you on the next one automatically when loading, load to the page you left off on.

**Comment by inorichi** [comment] 2018-08-04 21:26
1. Somewhat improved on the new reader because it now checks with the bottom edge of the page instead of top edge (the page must be completely visible from the bottom).
2. Working as intended. Otherwise the last chapter would never be marked as read.

**Comment by inorichi** [comment] 2018-08-05 01:39
Sorry, I didn't understand the issue. 

Due to point 1 being fixed, it won't happen anymore unless the page of the next chapter is completely visible.

**Closed** 2018-09-01 15:13 UTC
