### ISSUE TITLE
[Feature Request] <Clear History>

### ISSUE THREAD

**Issue by historiatachi** [inorichi/tachiyomi#3639] opened 2020-08-10 07:54 UTC
I want to request a feature that can  "clear all history" inside "History" section. It's hard to remove 1 by 1 and I bet everyone wants that feature! So please fulfill my request on this one onegai! Just an ability to clear all history!! 

Or, give us a choice if we want that "history" section appear inside Tachiyomi.. so we can remove that section and don't need to clear it anymore.

-Thank you

---

### Why/User Benefit/User Problem
(It's hard to delete what we have read. Especially adult manga with nsfw thumbnail)

### What/Requirements
(Something like Google Chrome has made, clear all history)

**Comment by historiatachi** [comment] 2020-08-10 08:05
@arkon I wish you can fulfill my request.

**Comment by scb261** [comment] 2020-08-10 08:25
Duplicate of #1799

**Comment by historiatachi** [comment] 2020-08-10 08:28
> Duplicate of #1799

That's 2019 and still haven't fixed yet

**Comment by scb261** [comment] 2020-08-10 08:47
It's the same feature request and there is no need to have two of them

**Comment by historiatachi** [comment] 2020-08-10 08:51
> It's the same feature request and there is no need to have two of them

Like I said that's already old.. they probably forgot it already.. I request this last year inside Discord and still no update about this thing yet.. so I guess maybe I'll just go through GitHub tho..

**Comment by CarlosEsco** [comment] 2020-08-10 10:28
1. Dupes are gonna be closed.  
2. Don't also ping people for no reason. 
3. Finally not every ticket is going to get implemented. You are free to open a pull request with the feature implemented

**Closed** 2020-08-10 10:28 UTC
Labels: feature
