### ISSUE TITLE
[Bug] Android buttons and status bar covering reader settings header/footer

### ISSUE THREAD

**Issue by ZXY101** [inorichi/tachiyomi#3604] opened 2020-08-05 10:23 UTC
### Device information
* Tachiyomi version: Stable 0.10.3
* Android version: 7.1.1
* Device: Sony Xperia Z5

## Steps to reproduce
1. Open a manga to read
2. Have fullscreen enabled
3. Tap the center  of the screen

### Expected behavior
The reader header and footer should appear clearly.

### Actual behavior
The reader header and footer appear but they are quickly covered by the android buttons and status bar.

### Other details
Was not an issue on v0.10.1.
- v0.10.1:
![image](https://user-images.githubusercontent.com/39561296/89401898-509de980-d716-11ea-93c6-2dc3b8c90400.png)
- v0.10.3:
![image](https://user-images.githubusercontent.com/39561296/89401918-58f62480-d716-11ea-98df-1f0837d4a01e.png)

**Comment by scb261** [comment] 2020-08-05 11:04
Duplicate of #3586. Already fixed, wait for 0.10.4

**Closed** 2020-08-05 11:26 UTC
Labels: bug
