### ISSUE TITLE
[Feature Request] BOOKMARK WHILE READING CHAPTER

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi#2527] opened 2020-01-21 10:01 UTC
*User Benefit/User Problem*
This feature will help user to bookmark certain chapter during  binge reading without interruption of exiting book marking and then coming back to the chapter.
This whole process would make user experience much better and seamless.

*What/Requirements*
while reading a chapter the user can use setting button/or a dedicated button to simply bookmark the chapter by pressing it.

Thankyou for listening to my request. Hope to see this feature soon.

**Comment by arkon** [comment] 2020-03-07 23:16
Duplicate of #1413

**Closed by arkon** 2020-03-07 23:16 UTC
Labels: feature
