### ISSUE TITLE
[Bug] Download status not directly appearing when you start a download

### ISSUE THREAD

**Issue by MrAndre96** [inorichi/tachiyomi#3524] opened 2020-07-26 06:39 UTC
### Device information
* Tachiyomi version: r2569
* Android version: Android 9
* Device: Oneplus 5t

## Steps to reproduce
1. Go to a manga
2. Long click on a chapter
3. Download a chapter
4. See if on the right side of said chapter the download status appears

### Expected behavior
Normally it would state on the right side the download status queue, downloading and downloaded.

### Actual behavior
Now you first have to scroll down and then up again to see the current download status.

**Comment by arkon** [comment] 2020-07-31 01:15
Duplicate of #3358

**Closed by arkon** 2020-07-31 01:15 UTC
Labels: bug
