### ISSUE TITLE
[Feature Request] Improve Resume feature 

### ISSUE THREAD

**Issue by Indiangamer007** [inorichi/tachiyomi#4128] opened 2020-12-14 01:32 UTC
When clicking on resume button, it should take to page/chapter where you last left instead of latest read chapter. 
For example, if I've read a novel to chapter 500, but then started reading from 1st chapter, now I've to remember where I left because if I click on resume it'll take me to 501th chapter 1st page, bcoz that was unread chapter and it will get resumed, intead of my last read page. 
Manga Rock had this feature. 
---

## Why/User Benefit/User Problem
(will be helpful if we re-read a novel, incase we left it in middle due to slow update, but decided to read from 1st chapter) 

## What/Requirements
(resume button resumes reading feom last read page instead of 1st unread chapter)

**Comment by arkon** [comment] 2020-12-14 01:33
Duplicate of #1399

**Closed by arkon** 2020-12-14 01:33 UTC
Labels: feature
