### ISSUE TITLE
[Request] Search Suggestions

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi#1676] opened 2018-10-20 19:45 UTC
Let's say I do a global search for Bleach, I choose a source but it has a bad quality and for some reason the app closes, it would be nice if the Search Box reminded it and suggest me to search for it instead of writing down again the title of the manga. This is nice for those mangas with long and difficult names.

**Comment by arkon** [comment] 2020-01-04 21:56
Duplicate of #779

**Closed by arkon** 2020-01-04 21:56 UTC
