### ISSUE TITLE
[Bug] Progressbar circle offset

### ISSUE THREAD

**Issue by Presac** [inorichi/tachiyomi#1756] opened 2018-11-29 10:50 UTC
App version 0.8.0

When inside the reader, the circle of the progressbar is offset upwards.
 
The screen size of the device is 800x1280 pixels

Device: Samsung Galaxy Note 10.1 2014 Edition
Android:  5.1.1

![progressbar_offset](https://user-images.githubusercontent.com/10221581/49216614-cbecbb00-f3cb-11e8-8d8a-37ddaf49be06.png)

**Comment by arkon** [comment] 2020-01-19 22:28
Duplicate of #2487 (and is now fixed)

**Closed by arkon** 2020-01-19 22:28 UTC
