### ISSUE TITLE
Mangafox bug

### ISSUE THREAD

**Issue by Soldiercolur** [inorichi/tachiyomi#478] opened 2016-09-22 21:24 UTC
When attempting to read a chapter sourced from Mangafox it closes out and says "Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference"

https://www.youtube.com/watch?v=hp88e3vQq6I

Batoto and kissmanga sources still work for me.

Version: v0.2.3
Android: 6.0.1
Device: Nvidia shield k1

**Comment by ThePreviousOne** [comment] 2016-09-29 06:47
I believe Mangafox is at fault here. I just checked and most of the mangas I had through them are no longer in the catalogue

**Comment by GreyAsteroid** [comment] 2016-09-29 21:18
I'm also affected by this issue. I cannot read any manga sourced at Managafox, results in the same error.

**Comment by kabuto93** [comment] 2016-10-03 22:00
Seems to relate to MangaFox series that are marked as licensed. MangaFox still catalogues releases, but you can not read them.

**Comment by inorichi** [comment] 2016-10-06 17:53
I can't reproduce, but as @kabuto93 said if the content is removed, there's nothing to do.

**Comment by GreyAsteroid** [comment] 2016-10-09 21:31
I don't believe what @kabuto93 has said is the reason for this. I'm loading MangaFox's website and can read countless series but on Tachiyomi I have not been able to find a single series that loads. Everything from the most popular to less popular obscure webtoons/doujinshi refuses to load and gives me an error.

**Comment by GreyAsteroid** [comment] 2016-10-12 22:41
@inorichi could you reopen this bug?

**Comment by inorichi** [comment] 2016-10-13 07:21
Yes, but I can't help without the response the app is getting (wireshark or debugging the app).

**Comment by GreyAsteroid** [comment] 2016-10-13 09:00
I will happily get that information to you. I can give you the snippet from my logcat of the error it gives me right here http://pastebin.com/raw/jeAuEuBs However I've never used wireshark before so I'm not sure exactly how to find what you need. I've had no problem setting it up to receive packets from my phone though.

**Comment by GreyAsteroid** [comment] 2016-10-13 09:19
I have my phone connected to a hotspot running from a usb wifi antenna with wireshark watching the antenna. I can capture the response but I'm not sure exactly what I need to export. Can I give you a pcapng file? or do I need to give you something else?

**Comment by inorichi** [comment] 2016-10-13 09:28
Whatever is fine, as long as it contains the response from the site. You can email me the file if you want (it's in my profile).

**Comment by GreyAsteroid** [comment] 2016-10-13 09:31
I'll just give you a link https://drive.google.com/open?id=0BzqE0bTePMvjRGJwTlIzRzhXTWc That's the only packet that shows up when using the filter you gave me, hopefully this is what you need

**Comment by inorichi** [comment] 2016-10-13 09:37
That only contains the request, the one I'm interested in is the response, where the "Destination" field is your IP address.

**Comment by GreyAsteroid** [comment] 2016-10-13 09:38
I figured that might be the case, here's the full list of packets without the filter on https://drive.google.com/open?id=0BzqE0bTePMvjZm00eHdqUlVpaTQ

**Comment by inorichi** [comment] 2016-10-13 09:45
This one helps.

`<span style="color:#cc3300;float:right;font-style:italic;font-weight:700">Sorry, its licensed, and not available.</span>`

Do you see the same message from your PC?

**Comment by GreyAsteroid** [comment] 2016-10-13 09:57
Apparently kabuto93 was right. This whole time I've been Googling mangafox to get to the website and the first result is their mobile site which doesn't give me any warnings about licensing. After finding the desktop website I can see the licensing warnings and find a few manga that work through the app. This bug can be closed and chalked up to my stupidity.

**Comment by inorichi** [comment] 2016-10-13 09:59
No problem. I will try to show that message as the error in the app.

**Comment by inorichi** [comment] 2016-10-16 19:09
You should at least see a more readable "Page list is empty" error now.

**Closed by inorichi** 2016-10-16 19:09 UTC
Labels: bug
