### ISSUE TITLE
[Feature Request] Include Volume editing in the "Tracking" too

### ISSUE THREAD

**Issue by Umairuem** [inorichi/tachiyomi#3946] opened 2020-10-16 13:22 UTC
## Why/User Benefit/User Problem
Tracking in Tachiyomi is a really handy method to update them in their respective sites. But for the manga, there are many people (like me) who like to have the Volume progress along with the chapters, And it's really a bother sometimes when the chapters can get updated through Tachiyomi, but we have to update the volume progress by opening those websites/apps.
So, I think this feature is really gonna be useful for the trackings of MAL, Anilist, etc.

## What/Requirements
Just add the feature in the tracking so that it is possible to edit the volume number too. I'm not asking to make it automatic like the chapters progress, but there should be a feature through which volume progress can be edited through tachiyomi manually (just like how we can edit the start/end dates on MAL Tracking).
I know that mostly extensions do not have volume written with chapters. For this reason it would be great if their is an option through which volume of a series can be manually edited through tachiyomi tracking.

**Comment by scb261** [comment] 2020-10-16 13:25
Duplicate of #505

**Closed** 2020-10-16 13:29 UTC
Labels: feature
