### ISSUE TITLE
[Feature Request] Add subcategories

### ISSUE THREAD

**Issue by dkzerah** [inorichi/tachiyomi#3448] opened 2020-07-11 05:35 UTC
### Why/User Benefit/User Problem
Currently, for a better separation, I need to create several categories with the same context, I think it would be really useful to have sub-categories, as for example I create the category "Status" and in it I create the subcategories "Reading, Completed, Paused, Planning" in my opinion it would be really useful.

### What/Requirements
Simply by holding the touch over the category in the Library, a menu would appear with the child categories.

**Comment by arkon** [comment] 2020-07-11 12:01
Duplicate of #1803

**Closed by arkon** 2020-07-11 12:01 UTC
Labels: feature
