### ISSUE TITLE
how to download selective pages of a comic

### ISSUE THREAD

**Issue by suvendu1997** [inorichi/tachiyomi#3115] opened 2020-05-08 02:56 UTC
Sir,
I think selective pages download should be added to tachiyomi.
It is very required for tachiyomi users like me .
When a new chapter is added in websites like nhentai.net it shows all chapters as one, so for just one chapter I have to download all the whole chapters again which is not very efficient.
Hence addition of selective pages download can solve this problem.

Thank you

**Comment by arkon** [comment] 2020-05-08 03:02
Duplicate of #2323

**Closed by arkon** 2020-05-08 03:02 UTC
Labels: feature
