### ISSUE TITLE
[Feature Request ] Add filter "readed"

### ISSUE THREAD

**Issue by Jokerdrim** [inorichi/tachiyomi#1821] opened 2019-01-27 14:45 UTC
App version: r1462
This is about library. It would be great if there was also filter "readed" and also oportunity to hide readed manga in library.

**Comment by AmineI** [comment] 2019-01-27 20:12
Invert sorting by unread should do the trick ?
With that your *read mangas end up at the end of the list.

**Comment by hXtreme** [comment] 2019-02-17 09:24
https://github.com/inorichi/tachiyomi/issues/1814

Similar issue which would indirectly also solve this one. Please upvote/like/thumbs up it if you find it important/relevant.

**Comment by arkon** [comment] 2020-03-07 23:11
Marking as duplicate of #1814

**Closed by arkon** 2020-03-07 23:11 UTC
