### ISSUE TITLE
[Feature Request] add chapter count to searches and source migration results.

### ISSUE THREAD

**Issue by foxlore** [inorichi/tachiyomi#3075] opened 2020-05-05 12:24 UTC
### Why/User Benefit/User Problem
if the chapter counts are on the search results it will be easier to tell which sources are up-to-date. This will also help with source migration. As an addition to this request if the results could also be sorted my number of chapters it would bring the most up-to-date source to the top of the search.

### What/Requirements
When the search results are returned one of the query parameters could be the total chapter count. A badge overlaid on the artwork would display the chapter count.

**Comment by arkon** [comment] 2020-05-05 12:25
Duplicate of #2867

**Closed by arkon** 2020-05-05 12:25 UTC
Labels: feature
