### ISSUE TITLE
[Feature Request] Add a setting to change zoom amount when double-tapping

### ISSUE THREAD

**Issue by zukako18** [inorichi/tachiyomi#3926] opened 2020-10-11 04:09 UTC
## Device information
* Tachiyomi version: 1.10.5
* Android version: 10
* Device: Samsung Galaxy s10e

## Steps to reproduce
1. Go into any chapter
2. Tap twice in rapid succession to zoom onto the page

## Issue/Request
When you zoom onto a page it zooms in too much for my monkey brain. Some people may like this level of zoom, so it seems better to just add a setting that lets you control the zoom strength.

**Comment by arkon** [comment] 2020-10-11 13:30
Duplicate of #228

**Closed by arkon** 2020-10-11 13:30 UTC

**Comment by zukako18** [comment] 2020-10-11 14:38
Seems like a simple enough feature, why's it taking over a year to
implement?

**Comment by CarlosEsco** [comment] 2020-10-11 15:30
@zukako18 you are welcome to implement it and open a pull request. Also don't comment on closed issues
