### ISSUE TITLE
Library doesn't re-sort itself after reading.

### ISSUE THREAD

**Issue by LumpBloom7** [inorichi/tachiyomi#1106] opened 2017-12-03 03:17 UTC
### Problem
When the library is set to sort by unread count, the library doesn't re-sort itself after reading an unread chapter. The unread badge also does not update this.

Restarting it changing the library view is required to re-sort the list.

### Steps to reproduce
1. Set library to sort by unread count(could be any other, but more obvious with this)
2. Read an unread chapter completely so that it is marked as read in the chapter list.
3. Go back to the library view.
4. Observe the unread badge and/or position of manga in the list.

### System information
OS: ResurrectionRemix 5.8.5 (Android 7.1.2)  
Tachiyomi version: r1293 (Dev version)

**Comment by mrskizzex** [comment] 2017-12-03 04:11
I want to add that this might be because of new caching. Similar thing also happens when you change manga category, it will stay in the category it was before unless I restart the app. Same with removing manga from the library.

**Comment by Taumer** [comment] 2017-12-03 06:50
One of users was send me videos with reproduce this bug
https://youtu.be/r2lZ3hj3hB0
https://youtu.be/7auG1WPqsJk

**Comment by inorichi** [comment] 2017-12-03 12:04
It should be fixed now. It's not because of the caching, but the retained view (I think this issue didn't reach stable).

**Comment by LumpBloom7** [comment] 2017-12-03 12:46
It's fixed works as intended after the update now.

**Closed** 2017-12-03 12:49 UTC
