### ISSUE TITLE
Can't install any extention

### ISSUE THREAD

**Issue by jcyxxx** [inorichi/tachiyomi#2237] opened 2019-09-21 08:06 UTC
**App version: 0.8.4**

**Android version: 9.0**

**Issue/Request: I can't install any extention, always “There was a problem parsing the package".
No VPN, unkown source allowed.**

**Comment by joseph619** [comment] 2019-09-21 12:51
Delete the file and redownload it again to see if it works.

**Comment by jcyxxx** [comment] 2019-09-22 00:08
> Delete the file and redownload it again to see if it works.

No use... 
For now I can just manually download extention.apks and install it.

**Comment by WH1T3No1SE** [comment] 2019-09-25 14:33
I had same problem sometime ago, only reverting phone back to factory settings helped me.

**Comment by Digi1980s** [comment] 2019-10-07 18:15
Same here, I upgraded to Android 9 today then failed to install any extension from the app.

**Comment by Digi1980s** [comment] 2019-10-08 14:33
I have managed to figure out a workaround:

When it prompts "There was a problem parsing the package", instead of tapping "OK" here, swipe down notification bar, there is "Download complete" and by tapping it you proceed the normal installation.

**Comment by Seiyu12** [comment] 2019-10-15 01:52
https://github.com/inorichi/tachiyomi/issues/2237#issuecomment-539542882
Had the same problem, tried doing what you said but it only lead me to extension with nothing installed, does anyone had solution?

**Comment by Digi1980s** [comment] 2019-10-15 03:56
@Seiyu12 

With screenshots it should be much easier to follow:

This is the problem we run into here.
![image](https://user-images.githubusercontent.com/28332245/66798620-3570ac00-ef41-11e9-9ad7-62f48d59f527.png)

Swipe down the notification bar, we will see the extension has been downloaded. Just tap it.
![image](https://user-images.githubusercontent.com/28332245/66798671-63ee8700-ef41-11e9-9bbc-80ac9e931224.png)

Here we have the familiar normal installation interface.
![image](https://user-images.githubusercontent.com/28332245/66798772-a6b05f00-ef41-11e9-9b18-5c44c8143042.png)

And it just will finish as expected, at least in my case.
![image](https://user-images.githubusercontent.com/28332245/66798970-03137e80-ef42-11e9-9dec-40326e999a36.png)

Back to here, it doesn't matter just tap "OK", see if the extension installed (I hope so).
![image](https://user-images.githubusercontent.com/28332245/66799058-41a93900-ef42-11e9-8609-c7a937f882c0.png)

**Comment by Seiyu12** [comment] 2019-10-15 04:04
@Digi1980s
How did you use screenshot? 
Anyway i have the same situation until i tap the notification, the app came back to the extension list but it didn't install anything
The solution i got was to install the extension in tachiyomi.org

**Comment by Digi1980s** [comment] 2019-10-15 05:19
@Seiyu12 
Just paste images as the line beneath the text area says.
Perhaps what you have had is another new but worse problem. Downloading separately is indeed a workable method, but it is way too tedious when you have extensions to be updated occasionally. Let's hope someone could fix it soon.

**Comment by arkon** [comment] 2020-04-09 19:27
Duplicate of #2107

**Closed by arkon** 2020-04-09 19:27 UTC
