### ISSUE TITLE
[Feature Request] Save Settings & Required Extensions Details in Backup

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi#1810] opened 2019-01-19 14:16 UTC
Backup Saves only manga details but it could be best if it saved settings too so if someone is switching devices he/she doesn't need to do all the settings again

and i think adding extension data too will be good so before restoring we can show warning message like "**This extension are missing might face some problems while Restoring"** .

and it could be best if ask user to download all the required extension in one click.

adding required tracking data will be good too before restoring any backups too.

Like **Login to kitsu or Anilist before restoring** .

This will solve most of the mistakes people do while restoring and think its a bug.

**Comment by as280093** [comment] 2019-02-20 13:54
is this feature going to be in 1.x update?

**Comment by arkon** [comment] 2020-06-21 21:45
> Backup Saves only manga details but it could be best if it saved settings too so if someone is switching devices he/she doesn't need to do all the settings again

Duplicate of #1857

> and it could be best if ask user to download all the required extension in one click.

We show missing sources before restoring now, but we won't prompt it since we can't actually install extensions without user interaction without root.

> adding required tracking data will be good too before restoring any backups too.

There's a reminder to do so, which is good enough IMO.

**Closed by arkon** 2020-06-21 21:45 UTC
