### ISSUE TITLE
[Bug] Cannot install the extentions through app (dev or stable branch)

### ISSUE THREAD

**Issue by IS0ULI** [inorichi/tachiyomi#2851] opened 2020-04-09 19:19 UTC
Hi, i m facing a problem with both stable and dev branch of app where i cannot download the extensions through app. I downladed them frm the site and after sucsessfully installing and making them work i cannot update them through app itself nor can i download new ones.

This is the only issue in both of the branches of the app i have faced in past 15 days i have been using it i have updated the dev branch twice and using it since. Please help!!

**Comment by arkon** [comment] 2020-04-09 19:27
Duplicate of #2107

**Closed by arkon** 2020-04-09 19:27 UTC
Labels: bug
