### ISSUE TITLE
Error when trying to open any chapter from any source

### ISSUE THREAD

**Issue by guicale** [inorichi/tachiyomi#859] opened 2017-06-20 23:09 UTC
Whenever I try to open a chapter from any series, independently from the source, I get the error `chapter_disk_cache/journal.tmp (No such file or directory)`. When this happens, it is also impossible to enter the advanced settings, as the app crashes whenever I try.
However, this didn't use to happen. The app functioned normally until a few days ago, but this suddenly started. I have even factory reset my phone and the error persists! The only way to use the app was to install the latest nightly, which seems to work perfect. 

Version: v0.5.2
Device: Moto G4
OS: Android 7.0

![screenshot_20170620-235104](https://user-images.githubusercontent.com/7140690/27359811-b4197040-5615-11e7-8a6f-12d3295bd113.png)

**Comment by inorichi** [comment] 2017-07-04 14:17
Try clearing the cache through Android's app settings. I've seen those crashes before and I think it has to do with removable storage (SD card), but I can't reproduce it.

**Comment by inorichi** [comment] 2017-08-09 07:17
This issue should be fixed in master, however the build server is down and will take a while to update the apk.

**Closed** 2017-11-29 18:54 UTC
