### ISSUE TITLE
[Feature request] Download chapters in advance

### ISSUE THREAD

**Issue by Heavyarms04** [inorichi/tachiyomi#2379] opened 2019-12-21 13:05 UTC
1. App version 0.8.4
 2. Android version 7
 3.Compress manga in zip format

It would be very good that when reading a chapter the application will download 1 or 2 subsequent chapters would give an even more fluid reading experience

**Comment by clem193** [comment] 2019-12-22 20:15
There is a workarround this (that I do use) :
When you are about to read a new serie you click on the dots up right and "download all chapters"
Then in app options you enable "delete read chapter" or "delete 2nd to read chapter" (<= that's what I use in case I wanna go back for some reason)
If your manga is still ongoing you can also unable "download new chapters" so when you update your library it will download new chapters. (if your library is huge you can spilt it and ask the app to only update certain category in global update so you don't get things you don't read yet, updated/downloaded).

In the end it's a very neat trick so you can keep reading in peace with bad internet / offline and it also do what you seek. It just require some space (between only fiew Mb to fiew Gb depending how many things you read at once).

Hope it help !

**Comment by arkon** [comment] 2019-12-22 20:27
Marking this as a duplicate of #2367

**Closed by arkon** 2019-12-22 20:27 UTC
