### ISSUE TITLE
[Feature Request] Add a free text zone under Discription & Tags

### ISSUE THREAD

**Issue by clem193** [inorichi/tachiyomi#2662] opened 2020-03-04 23:18 UTC
Everything is in the title :
Sometimes I find myself wanting to add some comments under fiew mangas for whatever reasons, and there is no way to write anything anywhere.

What about adding underneath the manga Discription & Tags a little zone where we can type whatever we want (and what you type stay there as long we don't remove it, obviously).

For exemple personaly I often wait works to be finished before I read them, but some sources dont have reliable "status" showing, so I need to remember the number of the last chapter to know when/if it's done, but I can't type it anywhere and always need to check back and forth with mangaupdates. Sometimes I also wanna quickly put a comment and rating once I'm done reading, without having to go use another app/website to do so.

**Comment by wopian** [comment] 2020-03-05 00:13
Could also be done through the tracking section - MyAnimeList, Kitsu (and I think) AniList all support notes.

**Comment by clem193** [comment] 2020-03-05 00:44
"without having to rely use another app/website to do so".

**Comment by hXtreme** [comment] 2020-03-05 05:55
dup of #2155 / #2203 ?

**Comment by hXtreme** [comment] 2020-03-05 05:58
I personally really like this feature and have asked for it previously but, this feature would need the underlying database structure to be updated, something that isn't very likely to happen anytime soon though.

**Comment by arkon** [comment] 2020-03-07 22:50
Duplicate of #2155

**Closed by arkon** 2020-03-07 22:50 UTC
Labels: feature
