### ISSUE TITLE
[Bug] Full-screen doesn't work properly in the recently new version 

### ISSUE THREAD

**Issue by hambazumba** [inorichi/tachiyomi#3619] opened 2020-08-06 13:02 UTC
### Device information
* Tachiyomi version: 10.3
* Android version: 6.0
* Device: HTC One M8

## Steps to reproduce
1. Open a manga page
2. Tap the screen 

### Expected behavior
Should be able to see all the stuff

### Actual behavior
Notification bar on the top and the home button bar on the bottom crop out the manga title on top and the chapter number and scroll wheel on the bottom

### Other details
Maybe the new code u use to stop the notification and home buttons bar popping up in the app's full screen mode doesn't work in Android 6

**Comment by arkon** [comment] 2020-08-06 13:06
Duplicate of #3586, fixed for next release.

**Closed by arkon** 2020-08-06 13:06 UTC
Labels: bug
