### ISSUE TITLE
[Bug] Scrolls up really fast when zooming with two fingers

### ISSUE THREAD

**Issue by Tetreos** [inorichi/tachiyomi#3962] opened 2020-10-22 23:24 UTC
## Device information
* Tachiyomi version: 0.10.5
* Android version: 9
* Device: Samsung Galaxy S8
* Reading mode: Webtoon
* While reading normal Manga

## Steps to reproduce
1. While reading normal Manga try to zoom with both of your fingers.
2. After zooming in or out you release both of your fingers at the same time (dont stop the movement of your fingers after zooming in).

### Expected behavior
The reader zooms into the picture to the place where you zoomed in with your fingers.

### Actual behavior
After zooming in the reader scrolls really fast in one direction, multiple pages up or down.

## Other details
It seems like the reader somehow stored a big value of velocity while zooming and after you release your fingers the reader seems to notice a little flicking from your fingers which translates the velocity into up or down movement.

**Comment by arkon** [comment] 2020-10-22 23:32
Duplicate of #2602

**Closed** 2020-10-22 23:32 UTC
Labels: bug
