### ISSUE TITLE
Batoto from Emerald is bugging

### ISSUE THREAD

**Issue by avitari14** [inorichi/tachiyomi#3937] opened 2020-10-12 19:30 UTC
![Screenshot_20201013-022609](https://user-images.githubusercontent.com/66585071/95783196-86a1b000-0cfb-11eb-92b7-9037281a5e9b.png)

So for the past few days Batoto seems to unable loading their manga source in the app, I've updated my app and extension, and I've tried open it in web view and log in then go back but it's still futile
Even though the manga that I marked is still existing, but I can't read it in app so I have to open the web view everytime I want to read from the source

Can you help me fix this bug?

**Comment by scb261** [comment] 2020-10-12 19:32
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/4524

**Comment by arkon** [comment] 2020-10-12 19:32
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/4524

**Closed** 2020-10-12 19:32 UTC
