### ISSUE TITLE
Letter Filter Local Manga

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#680] opened 2017-02-08 17:46 UTC
Just like #665 . Looks like letter `T` is filtered so it's not showing in the chapter list. File name is `Twin Spica 01` but showing only `01` in chapter list.

Version : r1100

**Comment by paronos** [comment] 2017-02-08 18:37
The manga name (i.e. the parent folder name) is removed from the chapter names.
So, if the file `Twin Spica 01` is in a directory named `Twin Spica`, this is the intended behaviour.

**Comment by inorichi** [comment] 2017-02-12 18:09
Closing since it's working as expected.

**Closed by inorichi** 2017-02-12 18:09 UTC
