### ISSUE TITLE
[Feature Request] Able to remove multiple items in download queue

### ISSUE THREAD

**Issue by imKenjo18** [inorichi/tachiyomi#3638] opened 2020-08-10 06:45 UTC
---

### Why/User Benefit/User Problem
In case you want to remove multiple chapters that are downloading to make it convenient. The options right now are either doing it one by one or cancelling all.

### What/Requirements
Just a simple tap and hold to a chapter in order to multi select it and choose whether to cancel or "move to top" those items(chapters).

**Comment by arkon** [comment] 2020-08-10 13:49
Duplicate of #2860

**Closed by arkon** 2020-08-10 13:49 UTC
Labels: feature
