### ISSUE TITLE
Kissmanga http Error

### ISSUE THREAD

**Issue by Blackbolt007** [inorichi/tachiyomi#1939] opened 2019-03-27 11:21 UTC
it's been a week and kissmanga is still showing http error,
Kindly Fix it

**Comment by CarlosEsco** [comment] 2019-03-27 11:23
kindly read the template that you deleted before opening the issue.  if you had you would see it says all extension/catalog issues go in the extensions-repo.  then when you got there you would see that there is an open issue for kissmanga already.  then you would see that at the bottom the issue is fixed in the lastest dev, with a pending 0.8.2 coming at some point this week.

**Closed by CarlosEsco** 2019-03-27 11:23 UTC
