### ISSUE TITLE
Add Side by Side Viewer

### ISSUE THREAD

**Issue by Flipflopapocalypse** [inorichi/tachiyomi#760] opened 2017-04-18 20:55 UTC
Requesting a feature that displays two pages simultaneously side by side as if to mimick how pages are displayed in a book; turning the page would advance Tachiyomi to the next two pages. I have attached an example of this feature present in Perfect Viewer.
![tmp_4525-screenshot_2017-04-18-10-34-16604790781](https://cloud.githubusercontent.com/assets/27741619/25151795/a1e06d90-2422-11e7-9e21-19a3f870ffe2.png)

Such a feature would also require a Shift button, which would advance the reader by a single page; this would allow for the user to correct which pages should be on the right and which should be on the left.

Tachiyomi would also need to detect the aspect ratio of each image to disable this feature when displaying individual images that already include the right and left pages. Otherwise a quick toggle on the popup toolbar would give users the ability to quickly deal with it themselves.

**Comment by inorichi** [comment] 2017-04-30 22:11
Duplicate of #149

**Closed by inorichi** 2017-04-30 22:11 UTC
