### ISSUE TITLE
Configurable zoom on double-tap

### ISSUE THREAD

**Issue by jotumn** [inorichi/tachiyomi#476] opened 2016-09-22 10:24 UTC
Right now, the app zooms the page to a fixed size on double-tap. This probably works fine on tablets but on smartphones the zoom is too large so it's not very useful. I'd like it if you could configure the zoom percentage in the settings.

**Comment by TheMostCuriousThing** [comment] 2017-12-19 19:23
I agree, but I think the easiest solution is simpler than a configurable percentage: a toggle between two different `Scale type`s (say, `Primary scale type` and `Secondary scale type`).

An example use case for smartphones in portrait would be:
- `Primary scale type`: `Fit screen`
- `Secondary scale type`: `Fit height`

...which would allow for simple, "zoom-free" reading on smartphones with a 16:9 or greater aspect ratio.

**Comment by edenpc** [comment] 2018-10-08 00:27
I second this.

**Comment by Matth7878** [comment] 2019-06-14 09:20
Same here.
I think issue #228 is identical to this one.

**Comment by Battler624** [comment] 2019-10-08 21:40
I also wish this is implemented.

**Comment by arkon** [comment] 2020-06-23 02:48
Duplicate of #228

**Closed by arkon** 2020-06-23 02:48 UTC
Labels: feature
