### ISSUE TITLE
[Bug] The app force you to read or mark all the earlier chapters as read if you want the continue reading button to work.

### ISSUE THREAD

**Issue by ach-raf** [inorichi/tachiyomi#2410] opened 2019-12-30 19:03 UTC
I tried to start reading a manga from chapter 337, after reading few pages I clicked back and the app took me to chapters list as intended and it showed my progress in that chapter.
after coming back to the app and clicking continue to read button it took me to the first chapter.

### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Select any new manga that you haven't read.
2. Try to read any chapter except the 1st one.
3. Go back to chapters menu.
4. Click the continue reading button (the blue circle with a white play).

### Expected behavior
The app should take you to the chapter you started reading.

### Actual behavior
The app always takes you to the first chapter if it's unread.

**Comment by eshrh** [comment] 2019-12-31 17:26
You could just "mark previous as read" in the 3 dot menu of your latest chapter.

**Comment by hXtreme** [comment] 2019-12-31 22:48
I can imagine that, if you're reading a compilation of oneshots or if you want to skip the oneshot for a certain manga and read it later then you may not want to mark it as read.

**Comment by arkon** [comment] 2020-01-04 20:41
Duplicate of #1399

**Closed by arkon** 2020-01-04 20:41 UTC
Labels: bug
