### ISSUE TITLE
[Bug] <emerald>: Can't acess the bato.to extension even the new emerald extension containing the new bato.to source which doesn't show on my sources page

### ISSUE THREAD

**Issue by Janejade** [inorichi/tachiyomi#3948] opened 2020-10-17 15:04 UTC
## Device information
- Tachiyomi version: Stable 0.10.5
- Android version: 7.0

## Source information
- Name: batoto (Emerald)
- Extension version: 1.2.2

## Steps to reproduce
1. Open chapters from any saved manga/manhwa from bato.to source

### Expected behavior
Open chapter images in viewer

### Actual behavior
value document.domain of type java.lang.String cannot be converted to JSONObject

## Other details
I also checked the old bato.to extension and it only showed a black page thus I tried to go to the webview thinking that the site may be down, but the original site was still working perfectly fine. The next thing I did, I tried the troubleshoot instructions I found on reddit, still the problem was not solved. I installed the new extension containing the new bato.to source which is the emerald extension but when I checked my sources page it didn't reflect the new bato.to source. I looked at the settings of the emerald extension and toggled on the english bato.to source but still it didn't reflect on my source page. 
![20201017_222650](https://user-images.githubusercontent.com/73028295/96344812-e073f280-10cc-11eb-9295-da4b98381fd4.jpg)
![Screenshot_20201017-224117](https://user-images.githubusercontent.com/73028295/96344999-ed90e180-10cc-11eb-8fdf-4ab7a98c56be.jpg)
![Screenshot_20201017-224016](https://user-images.githubusercontent.com/73028295/96345138-f7b2e000-10cc-11eb-9e3f-b7577ade9b02.jpg)
![Screenshot_20201017-224344](https://user-images.githubusercontent.com/73028295/96345339-07cabf80-10cd-11eb-8b2a-056b80f92ef1.jpg)
![Screenshot_20201017-224533](https://user-images.githubusercontent.com/73028295/96345477-12855480-10cd-11eb-9037-8c255c2e8d85.jpg)
![Screenshot_20201017-224234](https://user-images.githubusercontent.com/73028295/96345496-1ca75300-10cd-11eb-895f-01cd3da2f965.jpg)

**Comment by CrepeTF** [comment] 2020-10-17 15:08
We know.

Duplicate of:
https://github.com/inorichi/tachiyomi-extensions/issues/4524

And also this ain't even the right place to post issue, you issued in "inorichi/tachiyomi" instead of "inorichi/tachiyomi-extensions"

**Comment by Janejade** [comment] 2020-10-17 15:12
Sorry I was new to this. I just clicked new issue and was not able to check if there were tags to be used for specific issues. I apologize, it was an honest mistake.

**Closed** 2020-10-17 16:07 UTC
Labels: catalog, invalid
