### ISSUE TITLE
[Feature Request] Mass "mark as read" feature

### ISSUE THREAD

**Issue by PixelDemise** [inorichi/tachiyomi#2628] opened 2020-02-26 06:30 UTC
For others like myself who are migrating over from mangarock, having a ton of manga to sift through and manually mass mark-as-read each story individually is extremely tedious. especially for me, who has over 750 manga I am keeping on my list. It takes like 7 seconds to mark one story as read, times 750, not counting the ones above that number, is more than an hour and a half of constant nonstop sifting through the app doing the same mundane task.

### What/Requirements
Move the mark-as-read ability to the overall library, rather than having it done in each story. That would allow you to highlight all manga and mark as unread/read for people migrating from another app, or for people who changed sources due to one going down and need to remove large numbers of manga.

**Comment by arkon** [comment] 2020-02-26 13:20
Duplicate of #1181

**Closed by arkon** 2020-02-26 13:20 UTC
Labels: feature

**Comment by PixelDemise** [comment] 2020-02-26 17:45
So you close the thread after not answering not one, but two threads worth of the question.

This kind of thing is why I avoided Tachiyomi for so long.

**Comment by CarlosEsco** [comment] 2020-02-26 17:50
It's a duplicate any questions or concerns belong in that thread

**Comment by happywillow0** [comment] 2020-02-26 18:08
Or to put it in other words:

Thank you for your feature suggestion and feedback about the app. 
There is currently an existing request that was previously posted about marking everything as read. It is still pending (not complete) so feel free to join in and add to the existing conversation.
