### ISSUE TITLE
[Bug] Tachiyomi struggle with big webtoons on older hardware

### ISSUE THREAD

**Issue by Lightjohn** [inorichi/tachiyomi#4134] opened 2020-12-14 17:40 UTC
## Device information
* Tachiyomi version: 0.10.7 
* Android version: 10
* Device: Samsung tab pro 8.4

## Steps to reproduce

I recently encountered multiple webtoons that were splitted in many big images ~6000x20000 and on my old tablet (2gB ram) it's enough to kill tachiyomi reader. The reader can show the first part of the first image but I imagine that when it tries to load next images it starts to hang/crash.

So to fix it I created an Android app that is going through all Tachiyomi images and will split these images if image height is > screen height.

So in my case, going from one image 6000x20000 (000.jpg) to 12 images 6000x1800 (000-001.pg 000-002.jpg) and after that no more issue, reader is quite snappy and memory usge is quite low.

But it work well because I'm in  webtoon reader mode.

Do you think it makes sense for tachiyomi to have something like that?

**Comment by arkon** [comment] 2020-12-14 17:42
Duplicate of #1908

**Comment by arkon** [comment] 2020-12-14 17:43
Automatic slicing could be a solution. Feel free to add more details to that older issue.

**Closed by arkon** 2020-12-14 17:43 UTC
Labels: bug
