### ISSUE TITLE
[Feature Request] Quick Download

### ISSUE THREAD

**Issue by Mano5JP** [inorichi/tachiyomi#3122] opened 2020-05-08 19:29 UTC
**Download option when long press on manga on library tab**.

Right now we can change cover, source, or delete manga

It would be beneficial to have quick download option with limit to 5 manga selection or all selected manga from library tab, rather than opening a manga at a time then download and so on.

**Comment by arkon** [comment] 2020-05-08 19:32
Duplicate of #156

**Closed by arkon** 2020-05-08 19:32 UTC
Labels: feature
