### ISSUE TITLE
[Feature Request] Turn a double page into two single pages

### ISSUE THREAD

**Issue by 7sevenseven** [inorichi/tachiyomi#2034] opened 2019-05-14 09:14 UTC
The perfect viewer has a similar function (automatic single page).
Some e-books are not composed of one page, but are composed of many double pages. This makes manual zooming every time you watch, which is cumbersome. There is now a function to adapt to height, but this feature is not very useful. Fit height does not divide the original interface into two parts, resulting in uneven crops.
This feature is generally not  go wrong, 90% of the two pages are divided into single pages. If someone doesn't like it, he can change back to the default mode.

**Comment by CarlosEsco** [comment] 2019-05-14 09:30
Duplicate of open issue. Search the repository to see it

**Closed by CarlosEsco** 2019-05-14 09:30 UTC
