### ISSUE TITLE
Restoration : doesn't add anything in database if the number of manga is too big

### ISSUE THREAD

**Issue by briaeros** [inorichi/tachiyomi#1572] opened 2018-08-07 22:42 UTC
Hi,

I use tachiyomi r1427 (from fdroid)
I've tried to restore a save from another device. The save have 360 manga.
When I try to import it, it do all the works, and at the end of the import: 
- gives no error
- and nothing is imported.

Even if I stop the import after the first imports , no manga are added.

If I split the "mangas" array in the json with a smaller size (I've test up to 30 successfully, doesn't try above), then the import works fine (most of the time. I've got some trouble on specific chapter I haven't sorted yet).

If you want to split a big save, I used the following command
for i in `seq 0 30 360` ; do  jq ".mangas=(.mangas[$i:$((i+30))])" test.json > test_${i}.json ; done

**Comment by arkon** [comment] 2020-04-26 22:43
Duplicate of #2482

**Closed by arkon** 2020-04-26 22:43 UTC
