### ISSUE TITLE
[Feature Request] Mini pictures of manga pages

### ISSUE THREAD

**Issue by FilipBlinder** [inorichi/tachiyomi#3184] opened 2020-05-15 14:46 UTC
### Why/User Benefit/User Problem
Uncomfortable navigating to the page you need in a multi-page manga. This feature will help you immediately find the page you want. 

### What/Requirements
The screenshots show the mechanism of this function. When you click on the window, a menu of small images appears. This function is taken from the OpenManga application.
![_20200515_215850](https://user-images.githubusercontent.com/65407865/82064883-8d4ddc00-96f7-11ea-840e-055de26c5015.JPG)
![IMG_20200515_215943_087](https://user-images.githubusercontent.com/65407865/82064928-99d23480-96f7-11ea-8da2-80809fc87a34.jpg)

**Comment by arkon** [comment] 2020-05-16 14:29
Marking as duplicate of #1632

**Closed by arkon** 2020-05-16 14:29 UTC
Labels: feature
