### ISSUE TITLE
[Feature Request] <Ability to filter more than just one category>

### ISSUE THREAD

**Issue by AkoSiJam** [inorichi/tachiyomi#3449] opened 2020-07-11 06:32 UTC
---

### Why/User Benefit/User Problem
It will make finding certain types of manga easier. 

### What/Requirements
It will filter manga with the tags you selected(ex. You chose shounen and action, it will show you the mangas with those tags.

**Comment by arkon** [comment] 2020-07-11 12:03
Not sure what you mean, library search already does all categories.

**Comment by AkoSiJam** [comment] 2020-07-11 13:46
I mean the filter button when browsing. It only allows you to filter 1 category.

**Comment by arkon** [comment] 2020-07-11 13:47
Duplicate of #2698

**Closed by arkon** 2020-07-11 13:47 UTC
Labels: feature

**Comment by CarlosEsco** [comment] 2020-07-11 14:55
I assumed this was when browsing a source. But there highly dependant on a source allowing it this will stay closed.
