### ISSUE TITLE
[Bug] Conflict when downloading different chapters with same name

### ISSUE THREAD

**Issue by mattiadr** [inorichi/tachiyomi#3548] opened 2020-08-01 14:04 UTC
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: Samsung Galaxy S8

### Bug description
If there are multiple chapters with the same name (different groups in my case) and you try to download both there is a conflict.
The first chapter is downloaded normally, the second is downloaded, but it is stored in a folder with the same name and "_tmp" appended to it.
Trying to open any of the two chapters always shows the first one downloaded (the one without "_tmp" in the folder name).

### Expected behavior
Different chapters should be stored in different folders even if they have the same name, maybe including a chapter ID in the filename.

### Screenshots
![image](https://user-images.githubusercontent.com/8914498/89103254-af125180-d410-11ea-9421-1bd85402da2f.png)
![image](https://user-images.githubusercontent.com/8914498/89103256-b20d4200-d410-11ea-9afe-dc5cf4286629.png)

**Comment by arkon** [comment] 2020-08-01 14:09
Duplicate of #1893

**Closed by arkon** 2020-08-01 14:09 UTC
Labels: bug
