### ISSUE TITLE
JSON error while trying to select batoto as source from catalogues   

### ISSUE THREAD

**Issue by Nishant21Hada** [inorichi/tachiyomi#955] opened 2017-08-25 17:26 UTC
I was using an older version of tachiyomi(forgot which one it was).Today I upgraded to the newest dev version and batoto source can't be selected from sources menu.Error: "Attempted to invoke virtual method java.lang.string.org.jsoup.Node...."
Then I tried to switch back to older versions but they were not in F-droid repository.There are only 3 dev builds versions shown and all of them are having same error.Is there anyway to re-download the older versions?

Version:0.6.1-1200
(other relevant info like OS)

**Comment by wopian** [comment] 2017-08-25 17:47
Duplicate of #953

**Closed** 2017-08-25 21:10 UTC
