### ISSUE TITLE
MangaFox not working.

### ISSUE THREAD

**Issue by traferi** [inorichi/tachiyomi#1224] opened 2018-02-01 04:02 UTC
In the last 2 days the mangafox is not working in the tachiyomi. I can't see the catalogue and none of my mangas are updating. It's only me or is a common problem? 

The for the help and sorry for my english.

**Comment by cd0rw0** [comment] 2018-02-01 04:38
manga fox website is down for all
next time if you have site loading problem, follow faq, at least Try opening the manga in browser

Please close this issue.

**Comment by cylonu87** [comment] 2018-02-01 04:57
the new address is http://fanfox.net/ (redirected from mangafox.la) but on reddit, some people say they are redirected to mangazone app.

**Comment by CarlosEsco** [comment] 2018-02-01 23:22
I'm having no issues with this

**Comment by cd0rw0** [comment] 2018-02-02 00:33
in browser mangafox / faxfox being redirected to mangazoneapp.com

**Comment by CarlosEsco** [comment] 2018-02-02 00:35
Even if it does it's not breaking tachiyomi.

**Comment by cd0rw0** [comment] 2018-02-02 00:37
mine not working for last fewdays,
i already start moving my manga from mangafox

**Comment by CarlosEsco** [comment] 2018-02-02 00:41
Wonder if location based issur

**Comment by cd0rw0** [comment] 2018-02-02 00:48
yap, its location based issue.
just tried load with us proxy now website working.

**Comment by SDMU** [comment] 2018-02-03 03:58
Mangafox might slowly be forcing all mobile users to download and use the mangazone app.

**Comment by SDMU** [comment] 2018-02-03 03:59
I wonder whether the site can be accessed if we are on the desktop (not desktop mode)

**Comment by cd0rw0** [comment] 2018-02-03 06:13
@SDMU 

as i said before mangafox.me /fanfox.net only accessible if you use US proxy even in desktop.

**Comment by Szachie** [comment] 2018-02-06 14:36
aww man, pretty much 99% of my library are from mangafox 

this address "[https://manga-fox.com](url)" still works though.. and it's still updated.

Is it's possible for devs to switch to this one? its like a lite version or like an old version of MangaFox, I'm not really sure since I just found this today. I do believe/hope that it's less difficult than working with a location based issue.

**Comment by nyahsu** [comment] 2018-02-08 14:29
this is occurring to me as well, i can't read anything from mangafox in tachiyomi at the moment.

but someone suggested to use http://teleportyou.com/

then in the website you'll enter fanfox.net

it directs you to the real thing
http://fanfox.net.prx.us.teleportyou.com/ 

i hope this helps!
good luck!

**Comment by melnation-com** [comment] 2018-02-18 20:28
I can confirm http://fanfox.net/ is bluntly garbage mangazone ad on browser, as of 2018/02/18 mangafox has no list in tachi

https://manga-fox.com/ seems working but I don't know if same owner or different competitor just fishing fans

**Comment by Szachie** [comment] 2018-02-19 20:31
Welp, I just started slowly migrating my libraries to other sources for now.

It's a bit of a hassle since MangaFox was my main source but I suppose it's still way faster to migrate than to wait for it to come back as a working source. 

It does seem like it'll be somewhat difficult to do so, but if it does get fixed, I can always switch back...

**Comment by LakotaGray** [comment] 2018-04-04 18:28
Is this a better fit in tachiyomi-extensions?

**Comment by wopian** [comment] 2018-04-04 19:25
This was the internal catalogue @lakotagray

**Comment by inorichi** [comment] 2018-04-07 18:48
It's working atm anyways.

**Closed by inorichi** 2018-04-07 18:48 UTC
