### ISSUE TITLE
Chapters aren't shown as "Downloaded" 

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi#674] opened 2017-02-04 12:06 UTC
v0.4.2

This is what I'm talking about
https://aww.moe/95rpu5.webm
As seen here trying to download all the unread chapters (and tried downloading a chapter manually) doesn't do anything but the chapter itself is already downloaded (no 'downloading' at all) and you can't manually delete a chapter by the **...** menu (http://i.imgur.com/L8v7EPM.jpg) but if you press-hold a chapter and delete it you can download it and it will show downloading/downloaded.

I have set up for the app to download new chapters automatically.

**Comment by inorichi** [comment] 2017-02-04 12:52
Working fine for me. How are the folders named?

**Comment by NoodleMage** [comment] 2017-02-04 17:00
Do you use multiple simultaneous downloads? And if so could you test with latest commit?

**Comment by inorichi** [comment] 2017-02-04 17:16
I think this is due to the folder names, the notification issue shouldn't have anything to do with this, the video was probably made after everything was downloaded so...

**Comment by NoodleMage** [comment] 2017-02-04 17:18
Woops. I thought it just didn't show the notification. You can ignore my comment then ;).

**Comment by pitman10** [comment] 2017-02-04 22:14
Here are the folders 
https://imgur.com/a/8XcWk

The one named Keijo________ is empty.

**Comment by inorichi** [comment] 2017-02-12 18:13
The one with underscores must be from the old downloader, you can delete it.

The names look fine. I have no idea. Does redownloading help?

**Comment by pitman10** [comment] 2017-02-13 14:25
> Does redownloading help?

Yes
> "...if you press-hold a chapter and delete it you can download it and it will show downloading/downloaded."

**Comment by inorichi** [comment] 2017-02-13 18:44
Were the screenshots from https://imgur.com/a/8XcWk made after or before redownloading?

Did you replicate the issue somewhere else or only that one time?

**Comment by pitman10** [comment] 2017-02-20 05:53
As far as I noticed it was a one time thing

**Comment by inorichi** [comment] 2017-02-23 13:07
Most likely the chapter name changed in another update and the directory name didn't match, though for some reason it was still able to open the folder (maybe the `!` are involved). I'm closing since I couldn't reproduce and it only happened once.

**Closed by inorichi** 2017-02-23 13:07 UTC
