### ISSUE TITLE
Problems with sorting

### ISSUE THREAD

**Issue by VillyShmilly** [inorichi/tachiyomi#894] opened 2017-07-12 10:14 UTC
Basically, some chapters are out of order in a few cases.

For example, one of my mangas is set up like this (there's a "Stone Ocean" folder in the local directory and the volumes are subfolders, if that matters):
Volume 01 - Prisoner FE40536, Jolyne Cujoh
Volume 02 - Visitor to Green Dolphin Street Prison
...
Volume 17 - Made In Heaven

Obviously, I'd like it to be sorted by the volume number. However, in this case it doesn't work that way. 
(i really hope i didnt go overboard with the picture size)
![screenshot_20170712-115735](https://user-images.githubusercontent.com/30112590/28112799-a8248bee-66fa-11e7-961b-8aca9646b594.png)
Changing the display mode to show chapter numbers makes this show up:
![screenshot_20170712-115819](https://user-images.githubusercontent.com/30112590/28112872-d84573c4-66fa-11e7-93d8-7c1665767bb5.png)

So, it seems that Tachiyomi took the 40536 from "Prisoner FE40536", which screwed up sorting. I imagine this is intended behavior, but is there any way to make it ignore everything after "Volume <xy>-" in this case?

I'm using 0.6.1. I tried reverting to 0.5.2 to see if anything would change, but the issue still persists. The device is a Huawei P9 with Android 7.0 (Nougat). I don't have any sorting filters on.

**Comment by j2ghz** [comment] 2017-07-12 11:53
Can you try Sorting Mode > By Source?

***
If not it could be hard to solve because:
The number after volume is ignored, because usually the naming is:
- volume 1 chapter 1
- volume 1 chapter 2
- volume 2 chapter 3

The parser looks at each chapter individually, and sees "volume 1 \<something\> 40536", which usually means chapter 40536

**Comment by j2ghz** [comment] 2017-07-12 11:55
Do both sorting modes do the same? As a workaround you can try renaming to `01 - Prisoner FE40536, Jolyne Cujoh` or `Chapter 01 - Prisoner FE40536, Jolyne Cujoh`

**Comment by VillyShmilly** [comment] 2017-07-12 13:21
Yes, both sorting modes do the same.

Cutting out the "Volume" part fixed the sorting, thankfully. I'd rather keep it for consistency's sake, but hey, the workaround works.

**Comment by NoodleMage** [comment] 2017-07-12 13:23
It's probably the FE not being removed. So it sees 040536 and 1 and can't determine which is the correct chapter (as multiple number) so it take -1.

**Comment by 444nonymous** [comment] 2017-07-26 18:46
I had that -1 problem with some mangas. IE "One Outs" from Kissmanga. Chapters from 1 to 130 are listed as -1.

**Comment by j2ghz** [comment] 2017-07-26 22:45
@444nonymous You need to "Change display mode"

**Comment by 444nonymous** [comment] 2017-07-27 03:36
@j2ghz  No. It's a bug. There is no setting to fix it. Showing chapter numbers shows -1.

**Comment by j2ghz** [comment] 2017-07-27 10:42
~I mean that you should use "Show title" and sort "by Source", because it's usually better.~
I see, we are talking about local manga.

**Comment by 444nonymous** [comment] 2017-07-29 08:23
I'm not even sure if it's the same problem, so I opened a new issue. https://github.com/inorichi/tachiyomi/issues/914

**Comment by NoodleMage** [comment] 2017-07-31 18:02
Closing because intended behavior.  Chapters aren't recognized by volume

**Closed by NoodleMage** 2017-07-31 18:02 UTC
