### ISSUE TITLE
Kissmanga extension doesn't update

### ISSUE THREAD

**Issue by derencel20** [inorichi/tachiyomi#2808] opened 2020-04-01 09:57 UTC
All the manga under Kissmanga in my favorites don't update. Even though there are so many updates when I view the site.

**Comment by CarlosEsco** [comment] 2020-04-01 10:42
wrong repository.
dupe of https://github.com/inorichi/tachiyomi-extensions/issues/2496

**Closed by CarlosEsco** 2020-04-01 10:42 UTC
Labels: bug
