### ISSUE TITLE
Recommendation, recognize external links

### ISSUE THREAD

**Issue by MakuSensei** [inorichi/tachiyomi#1856] opened 2019-02-24 16:48 UTC
**App version:**
r1463
**Issue/Request:**

I would like the application to recognize external links when sharing from the browser.
for example I share a link of a manga of X source that is supported in tachiyomi (example eHentai)
then the other person who shared the link and also uses tachiyomi can open the link directly in the application instead of going around a lot to find the manga / doujins and visualize it in the application

**Comment by CarlosEsco** [comment] 2019-02-24 16:53
Duplicate of a closed issued. Not possible with current architect of extensions. Will possibly be added to 1.x

**Closed by CarlosEsco** 2019-02-24 16:53 UTC
