### ISSUE TITLE
[Feature Request] Easy management of download queue

### ISSUE THREAD

**Issue by Mymiano** [inorichi/tachiyomi#3264] opened 2020-06-01 12:14 UTC
### Why/User Benefit/User Problem
Managing downloads is such a pain when you have 500+ chapters to download.

### What/Requirements
1. The user must easily find what his looking for in the bunch of download. So a scroll is a must like in a library.
2. Cancelling is done one by one, but what if the user wants to cancel chapters of one manga while another manga will be downloaded or the user only wants to cancel up to 20 chapters. Add a multi select of chapters to be cancel. If possible add also the reorder of the selected chapters (move to top/bottom).

**Comment by arkon** [comment] 2020-06-01 12:56
1. Added in 0b8b13d0bb7f7bc8f0939f1ae1b91cd53fc2bd19
2. Duplicate of #2860

**Closed by arkon** 2020-06-01 12:56 UTC
Labels: feature
