### ISSUE TITLE
Could you please add a setting so that manually marking a chapter as "read" updates our MAL? 

### ISSUE THREAD

**Issue by thejellydude** [inorichi/tachiyomi#510] opened 2016-10-31 02:38 UTC
Sometimes I'll read a chapter of something online before it shows up on tachiyomi. (Directly through the scanlator, for example) If I want tachiyomi to update my MAL, I need to open the chapter and skip to the end, or mark it as read the  manually update the chapter. Would it be possible to make it so that if we mark a chapter as read, it syncs to MAL?

**Comment by inorichi** [comment] 2016-10-31 07:08
Duplicate of #389

**Closed by inorichi** 2016-10-31 07:08 UTC
