### ISSUE TITLE
[Feature Request] "All" category

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3350] opened 2020-06-19 22:30 UTC
### What/Requirements
- Not the same as "Default" category
- Hidden if there's only one category
- Probably hidden by default, dunno
- Can be toggled on/off either at **Filters menu › View** or maybe **Settings › Library**
- Option to reposition it to first or last
- obvious stuff ( all manga in the category, can't remove any manga from it, can't be removed from **Settings › Library › Edit Categories**, doesn't appear in "Edit categories" of a manga )

### Why/User Benefit/User Problem
Makes it way way easier to manage your library by having a list of all manga in a single category.

Q: "But can you instead just make an "All" category yourself and add everything there?"

It's inefficient. Why would I have to manually add something in an "All" category?

**Comment by arkon** [comment] 2020-06-19 23:56
Duplicate of #943

**Closed by arkon** 2020-06-19 23:56 UTC
Labels: feature

**Comment by vengiare** [comment] 2020-06-20 00:00
A 1.x feature, huh.
