### ISSUE TITLE
[Feature Request] ability to Delete Local Files In the App

### ISSUE THREAD

**Issue by ImPudding-tech** [inorichi/tachiyomi#3329] opened 2020-06-15 12:32 UTC
### Why/User Benefit/User Problem
Ability to Delete Local Files In The App
Because It is Hard to Delete Files from the File manager it Self. 
And please add A Range Select So that We can Delete or Download more... Or Add the feature "remove when marked as read" In Local Files not only in Downloads But IN local Files..

**Comment by arkon** [comment] 2020-07-26 21:17
So on the one hand, this sort of makes sense, but on the other hand I can envision users being confused because they thought it'd only remove something from Tachiyomi and not actually delete their local stuff (for some reason).

Up for debate.

**Comment by arkon** [comment] 2020-08-01 21:09
Duplicate of #1770

**Closed by arkon** 2020-08-01 21:09 UTC
Labels: feature
