### ISSUE TITLE
[Feature request] Comic/chapter-specific orientation toggle/settings 

### ISSUE THREAD

**Issue by MemeTroubadour** [inorichi/tachiyomi#1462] opened 2018-06-05 09:27 UTC
It's a bit of a bother to have to turn on auto-rotation to swap to landscape whenever you're reading horizontally (strips). It would be nice to have a comic-specific orientation setting, so that you could read one comic in landscape and still read any other comic in portrait without switching around orientations in your general settings.

It would also be cool to have a toggle button when reading to change the orientation of a page or chapter since some comics (mostly webcomics like xkcd) use both.

**Comment by wopian** [comment] 2018-06-05 19:44
Duplicate of #452

**Closed** 2018-06-06 10:53 UTC
