### ISSUE TITLE
{Issue} Extremely laggy when viewing manga in "Webtoon" mode

### ISSUE THREAD

**Issue by RYNAPU** [inorichi/tachiyomi#2041] opened 2019-05-19 04:53 UTC
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.4 (Latest)
**Android version:**
Andriod Pie 9.0 
**Issue/Request:**
The entire viewer gets really laggy and is fine after closing.
**Steps to reproduce (if applicable)**

 1. Chose vertical webtoon style manga from Manga Dex or other source(Manga Dex was what I had the issue for)
 2. Set viewer to "webtoon" 
 3.possibly have issue.

**Other details:**
This happened completely random at sometimes.

**Comment by hXtreme** [comment] 2019-05-22 11:50
This is a well known issue. The problem occurs when a large image is to be loaded into the ram.

Does this occur for any webtoon or for '1 page' webtoons only?

**Comment by ZaneHannanAU** [comment] 2019-05-23 03:45
Dupe of #1908

**Closed** 2019-05-23 07:49 UTC
