### ISSUE TITLE
[Feature Request]Detect combined pages in one image

### ISSUE THREAD

**Issue by yshui** [inorichi/tachiyomi#1281] opened 2018-02-28 03:36 UTC
Some manga (especially old ones) puts two consecutive pages into one image, make them hard to read.

Tachiyomi should detect wide images and make reading them easier (e.g. split them into pages)

**Comment by arkon** [comment] 2019-09-14 21:58
Duplicate of #1384

**Closed by arkon** 2019-09-14 21:58 UTC
