### ISSUE TITLE
Save chapters as .zip?

### ISSUE THREAD

**Issue by karehaqt** [inorichi/tachiyomi#1735] opened 2018-11-18 07:52 UTC
Is this possible in the latest version or do I need to start using the beta version?  Or, is it planned/not planned?

**Comment by tidux** [comment] 2018-11-26 19:20
Saving such files as .cbz instead of .zip would also allow easy export to other reader applications, like for an e-reader.

**Comment by toshiro9117** [comment] 2018-11-28 16:58
saving chapters to zip saves same little space too...

**Comment by inorichi** [comment] 2018-11-29 12:47
Duplicate of #918

**Closed by inorichi** 2018-11-29 12:47 UTC
