### ISSUE TITLE
[Bug] Mangadex automatically downloads only one group's chapter when multiple groups release the same chapter

### ISSUE THREAD

**Issue by vtruong68** [inorichi/tachiyomi#2794] opened 2020-03-30 18:46 UTC
### Device information
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
When a chapter is released by two different groups for the same chapter number and downloaded, selecting either group in the "chapters" menu results in only one of those group's chapter to be loaded. 

For example, group A releases chapter 1 and group B also releases chapter 1. The actual downloaded chapter 1s for both group A and B are from group A. This behavior does not occur when the file is not downloaded.

Looking in storage, only one version is downloaded and both groups releases point to that one chapter.

### Expected behavior
When multiple groups release the same chapter, the chapter should be downloaded per group and the downloaded chapters should correspond to the release of each group.

### Actual behavior
The downloaded chapters for the particular chapter number are all from one group. Usually the first group to release. This seems to be because all chapters sharing the same number point to a single chapter folder.

### Other details
This happens consistently for me when new chapters are found for "The Duchess With An Empty Soul". When selecting Ch. 35 for Magnificent Aurora Scans or KKJ Scans, I have the KKJ Scans version downloaded for both. This varies depending on which group releases their chapter first. Both groups are also marked as downloaded (Download new chapters is toggled on).

**Comment by arkon** [comment] 2020-03-30 19:26
Duplicate of #1893

**Closed by arkon** 2020-03-30 19:26 UTC
Labels: bug

**Comment by CarlosEsco** [comment] 2020-03-30 20:19
Also I believe this is fixed in dev tachiyomi

**Comment by vtruong68** [comment] 2020-03-30 20:22
> Also I believe this is fixed in dev tachiyomi

Is this something for the next release of Tachiyomi? The first post mentioning this bug was from over a year ago.

**Comment by arkon** [comment] 2020-03-30 20:45
It's not fixed yet.
