### ISSUE TITLE
[Feature Request] Rename mangas in the library

### ISSUE THREAD

**Issue by iliveinabag** [inorichi/tachiyomi#2457] opened 2020-01-07 12:33 UTC
While migrating mangas from mangarock to other sources, I noticed that most sources have their titles written in Romaji rather than in English. I'd like to have a way to either rename the mangas in my library or have them use their alternate English title if available via an option.
Being able to rename our manga would also allow to solve some sorting problems (for example, some mangas that have part 2 in their title actually appear before the part 1 manga) 

This could be implemented by having a new option next to the button that allows you to change covers. 
If syncing is a problem, then the edited mangas could still retain their original titles internally. This is mostly just a visual change that only affects the user's library.

**Comment by arkon** [comment] 2020-01-07 12:38
Duplicate of #2040. Please add your thoughts there!

**Closed by arkon** 2020-01-07 12:39 UTC
Labels: feature
