### ISSUE TITLE
Feature Request: add scanlation team nametag to chapters from batoto

### ISSUE THREAD

**Issue by Iliansic** [inorichi/tachiyomi#360] opened 2016-06-21 07:33 UTC
Considering lately there are a lot of quick lowquality scanlations on batoto for some of the series, which pop out before usual teams gets to release their version, is it possible to add scanlation team nametag for chapters, so it easier to differentiate them?

**Comment by inorichi** [comment] 2016-06-21 12:11
Duplicate of #107

**Closed by inorichi** 2016-06-21 12:11 UTC
