### ISSUE TITLE
[Feature Request] Option to auto-detect reading mode.

### ISSUE THREAD

**Issue by iamrrv01** [inorichi/tachiyomi#4141] opened 2020-12-15 15:13 UTC
## Why/User Benefit/User Problem
It will make the application more user friendly and will make more easy for lazy people like me to use the app.

## What/Requirements
It will simply start with the reading mode according to the tag mentioned on manga/manhua/webtoon.
example-suppose if I am reading solo leveling and it has 'Webtoon' tag and if I start reading it, it should change to webtoon.
if it's manhua then Left to right, and a default setting for manga.
if it's possible, then I would suggest to add an option for that in settings to switch it on/off or make some changes depending on user.

**Comment by scb261** [comment] 2020-12-15 15:22
Duplicate of #1664, you can add more details there

**Closed** 2020-12-15 15:28 UTC
Labels: feature
