### ISSUE TITLE
Suggestion for new feature

### ISSUE THREAD

**Issue by sm7297** [inorichi/tachiyomi#207] opened 2016-03-08 15:53 UTC
1. Add option to update only selected catagory
2. Option to export setting and library to a file so that if i update the app i can import it from the rather than manually adding all of them 
3. Add Plus button in the library to add new manga
4.Add Mangastream catalogue

**Comment by shogunreaper** [comment] 2016-03-08 18:56
i agree with all of these.

**Comment by NoodleMage** [comment] 2016-03-08 20:05
First of all. Please use a list for multi-part issues. See: https://github.com/inorichi/tachiyomi/blob/master/.github/CONTRIBUTING.md

To answer your questions / issues.

1. Duplicate of #158
2. Duplicate of #34. 
<i>Btw you don't have to delete the application when you update. So I don't know what you mean by the second part of this issue :).</i>
3. To do this we have to add a FAB button to the library. Because we think things will get to crowded with it, this will not be implemented. You will need to swipe and click to get to library :).
4. Please make a separate issue for this one.

**Comment by inorichi** [comment] 2016-03-10 19:52
Everything explained above.

**Closed by inorichi** 2016-03-10 19:52 UTC
