### ISSUE TITLE
[Feature Request] Preload Next Chapter While Reading

### ISSUE THREAD

**Issue by Lindsor** [inorichi/tachiyomi#2505] opened 2020-01-15 14:32 UTC
### Why/User Benefit/User Problem
This will vastly increase the UX for users who are binge reading (like most of us).
Currently when reading in WebToon mode when you reach the end of the chapter the scrolling "locks" while the app downloads the next chapter.
This also happens on normal reading mode (non-webtoon) but its less noticeable.

### What/Requirements
When you reach a new chapter while reading we should download the next chapter and preload the next <N> chapters.
This will allow the user to never notice the app is loading a chapter since by the time they are done reading the next one is already available.

<N> should most likely be configurable in the settings since some people read faster / have slower networks they can tweak it to what works for them

**Comment by arkon** [comment] 2020-01-15 14:36
Duplicate of #2367

**Closed** 2020-01-15 14:37 UTC
Labels: feature
