### ISSUE TITLE
[Feature Request] Auto-Rotate Double Page Spreads

### ISSUE THREAD

**Issue by imDED** [inorichi/tachiyomi#3533] opened 2020-07-28 00:34 UTC
Double page spreads are often a pain to read on mobile. If you have your phone locked in portrait mode, you need to zoom in and won't be able to see the whole thing all at once.

It would be nice if there were a toggleable feature that would rotate a page by 90 degrees counterclockwise if it is wider than it is tall/has an aspect ratio greater than 1:1.

**Comment by arkon** [comment] 2020-08-01 21:20
Sort of a duplicate of #1977

**Closed by arkon** 2020-08-01 21:20 UTC
Labels: feature
