### ISSUE TITLE
[Feature Request] Auto scroll

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi#2987] opened 2020-04-29 17:05 UTC
### Why/User Benefit/User Problem
Convenient cuz sometimes im too lazy to scroll down the manga

### What/Requirements
As the title says i would like the autoscroll toggle feature where i can choose at what speed to scroll down the screen like slow, moderately slow etc.

**Comment by arkon** [comment] 2020-04-29 17:07
Duplicate of #2093

**Closed by arkon** 2020-04-29 17:07 UTC
Labels: feature
