### ISSUE TITLE
Feature Request: Ability to delete downloaded content for a selected manga.

### ISSUE THREAD

**Issue by namack75** [inorichi/tachiyomi#38] opened 2016-01-19 19:13 UTC
Similar functionality to what MangaWatcher provided under the 'Profile' section. 
It provided a a Library List, with total disk space used and options to Delete All, Delete All Read, etc.

Useful when you need to clear out space on your device.

**Comment by namack75** [comment] 2016-01-19 19:16
Hopefully you don't mind me popping in these feature request.

**Comment by inorichi** [comment] 2016-01-19 20:09
It's fine, but this one looks like a duplicate of #27

**Comment by namack75** [comment] 2016-01-20 05:24
Sort of (based on the description of #27). 
I've never used MangaRock.

The key feature was the Delete All, Delete Read chapters of a given manga.
Its probably a merge of both tickets.

**Comment by inorichi** [comment] 2016-01-20 18:37
It will be something like that. Closing this (duplicate of #27).

**Closed by inorichi** 2016-01-20 18:37 UTC
