### ISSUE TITLE
[Bug] Cannot click on 3 horizontal line to login in web view (MangaDex) 

### ISSUE THREAD

**Issue by lohszeying** [inorichi/tachiyomi#2964] opened 2020-04-26 17:25 UTC
### Device information
* Tachiyomi version: 0.8.5
* Android version: 8.0.0
* Device: Samsung S7

## Steps to reproduce
1. Under catalogue, click on Browse for MangaDex extension
2. Open in Web View
3. Press 3 horizontal line in web view of mangadex to try to login

### Expected behavior
The login layout should appear (but as Guest)

### Actual behavior
Pressing on 3 horizontal line icon doesn't have any effect

### Other details
When logging in with my Google Chrome app, I can login

**Comment by arkon** [comment] 2020-04-26 17:29
Duplicate of #2963

**Closed by arkon** 2020-04-26 17:29 UTC
Labels: bug
