### ISSUE TITLE
[Bug] Downloaded chapters remain as tmp folder

### ISSUE THREAD

**Issue by chenghaoli36** [inorichi/tachiyomi#3867] opened 2020-10-01 00:20 UTC
## Device information
* Tachiyomi version: Stable 0.10.5
* Android version: 11
* Device: Pixel 3a

## Steps to reproduce (sorry that this is so vague, it only really happens to some chapters, not sure why)
1. Download any one chapter
2. Wait for the chapter to finish downloading
3. Close then reopen Tachiyomi

### Expected behavior
Chapter should remain downloaded 

### Actual behavior
The chapter is downloaded but remains a tmp folder and tachiyomi cannot access it. Downloading from this point will result in an error unless you delete that folder and try again in which it would still make the folder a tmp folder.

## Other details
default download location, not sd card. something probably broke when upgrading android but this bug only happens occasionally

The tmp folder actually has the completed chapter

The only way to fix this is by manually copy pasting the pages from the tmp folder into another folder and then copying it back in renamed as "Chapter" or whatever the chapter name is without the tmp, however its pretty tedious and doesn't work for all chapters.

### Recording of the bug:
https://streamable.com/ywpvip

**Comment by scb261** [comment] 2020-10-01 06:15
Check if it has apostrophe in the name, probably duplicate of #3778

**Comment by chenghaoli36** [comment] 2020-10-01 06:38
> Check if it has apostrophe in the name, probably duplicate of #3778

Hmm yeah it does so it's probably the same issue. Sorry about that.

**Closed** 2020-10-01 06:38 UTC
Labels: bug
