### ISSUE TITLE
Tachiyomi app crashes with play buttom resume

### ISSUE THREAD

**Issue by Aithey** [inorichi/tachiyomi#1449] opened 2018-05-31 18:34 UTC
**App version: 0.7.4**

**Issue/Request:App crashes when pressing the blue play button to resume reading chapters, in the chapters section of a manga.**

**Steps to reproduce (if applicable)**

 1.Open app
 2. Go to chapters
 3.Press blue play button on bottom right to resume

**Other details: Phone model: Samsung Galaxy S9+ Android Version: 8.0.0**

**Comment by Zeraflut** [comment] 2018-07-11 21:34
I have the same issue with a Xiaomi Mi A1 with the same app version (which seems to be still the latest stable version)

**Comment by evo85210** [comment] 2018-12-02 21:42
0.8.0 still happening, didn't happen before for me tho

**Comment by arkon** [comment] 2020-01-04 20:43
Closing due to age. Open another issue (with logs or more detailed reproduction steps) if it's still happening.

**Closed by arkon** 2020-01-04 20:43 UTC
