### ISSUE TITLE
add reading settings for every category in categories

### ISSUE THREAD

**Issue by Philosophy-Pr** [inorichi/tachiyomi#3299] opened 2020-06-09 16:26 UTC
In some cases the default reading setting doesn't be the right setting for all graphic novels, so if you added reading settings for all categories we can organize all graphic novels that have the same reading setting in one category and that make reading easier as we don't have to change the settings in every graphic novel we will read.
Thank you for your hard work

**Comment by arkon** [comment] 2020-06-09 16:57
Duplicate of #2518

**Closed by arkon** 2020-06-09 16:57 UTC
Labels: feature
