### ISSUE TITLE
Default Category Always Ask setting is broken.

### ISSUE THREAD

**Issue by iKzone** [inorichi/tachiyomi#885] opened 2017-07-08 19:46 UTC
The default category (always ask) setting does not work when you try to bookmark a manga. I have two categories which is Default and Plan to Read. It automatically adds the manga into my Plan to Read Category and does not give me the option to select with category to go to.

Version: v0.6.1

**Comment by inorichi** [comment] 2017-07-08 20:38
As workaround you can create a category called Default. Only one category and the default is a special case, I never thought about it.

**Comment by xChickens** [comment] 2017-07-09 05:13
Creating another category called Default still keeps the original default category and I don't think there's a way to mass move all of the old Default to new one. :/

But I found that the update r1149 to r1152 is where it stopped asking for categories

**Comment by wopian** [comment] 2017-07-09 16:23
Mass moving to a different category is possible - just no way to select all with 1 action. 

In the `default` category long hold any manga, then just tap all the other manga. Press the tag icon (1st) and chose the category to move them to

**Comment by LakotaGray** [comment] 2018-03-30 04:53
The issue is due the fact you have only created a single category, which is then assumed to be where you want series to go. Create a 2nd category to go along with default and your “plan to read” it will solve your issue

**Comment by arkon** [comment] 2020-01-04 21:00
I don't think this is still an issue?

**Closed by arkon** 2020-01-04 21:00 UTC
Labels: bug
