### ISSUE TITLE
Clickable authors / artists / genres fields in info tab not working

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#1077] opened 2017-11-23 19:06 UTC
I thought #860 by @QuestofIranon was implemented with global search time ago. I don't know if it has not been done yet or if there is a problem.

Thanks!.

**Comment by 444nonymous** [comment] 2017-11-23 19:46
Related to https://github.com/inorichi/tachiyomi/issues/1079 "Advanced search in globlal search", since "Clickable authors / artists / genres fields in info tab"  could open a global search.

**Comment by NoodleMage** [comment] 2017-11-29 19:15
Not yet implemented. Makes it duplicate of #860

**Closed by NoodleMage** 2017-11-29 19:15 UTC
