### ISSUE TITLE
Sub-Categorys

### ISSUE THREAD

**Issue by Schnoinsch** [inorichi/tachiyomi#2559] opened 2020-02-01 20:05 UTC
Sub categorys would be great. I guess i´m not the only one that built a huge library. Sometimes i just browse comics and save them to my library. But my "comics" tab is pretty full. Would be nice if there was an option to make folders in a category, for example of the "Comic" category, i would make a few folders like "Marvel", "Image" etc. to get an better overview.

**Comment by joseph619** [comment] 2020-02-01 20:10
Why not just make separate categories for Marvel/DC etc?

**Comment by Schnoinsch** [comment] 2020-02-01 20:23
I don´t know others librarys. I for my part, already got 6-7 categories and try to have not too much of them, since scrolling through them is not very convenient.
Other use of sub categorys would be folders for genres. So you might have a comic category with fantasy, sci-fi etc. folders.

**Comment by arkon** [comment] 2020-02-02 21:06
Duplicate of #1803

**Closed by arkon** 2020-02-02 21:06 UTC
Labels: feature
