### ISSUE TITLE
[Feature Request] improve restore function

### ISSUE THREAD

**Issue by DieKatzchen** [inorichi/tachiyomi#1930] opened 2019-03-25 01:13 UTC
Two things. Would it be possible for the backup to include which extensions are installed? And also would it be possible to have the restore add series even if it 503/404s?

**Comment by Keltere** [comment] 2019-04-10 21:29
With some roms on my nexus 5 sometimes, while restoring my 200 manga list, the restore just freeze and i need to stop it and do it again.
An async restore with notification should be implemented.

**Comment by metroid112** [comment] 2019-04-11 11:58
The backup already has which extension does the manga thats in the backup belongs to. I guess its about adding a behaviour in which if the extension is not installed -> prompt to install it. Maybe in a preemptive scan during the backup process.

**Comment by Sparh4wk** [comment] 2019-04-11 12:22
well I think we need better backup/restore for future, cause as was already mentioned if you have more mangas, you are not able to restore it, unless you split your backup files and thats not something that everyone can do.. yes I know thats sad, but I know a lot of ppl who cant do that alone :) and +1 for extension detection as well.

**Comment by as280093** [comment] 2019-04-11 12:27
i think some request ed feature are duplicate of #1810

**Closed** 2020-07-10 21:47 UTC
Labels: feature
