### ISSUE TITLE
Download queue never seems to process

### ISSUE THREAD

**Issue by Codex-** [inorichi/tachiyomi#73] opened 2016-01-26 02:38 UTC
Items get added to queue without issue but they never appear to download (running 0.1.2)

Have tried on and off of wifi with only over wifi set to off.

Android 6.0.1, Nexus 7 LTE

I wiped cache/data, restarted app etc.

The button on the form also appears to do, hit stop or start and it doesn't change to starting ever, although it does let you stop.

Not sure how else to describe the issue lol.

**Comment by malakigerald19** [comment] 2016-01-26 02:45
Had this issue on Marshmallow.
Go to Settings>Apps>Tachiyomi>Permissions> Switch on Storage and other permission

**Comment by Codex-** [comment] 2016-01-26 02:48
Oh wow, I forgot about marshmallow doing that. Awesome, working now, thanks.

Should probably add something in to invoke setting those permissions from first launch or something.

**Comment by inorichi** [comment] 2016-01-26 12:44
Duplicate of #36

**Closed by inorichi** 2016-01-26 12:44 UTC
