### ISSUE TITLE
[Bug] <Scroll Prematurely Stops>

### ISSUE THREAD

**Issue by PennyJim** [inorichi/tachiyomi#4013] opened 2020-11-06 06:18 UTC
## Device information
* Tachiyomi version: App version: 0.10.5 (standard, 2769e27a2, 51)
* Android version: 10 (SDK 29)
* Android build ID: QPMS30.80-51-8
* Device brand: motorola
* Device manufacturer: motorola
* Device name: sofia
* Device model: moto g power
* Device product name: sofia_retail

## Issue
After reading/scrolling for a while, once I reach the end it'll fail to allow me to scroll to the very end. I end up being incapable of seeing the last page and last chunk of the second to last page.

I haven't tried to recreate this issue, but it happens every time I've been reading for a while. I now realize that a common occurrence between these events might be when I've locked my phone multiple times while reading that comic. I've also got the fingerprint thing on.

## Other details
Reading mode: webtoon
Double tap animation speed: normal
Show reading mode: off
32-bit color: off
Animated page transitions: off
Rotation: force portrait
Background color: black
Fullscreen: on
Show content in cutout area: on
Keep screen on: on
Show page number: off
Skip chapters marked read: off
Skip filtered chapters: on
Always show page transitions: on

Side padding: none
Crop borders: off

- Side note: giving the user the ability to export (and import) their settings would help in sharing information

**Comment by arkon** [comment] 2020-11-06 13:34
Duplicate of #3052

**Closed** 2020-11-06 13:34 UTC
Labels: bug
