### ISSUE TITLE
[Feature Request] Recommendation Tab

### ISSUE THREAD

**Issue by Mathew20kdroid** [inorichi/tachiyomi#3935] opened 2020-10-12 18:40 UTC
## Please a recommend comics tab
Please add another tab in the home page showing the **trending** and **recommend mangas and comics**.
Add a **rank list or top chart** showing the most read mangas

**Comment by Soitora** [comment] 2020-10-12 18:44
Duplicate of #376.

**Closed** 2020-10-12 19:19 UTC
Labels: feature
