### ISSUE TITLE
[Enhancement] speed up application start up

### ISSUE THREAD

**Issue by raslmenea** [inorichi/tachiyomi#2678] opened 2020-03-08 17:21 UTC

**Comment by CarlosEsco** [comment] 2020-03-08 17:42
This is dependent on your library size

**Comment by raslmenea** [comment] 2020-03-08 18:15
i don't really have that much of mangas in my library (less than 10) and i don't use sd card and have plenty of free space.

**Comment by arkon** [comment] 2020-03-08 18:19
How slow is it? What's your device?

**Comment by raslmenea** [comment] 2020-03-08 19:18
it takes 2 seconds to start the app (dev 1857), while in version 0.8.4 it takes less than a second to start the app.
tested with y9 prime

**Comment by likehelly** [comment] 2020-03-26 14:10
it takes one second longer? 

is that really an issue.

**Comment by arkon** [comment] 2020-04-02 03:52
Duplicate of #2676

**Closed by arkon** 2020-04-02 03:52 UTC
Labels: bug
