### ISSUE TITLE
[Feature Request] New Filter Option: "Last Added".

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#2708] opened 2020-03-15 12:12 UTC
### Why/User Benefit/User Problem
This would allow the users to sort their manga based on **when** they added them.

### What/Requirements
Using this filter would sort all the manga based on which manga was added to library *last*, and before that, and before that, and so on. This could work inversely too, like which manga was added *first*, and what after that, and after that, and so on.

**Comment by arkon** [comment] 2020-07-10 19:14
Duplicate of #1287

**Closed by arkon** 2020-07-10 19:14 UTC
Labels: feature
