### ISSUE TITLE
 [Feature Request] Download manager upgrade

### ISSUE THREAD

**Issue by ArjixGamer** [inorichi/tachiyomi#2267] opened 2019-10-04 21:15 UTC
**App version:Latest Dev**

**Android version:Android Oreo 8.0**

**Issue/Request:Download 2 or more chapters from different sources at the same time**
Well it got me that the reason that 4 chapters downloading at the same time got users banned so how about making it so that 2 chapters from different sources can be downloaded at the same time!

**Other details:**
For example I have Boku no hero academia and nanatsu no taizai and I use Kissmanga Source on Boku no Hero Academia and Mangarock Source on Nanatsu no Taizai. And it would be cool if they started downloading at the same time

**Comment by Flat** [comment] 2019-10-04 21:32
#1573 #1595 #1603 #2102 #1567 tl;dr no not for this version.

**Comment by arkon** [comment] 2020-04-11 15:47
Duplicate of #2534

**Closed by arkon** 2020-04-11 15:47 UTC
