### ISSUE TITLE
[Feature Request/Suggestion] A simple fix by me for an underlying issue

### ISSUE THREAD

**Issue by VenomMage** [inorichi/tachiyomi#2191] opened 2019-08-26 14:12 UTC
_App version: 0.8.4_

_Android version: 9_

_Issue/Request:_ Currently, most gallery apps including Google Photos display the downloaded mangas. This happens because these apps check per folder for .nomedia file(s). Tachiyomi currently only creates a .nomedia file in Tachiyomi/Downloads (the parent folder) and not every folder where the chapters of manga are stored so they end up appearing in the gallery apps.

So, please make it so that Tachiyomi automatically adds a .nomedia file to each chapter folder.

Thanks for the amazing app!

**Comment by VenomMage** [comment] 2019-08-26 14:50
I have an Asus Zenfone Max Pro M1

**Comment by VenomMage** [comment] 2019-08-29 15:00
But it DOES happen for me

**Comment by RuthlessRuler** [comment] 2019-09-10 09:10
It also happens to me but for only some downloaded mangas like Volcanic Age.

**Comment by arkon** [comment] 2019-09-14 21:56
Duplicate of #2104

(Not exactly, but close enough for triaging sake)

**Closed by arkon** 2019-09-14 21:56 UTC
