### ISSUE TITLE
[Feature Request] Page turn animation

### ISSUE THREAD

**Issue by saintbepis** [inorichi/tachiyomi#3950] opened 2020-10-18 01:02 UTC
## Why/User Benefit/User Problem:
Alot of horror Mangas rely on the page turn for a shock factor and it isn't as effective when you simply slide to the next page.

## What/Requirements:
You can go to another page as if you were turning the page in a physical book.

**Comment by scb261** [comment] 2020-10-18 08:20
Duplicate of #1397

**Closed** 2020-10-18 13:37 UTC
Labels: feature
