### ISSUE TITLE
[Feature Request] Ratings

### ISSUE THREAD

**Issue by R-Jimenez** [inorichi/tachiyomi#1993] opened 2019-04-19 12:10 UTC
**App version:**
0.8.4

**Android version:**
9.0

**Issue/Request:**
As title suggests, was wondering if there were any plans for the introduction of a rating/star system for series and/or individual chapters. This would open up a lot of ability for sorting as well as help larger tracked catalogs like mine where I have quite a few dropped series, and am starting to forget which ones were more redeemable than others. This would also open up extension devs to be able to load or possibly even submit ratings for a user.

Unsure of how your data is structured but adding a field hopefully isn't too troubling, and so this should be mostly a UX feature. Cheers.

**Comment by CarlosEsco** [comment] 2019-04-19 12:12
are you trying to rate your own library?  If so why not just categories for it?

**Comment by R-Jimenez** [comment] 2019-04-19 12:25
Currently my categories are being used for managing which series I'm currently reading, (On Deck | On Hold | Deep Storage) in combination with the library update/download options, as I couldn't find a way otherwise to keep a series in my library without updating it (and subsequently getting the notification for it). I also don't want to remove series from my library entirely unless it's 100% dropped as I have a poor memory and try quite a lot of series with potential. Plus I enjoy collecting series to discuss with my wife or friends.

Generally I find user-organized folders/categories ratings for media a clunky solution, as stars are at least five, usually ten (half-stars) classifications, and 1-10 almost always includes decimal tenths (100!).

**Comment by CarlosEsco** [comment] 2019-04-19 12:33
so first off, you can have more categories for ratings and manga can be in more than 1 category.  2nd  maybe @inorichi  feels different but i dont see a reason to have rating system for your own library.  If you really needed a rating you could sync them to a tracker (mal, anilist, kitsu)  and rate them on the tracker.    Then refer to the tracker when you want to read your 5 star manga.

**Comment by R-Jimenez** [comment] 2019-04-19 12:52
You can set multiples, and it does solve the download category process, but not the viewing process, as each tab is only a single category, meaning if I wanted to see all series I rated as 5 stars, that are also On Hold/in any other category, I have no way of doing that, while you guys have already built a filtering and sorting system for the library browser that could serve this if you made ratings series metadata. 

Anyways, was just seeing if there had been thought put to it, as it's just more data that can be pulled through extensions and presented to the user, in addition to the user having his own data to store. I'm sure not many sources even have ratings (MangaDex is the only one I'm familiar with), and while I think MD is a great source, I understand there are many other extensions that may make this case smaller.

In my eyes the difference here lies in whether this app wants to be more of a reader app or a library management app, which is of course entirely your prerogative. I'm obviously coming at it from the latter but I have no idea what your user metrics are.

**Comment by arkon** [comment] 2020-04-26 22:55
Duplicate of #2272

**Closed by arkon** 2020-04-26 22:55 UTC
