### ISSUE TITLE
Add a new tracking website

### ISSUE THREAD

**Issue by vilaroo** [inorichi/tachiyomi#1985] opened 2019-04-16 11:12 UTC
**App version:**
0.8.4
**Android version:**
MIUI 10.2
**Issue/Request:**
Add tracker
**Steps to reproduce (if applicable)**

 1. Add a tracker website for comic books extension readcomicsonline if possible: 
https://leagueofcomicgeeks.com/

**Comment by arkon** [comment] 2019-12-22 21:27
Duplicate of #2356

**Closed by arkon** 2019-12-22 21:27 UTC
