### ISSUE TITLE
[Feature Request] Mass Mark Read/Unread/Download

### ISSUE THREAD

**Issue by folta01** [inorichi/tachiyomi#1181] opened 2018-01-12 01:56 UTC
Request for extended menu on main screen, to select multiple mangas and perform action (mark as read/unread, download all)

![screenshot_20180111-194857](https://user-images.githubusercontent.com/11202412/34856200-6e6c467c-f709-11e7-8d7b-c74bee7097fa.png)

**Comment by xadden** [comment] 2018-01-12 13:20
This is the only feature I am missing from manga rock. Sometimes I have to mark certain chapters as read and I have select 100+ chapters one by one.

**Comment by CarlosEsco** [comment] 2018-01-12 14:38
@xadden

In a manga you can mark previous as read so you can easily mark 100 plus chapters without having to select 1 by 1

**Comment by xadden** [comment] 2018-01-12 20:12
@CarlosEsco that's good to know but if I want to download the next 50 chapters I have to click all of them one by one.

**Comment by NoodleMage** [comment] 2018-01-12 20:27
You can also click download 10, 5 times. But I understand where you're coming from :).

I don't really like mass selection from manga though. Personally I think all manga should be managed individually. I will try to implement #1179 today though

**Comment by shogunreaper** [comment] 2018-01-19 16:49
how about letting us enter a custom number to download?

**Comment by NoodleMage** [comment] 2018-01-19 17:35
See #1185.

**Comment by Malkierian** [comment] 2018-12-02 21:20
Well, it's good to know that's what "Mark Previous Read" means.  Should be made clearer, though, had to come here and almost open up my own issue to find out.

**Comment by metroid112** [comment] 2018-12-03 12:42
How would it be made clearer? The action is pretty much self-explainatory.

**Comment by Malkierian** [comment] 2018-12-03 17:03
When I read it, it struck me as mark previous chapter (singular) as read.  Granted, I didn't try it out to see what it was, but I was confused, so thought it better not to risk it.  It'd be clear enough if it was just changed to "Mark Previous Chapters Read" or "Mark All Previous Read" or something like that.

**Comment by stardrogen** [comment] 2020-03-04 21:44
Is there any update for this yet by chance? I just fully migrated my 860 manga and was wondering if this feature would be coming? Definitely be amazing for the many like me who will be migrating especially now that MR is gonna be fully dead and buried

**Comment by Malkierian** [comment] 2020-03-04 21:57
You can still go to each one and do a select all > mark read, but yeah, that's going to be rather tedious for 800+ mangas. But if you actually migrated (using Tachiyomi's source migration feature) it should have kept the read status of those chapters.

**Comment by Malkierian** [comment] 2020-03-04 22:30
@clem193 stardrogen is talking about 800 or more mangas they now have to go through individually. The process we have now is valid, but it's two or three extra steps per manga than could be needed with operations on the manga list itself.

That being said, there IS a mass "Mark as unread" option. And it's virtually the same as I was talking about in my last comment. Go into the chapter list for a manga, long-press on any chapter, and tap the triple dot in the top right corner of the header. You'll see "Mark as read", "Mark as unread" and "Select all".

**Comment by CarlosEsco** [comment] 2020-03-04 22:42
@clem193 long press a chapter.  3dot at top, select all, 3 dot at top, mark unread

**Comment by CarlosEsco** [comment] 2020-03-04 22:44
Another option long press a chapter, long press another chapter it will select between then you can 3 dot at top far as unread

**Comment by inverlock** [comment] 2020-03-10 05:34
This would be nice to have I have to Mark 1900 manga now

**Comment by Fyzhex** [comment] 2020-03-13 02:26
Would have to agree that these need to be a future. I saw that some were saying that there is an alternative for it so why should this be a thing. But that alternative is nice for one or two manga but when you're like me and some of the others her we don't have 20 or 30 manga we range in the high hundreds to low thousands. Said you don't think it's a good idea don't knock it down since there is a large group of us that think it's wonderful. And a few of us would pay to have it as one.

Other note if someone could point me to the line of code in the Json backup file that states that a manga has been "read" I would greatly appreciate it. I personally could not see it but I am not a programmer.

**Comment by Malkierian** [comment] 2020-03-13 02:48
Unfortunately, there is no one single line that marks it as read, it keeps track of the individual read chapters. If it's in the chapter list, it's been read.
![image](https://user-images.githubusercontent.com/774771/76584975-675b4f80-649a-11ea-9ab0-3013baa0cc08.png)
I believe the "r" of 1 is what marks that individual chapter read. Sorry, no easy fix for you there.

**Comment by Fyzhex** [comment] 2020-03-13 16:28
I did look and saw those lines but was unsure if that was true. I'll see if it is and if not I'll just have to find one chapter mark it as read and unread and see what changes and see if I can make a report for it to help others. Heck maybe someone could right a small script to only change those portions of the code untill it becomes main.

**Comment by Fyzhex** [comment] 2020-03-13 16:35
After looking you're right. If it was already in there we could have maybe done something but it doesn't look like it sadly. It would probably take longer trying to make that happen via the Backup file sadly.

**Comment by arkon** [comment] 2020-04-26 22:27
Duplicate of #156

**Closed by arkon** 2020-04-26 22:27 UTC
