### ISSUE TITLE
[Feature Request] Set a certain "viewer" for each Category

### ISSUE THREAD

**Issue by Marushuu** [inorichi/tachiyomi#3077] opened 2020-05-05 14:40 UTC
### Why/User Benefit/User Problem
It would benefit the user in a way that allows them to customize every manga's view setting when it belongs to a certain category if that category needs it to be without the user needing to customize it themselves.

### What/Requirements
This would mainly be seen in the categories option, though this is only one feature request, I feel that the Categories option has still a lot you can add in to. 

This is not of utmost importance at all and would mainly feel like a small "quality of life" improvement.  But I do feel that the Categories Option, which I believe is an amazing feature, has greater potential.

**Comment by arkon** [comment] 2020-05-07 03:07
Duplicate of #2518

**Closed by arkon** 2020-05-07 03:07 UTC
Labels: feature
