### ISSUE TITLE
[Feature Request] Automatic Backup & Restore on Google Drive.

### ISSUE THREAD

**Issue by alfaazian** [inorichi/tachiyomi#3986] opened 2020-10-29 13:54 UTC
## Why/User Benefit/User Problem
With this feature, it will be easy to keep track of mangas.

## What/Requirements
It will just be automatic backup but we can set path to google drive and we can restore it with single click.
(Somewhat similar to what we experience when we login into Whatsapp.)

**Comment by scb261** [comment] 2020-10-29 13:57
Duplicate of #912

**Closed** 2020-10-29 14:25 UTC
Labels: feature
