### ISSUE TITLE
[Feature Request] Mass Source Migration

### ISSUE THREAD

**Issue by kaononymous** [inorichi/tachiyomi#2777] opened 2020-03-28 23:56 UTC
App version:
r1940
Android version:
9
Issue/Request:
Mass Source Migration
Other details:
If you want to migrate a few manga to another source you currently have to click on the source and then click the manga **individually** and migrate to another source. 
e.g.
![Screenshot_20200329-103703_Tachiyomi](https://user-images.githubusercontent.com/62789832/77836636-fe6b1b80-71ab-11ea-8fae-85651c86af13.jpg)

If you are using one source for a huge list of manga and that source has issues or no longer works (i.e. MangaRock) then it is very time consuming to go into each individual manga and change it. Any way to streamline this process would be good. 
For example, mass migrate option which finds the closest match from another specific source, and works in the background and then allows the user to change it if it is incorrect or if there were no matches

**Comment by kaononymous** [comment] 2020-03-28 23:58
#2605

**Comment by evo85210** [comment] 2020-03-29 02:43
This would be a nice to have.

**Comment by Adsam112** [comment] 2020-03-29 17:50
I support this as well, it would be a welcome feature.

**Comment by joseph619** [comment] 2020-03-29 17:52
Duplicate of #1729

**Closed** 2020-03-29 18:01 UTC
