### ISSUE TITLE
[Bug] Cannot read half of last page when reading continuously

### ISSUE THREAD

**Issue by Mymiano** [inorichi/tachiyomi#3282] opened 2020-06-05 11:25 UTC
### Device information
* Tachiyomi version: 0.9.2-2373
* Android version: 10 (SDK 29)
* Device: Mi 9T Pro

## Steps to reproduce
1. Read from first chapter up to last

### Expected behavior
Must able to read last page without going back to chapter list to fix this behavior

### Actual behavior
Continuously reading shows only half of the last page. It will indicate that it will be the last page but it only shows half of it regardless of webtoon or manga

**Comment by arkon** [comment] 2020-06-05 12:23
Were you zoomed in or out?

**Comment by Mymiano** [comment] 2020-06-06 01:00
> Were you zoomed in or out?

just fit on my screen

this is my reader settings
![101978451_949920215470053_3040212679046417335_n](https://user-images.githubusercontent.com/24500122/83932253-fcd55980-a7d3-11ea-9dcc-9e9417c9e450.jpg)
![102707399_637710560155978_3309019238253078791_n](https://user-images.githubusercontent.com/24500122/83932259-019a0d80-a7d4-11ea-95f6-2d5c1bdbda44.jpg)

**Comment by Camusensei** [comment] 2020-06-14 22:23
In case it helps, this happens to me if I tried to zoom while reading the chapter. Always.
This bug was introduced with the unzoom feature.

**Comment by arkon** [comment] 2020-08-01 21:47
I do believe this is a duplicate of #3052

**Closed by arkon** 2020-08-01 21:47 UTC
Labels: bug
