### ISSUE TITLE
[Feature Request] automatically re-download chapter

### ISSUE THREAD

**Issue by Poncow5** [inorichi/tachiyomi#3942] opened 2020-10-14 19:18 UTC
## Why/User Benefit/User Problem
When there's error or when internet down you don't have to manually tap resume again

## What/Requirements
Automatically re-download when there are an errors or when the internet back again.

**Comment by scb261** [comment] 2020-10-14 19:27
Duplicate of #959

**Closed** 2020-10-14 20:29 UTC
Labels: feature
