### ISSUE TITLE
[Bug] Hidden Toolbar won't reappear 

### ISSUE THREAD

**Issue by CalneKuro** [inorichi/tachiyomi#3488] opened 2020-07-18 04:41 UTC
### Device information
* Tachiyomi version: 0.9.2
* Android version: 7.1.1
* Device: Moto E4 Plus

## Steps to reproduce
1. Create a Category and add series until the category can be scrolled making the toolbar hide
2. Create a second category and add one series and try scrolling, the toolbar won't come back until i scroll back over to the previous category and scroll.

### Expected behavior
Toolbar should reappear without needing to have more than a few series in a category 

### Actual behavior
Toolbar does not come back in a category that has less series that does not allow you to scroll

### Other details
I think the hidden toolbar is a good feature for smaller devices but not always necessary on bigger devices so in addition to this behaviors being fixed could it also be optional?

**Comment by arkon** [comment] 2020-07-31 01:00
I assume you mean the bottom navigation bar and not the top toolbar.

Duplicate of #3392

**Closed by arkon** 2020-07-31 01:00 UTC
Labels: bug
