### ISSUE TITLE
[Feature Request] Next Chapter Preloading

### ISSUE THREAD

**Issue by X7SHaDe** [inorichi/tachiyomi#2383] opened 2019-12-22 05:40 UTC
### Why/User Benefit/User Problem
This would reduce waiting time on slow networks (especially on next chapter), and improve reading experience.

### What/Requirements
Preload the next chapter into memory (or storage) to avoid waiting.

**Comment by clem193** [comment] 2019-12-22 20:25
see https://github.com/inorichi/tachiyomi/issues/2379 for a workarround about this.

I do think it's a good idea, but not "next chapter preloading", because some stuff have chapters that are only 2 pages long while others have stuffs with like 400 pages chapters.

I think the best deal would be an option so the app (try to) preload the next 30 pages, regardless the size of the chapter (so if your chapters are 5 page long it will preload next chapters, and if your chapter is 200 pages it will only preload a part of that chapter).
Of course no need to make the app preload 30 pages at once (else we are going to trigger bans), but preload the pages one after another up to 30.

It would smarter to use the cache that way, rather than using it mainly to remember pages already read like it's currently the case.

**Comment by arkon** [comment] 2019-12-22 20:26
Duplicate of #2367 (feel free to add more thoughts there)

**Closed by arkon** 2019-12-22 20:26 UTC
Labels: feature
