### ISSUE TITLE
Download badges show wrong count

### ISSUE THREAD

**Issue by phanirithvij** [inorichi/tachiyomi#1531] opened 2018-07-03 03:38 UTC
**App version:**
0.7.4 and 0.7.4-r1425

**Issue/Request:**
Download badges count is wrong for some manga
For example
I only downloaded 58-90 chapters from Tokyo Ghoul re (kissmanga extension)
But it shows 132 as the download count

**Steps to reproduce**
Not applicable

**Other details:**
### Screenshots:

![screenshot_20180703-085902](https://user-images.githubusercontent.com/29627898/42197347-fc063aa6-7e9f-11e8-84e3-a315fdd9b6d1.png)

![screenshot_20180703-090453](https://user-images.githubusercontent.com/29627898/42197427-652cc540-7ea0-11e8-8c4e-63d997028533.png)

![screenshot_20180703-090443](https://user-images.githubusercontent.com/29627898/42197470-97cf8f3c-7ea0-11e8-9aa6-56438566c863.png)

**Comment by phanirithvij** [comment] 2018-07-03 03:40
I tried
- reinstalling,
- refreshing,
- rebooting,
- reinstalling the kissmanga extension
It didn't change (the download count)

**Comment by phanirithvij** [comment] 2018-07-03 03:48
I found why it's happening 
There are lots of **_tmp** directories in The directory of the Kissmanga/Tokyo Ghoul re/

I think this should be fixed

I am leaving the issue open for now

**Comment by wopian** [comment] 2018-07-03 12:41
Duplicate of #1193

**Closed** 2018-07-03 12:52 UTC
