### ISSUE TITLE
Bug on loading pages on source union mangas

### ISSUE THREAD

**Issue by MadBR2** [inorichi/tachiyomi#1560] opened 2018-08-03 13:01 UTC
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.7.4

**Issue/Request:**
All issues of Union mangas source
**Steps to reproduce (if applicable)**
I go to read a manga but all manga of source appears errror on loading of the pages
 1.
 2.
 3.

**Other details:**
Sorry for the English

**Comment by arkon** [comment] 2018-08-03 13:38
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/424

**Closed** 2018-08-03 14:06 UTC
