### ISSUE TITLE
Anilist tracker can't find Jin (MURAKAMI Motoka)

### ISSUE THREAD

**Issue by robbato** [inorichi/tachiyomi#1853] opened 2019-02-18 09:32 UTC
App version:Tachiyomi dev r1463

Issue/Request:Anilist tracker can't find Jin.

Steps to reproduce (if applicable) : Input Jin into anilist tracking

**Comment by robbato** [comment] 2019-02-18 09:37
Steps to reproduce (if applicable)
1. Add a webtoon like Tower of God, Lookism, etc. to your library.
2. Go to the tracking tab
3. Selecting on edit button and then searching returns no results.

**Comment by robbato** [comment] 2019-02-18 09:38
Steps to reproduce (if applicable)
1. Add Jin to your library.
2. Go to the tracking tab
3. The AniList details will be empty.
    Selecting on edit button and then searching returns no results.

**Comment by robbato** [comment] 2019-02-18 09:39
Steps to reproduce (if applicable)
1. Add Jin to your library.
2. Go to the tracking tab
3. Selecting on edit button and then searching returns no results.

**Comment by Flat** [comment] 2019-02-18 11:19
Can you provide a link to this on anilist.co?

**Comment by robbato** [comment] 2019-02-18 14:33
https://anilist.co/manga/41493/Jin/

**Comment by Skcyte** [comment] 2019-02-18 14:38
Probably caused by the limited amount the list tachi provided and how far down there if you search on Anilist. I checked just now.

**Comment by Flat** [comment] 2019-02-18 14:42
Due to the way anilist search works there isn't much we can do. We retrieve the first 100 results returned from the search however due to the short and relatively common nature of the name this returns a lot of results. In the rewrite the search may be paginated to fix this. https://anilist.co/search/manga?search=%22JIN%22&sort=SEARCH_MATCH

**Comment by as280093** [comment] 2019-02-18 15:24
@Flat is it possible to reduce search if url search is possible like i found the url on webite then copy paste it on tracking search result it will directly show the manga name of which url belongs
or even providing id search will solve it

**Comment by MerradOklom** [comment] 2019-02-18 19:59
Last time I checked I couldn't find Monster (Naoki Urasawa) and I had to add it manually to my Anilist.

**Comment by arkon** [comment] 2020-01-04 22:09
Anilist search sucks. Closing in favour of #1879.

**Closed by arkon** 2020-01-04 22:09 UTC
