### ISSUE TITLE
[Feature Request] Improvement for searching for source names in extension list

### ISSUE THREAD

**Issue by clarjon1** [inorichi/tachiyomi#4079] opened 2020-11-30 20:16 UTC
---

## Why/User Benefit/User Problem
When searching for a specific site source in the extensions list, if the extension does not have the site name, the user has no idea which addin will provide that site source. 

For example:

Search extensions list for "toonily". No results come up. However, there is a source for toonily provided by the Madara extension. The user may give up at this point, as they may mistakenly believe that their desired source is not available in Tachiyomi.

## What/Requirements
The metadata provided to the list of available extensions should also include a field listing the sites / sources the addin will provide for addins that provide multiple sources. Then the user should be able to search by site name as per normal, and the matching multiple source extension(s) will show in the search results, as if they had searched for that extension by its name.

**Comment by arkon** [comment] 2020-11-30 20:32
Duplicate of #3338

**Closed by arkon** 2020-11-30 20:32 UTC
Labels: feature
