### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by suvendu1997** [inorichi/tachiyomi#3612] opened 2020-08-06 07:22 UTC
Please add a setting to select the number of parallel download at a time.
More than 2 download get started at time,due to which my internet pack gets exhausted and not a single download get completed.
It is a big problem.

**Comment by CarlosEsco** [comment] 2020-08-06 10:51
duplicate of #3472

Also next time please provide a better title

**Closed by CarlosEsco** 2020-08-06 10:51 UTC
