### ISSUE TITLE
[Feature Request] Buttons for quick action with manga (relevant for screens 20:9 and tablets)

### ISSUE THREAD

**Issue by Akazotik** [inorichi/tachiyomi#3542] opened 2020-07-30 21:35 UTC
Since you did title screen like j2k, please add buttons for quick download and delete manga. Like on screenshot. Cause for now it's very uncomfortable make longtap on scren with 20:9 aspect ratio.

![photo_2020-07-31_00-25-58](https://user-images.githubusercontent.com/39062952/88976996-b8db6e00-d2c5-11ea-9f3c-b753af5f4ea5.jpg)

**Comment by arkon** [comment] 2020-07-30 21:36
Duplicate of #3039

**Closed by arkon** 2020-07-30 21:36 UTC
Labels: feature
