### ISSUE TITLE
[Feature Request] Using volume keys to enable forced landscape/portrait mode

### ISSUE THREAD

**Issue by pencilbook** [inorichi/tachiyomi#2689] opened 2020-03-10 07:36 UTC
Please give us the option to use volume keys to switch between forced landscape/portrait mode.

**Comment by arkon** [comment] 2020-03-10 11:42
Duplicate of #2446. I still don't think this is a great idea.

**Comment by saintbepis** [comment] 2020-03-10 13:14
I feel like the only useful thing you could do with the volume buttons when it comes to reading is using them to flip through pages but even then I wouldn't really see a use for them and that would just wear out the volume buttons after a marathon of reading

**Comment by pencilbook** [comment] 2020-03-11 16:01
I don't personally don't know anyone using the volume buttons to flip/change the page and I've never met anyone who's tried it because the idea behind it is irrational, because it'd technically break the volume keys (the volume keys are the cheapest parts on a phone) and I cannot see how volume keys can survive after using it to sift through 1000+ chapters with 20 pages each.

It'd be much better to give us options with volume keys, such as enabling forced landscape/portrait mode, going to the previous/next chapter and so on.

**Comment by pencilbook** [comment] 2020-03-11 16:01
I personally don't know anyone using the volume buttons to flip/change the page and I've never met anyone who's tried it because the idea behind it is irrational, because it'd technically break the volume keys (the volume keys are the cheapest parts on a phone) and I cannot see how volume keys can survive after using it to sift through 1000+ chapters with 20 pages each.

It'd be much better to give us options with volume keys, such as enabling forced landscape/portrait mode, going to the previous/next chapter and so on.

**Comment by CarlosEsco** [comment] 2020-03-11 16:24
don't know why this is still open.  Since its a duplicate of a closed issue.

**Closed by CarlosEsco** 2020-03-11 16:24 UTC
Labels: feature
