### ISSUE TITLE
[Bug] Minimising the app and restoring it again resets the page back to starting top position in webtoon mode

### ISSUE THREAD

**Issue by saikat0511** [inorichi/tachiyomi#3031] opened 2020-05-02 11:09 UTC
### Device information
* Tachiyomi version: 0.9.1-2237
* Android version: 10

## Steps to reproduce
1. Open any chapter in webtoon mode
2. Scroll down a bit
3. Minimise the app and open it again from recents

### Expected behavior
The last scroll location should be preserved

### Actual behavior
Page resets back to top position

### Other details
Might be due to lack of ram on my device so someone else should confirm this

**Comment by arkon** [comment] 2020-05-02 12:02
Duplicate of #3028

**Closed by arkon** 2020-05-02 12:02 UTC
Labels: bug
