### ISSUE TITLE
[Bug] [Preview] Library update gets stuck

### ISSUE THREAD

**Issue by hnoisemaker23** [inorichi/tachiyomi#3137] opened 2020-05-10 03:09 UTC
Update Library Feature is not working do you have a solution

**Comment by kai000bubbles** [comment] 2020-05-10 06:42
Yeah im getting this as well it gets half way and just stops while trying to update library

**Comment by hnoisemaker23** [comment] 2020-05-10 06:48
That what happened to me too but this Feature is like the best in the app for me so I hope it will be solved in future updates

**Comment by Riztard** [comment] 2020-05-10 10:19
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: ?
* Android version: ?
* Device: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment] 2020-05-10 10:37
Yea you guys provided 0 information. Please add the details requested (can see in riztards) post

**Comment by kai000bubbles** [comment] 2020-05-10 10:43
0 info? Wtf we were saying that when we go to update our library it stops halfway and just doesnt move.

**Comment by Riztard** [comment] 2020-05-10 11:02
0.1

**Comment by CarlosEsco** [comment] 2020-05-10 11:12
Open again fill in the actual template...

**Comment by arun07as** [comment] 2020-05-10 11:13
**Device information**
Tachiyomi version: App version: 0.9.2-2289 (standard, 436253dd, 45)
Android version: 9 (SDK 28)
Android build ID: LLD-AL10 9.1.0.166(C675E5R1P4)
Device brand: HONOR
Device manufacturer: HUAWEI
Device name: HWLLD-H
Device model: LLD-AL10
Device product name: LLD-AL10

**Steps to reproduce**
1. Open Library
2. Select Kebab menu ( the three vertical dots )
3. Select Update Library

**Expected behavior**
Manga in library is updated and shows new chapters

**Actual behavior**
Update gets stuck at some random manga and doesn't progress.

**Other details**
Screenshot
![Screenshot_20200510_164140_com huawei android launcher](https://user-images.githubusercontent.com/17740186/81497616-39995800-92dd-11ea-8903-e630544fc954.jpg)

**Comment by arun07as** [comment] 2020-05-10 12:03
Hi
Just giving some more information on the issue

- When I tried updating library in the morning today, it got stuck on one manga ( let's call it mangaA ). 
- I cancelled update and tried again and again, but it kept getting stuck at the same manga ( mangaA ).
- A few hours later, I tried again and this time it did not get stuck on the previous manga ( mangaA ), but instead on some other manga ( mangaB ), and in subsequent tried stuck at same manga ( mangaB ).
- I then removed the manga ( mangaB ) from library, and tried updating again, but update then got stuck on another manga ( mangaC ).
- I added the removed manga ( mangaB ) back and tried updating again, but again the update got stuck on mangaB.
- I tried to update a single category ( which has less manga and the mangas that got stuck are not present in it ) and the update succeeded.
- I then tried updating full library, and update got stuck again at mangaB
- And now, around an hour later, I tried updating again and this time update succeeded with no issues.

I've no clue what could be the cause of this issue, but hope these steps can be useful in debugging

**Comment by arkon** [comment] 2020-05-10 14:04
What sources are the ones that are stuck? Does it progress after some time?

**Comment by TheOnlyZii** [comment] 2020-05-10 16:19
> What sources are the ones that are stuck? Does it progress after some time?

in my experience it happens on multiple sources if i follow the example above MangaA was from webtoons then i remove mangaA from the librarry and it stucked on mangaB instead which from MangaDex

and i had mine stuck for nearly over 5 hours now it stays on the same spot unless you cancel the update

**Comment by shashank-p** [comment] 2020-05-10 16:20
I just did some things came to conclusion that button to global library update not working but when I do pull refresh from any category library I updated for that category.

**Comment by mra1412** [comment] 2020-05-10 18:00
This wasn't an issue on the previous version of the app that I used i.e. r2252.

**Comment by kai000bubbles** [comment] 2020-05-10 19:40
Yeah whatever they did in the last update yesterday screwed it up

**Comment by assmaster69** [comment] 2020-05-10 21:58
App version: 0.9.2-2289 (standard, 436253dd, 45)
Android version: 9 (SDK 28)
Android build ID: SW_S98507AE1_V009_M13_XM_C3D_USR
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: cereus
Device model: Redmi 6
Device product name: cereus

It is already clear that the update feature is not working. Gets stuck at the 7th title alphabetically (I'm nearly 30, but this is my first love; Mangadex) but I don't think the source is a problem. It gets stuck on it and after a while, the update process is terminated. It could no longer be initiated as well automatically or manually.

Another thing which I noticed is that the little blue icon which shows how many new chapters are left to read at the upper right hand side of each tile is also gone.

**Comment by arkon** [comment] 2020-05-10 22:00
I'm aware of the issue, it should be fixed by next week's preview build.

**Closed** 2020-05-17 14:30 UTC
Labels: bug
