### ISSUE TITLE
Missing Blue/Grey Bar When Viewer is set Right to Left

### ISSUE THREAD

**Issue by Kreemy** [inorichi/tachiyomi#544] opened 2016-11-22 22:39 UTC
![screenshot_20161122-223527](https://cloud.githubusercontent.com/assets/15200832/20544949/6a6998be-b104-11e6-9594-5e2155392af8.png)

Version: r964

**Comment by inorichi** [comment] 2016-12-05 22:13
I wasn't able to reproduce this issue. Device and OS?

**Comment by Kreemy** [comment] 2016-12-05 22:17
Nexus 6, Android 7.0

**Comment by inorichi** [comment] 2016-12-05 22:31
https://code.google.com/p/android/issues/detail?id=222234

It only happens in API 24 (7.0). In 7.1 it works as expected.

**Comment by Kreemy** [comment] 2016-12-05 22:46
Oh Right well the Nexus is supposedly getting 7.1 (guess i'll have to wait lol)
https://android-developers.blogspot.co.uk/2016/12/welcoming-android-711-nougat.html

**Comment by inorichi** [comment] 2016-12-10 11:28
Closing because this is a bug in the platform. However I'll follow that issue and try to fix it if any workaround is posted.

**Closed by inorichi** 2016-12-10 11:28 UTC
