### ISSUE TITLE
[Feature Request] Add comics tracking

### ISSUE THREAD

**Issue by nsnasa21** [inorichi/tachiyomi#2081] opened 2019-06-14 07:02 UTC
I would be nice if it were possible to track comic-book reading history like in Myanimelist/Ani-list. I have used "League of comic geeks". If there are better sites, then please add the tracking system for that site. I would be happy either way. Thank you.

**Comment by arkon** [comment] 2020-01-04 18:12
Duplicate of #2356

**Closed by arkon** 2020-01-04 18:12 UTC
