### ISSUE TITLE
[Bug] Webtoon viewer doesn't show images continuously on larger resolutions.

### ISSUE THREAD

**Issue by ahmubashshir** [inorichi/tachiyomi#2779] opened 2020-03-29 07:38 UTC
### Device information
* Tachiyomi version: r1949
* Android version: 7.1.1 (anbox)

## Steps to reproduce
1. Change Viewer to Webtoon
2. Second step

### Expected behavior
Image Should be shown continuously.

### Actual behavior
Each image has a large gap.

### Other details
Additional details and attachments.
![image](https://user-images.githubusercontent.com/24864366/77843781-45fca200-71c2-11ea-81c1-3b3f6009ae81.png)
![image](https://user-images.githubusercontent.com/24864366/77843798-5d3b8f80-71c2-11ea-8b7c-78b16a624714.png)

It works properly after changing window width to 640.

![image](https://user-images.githubusercontent.com/24864366/77844979-c6c09b80-71cc-11ea-88bf-5fa4629880f4.png)

**Comment by arkon** [comment] 2020-03-29 15:58
Duplicate of #2736.

**Closed** 2020-03-29 15:58 UTC
Labels: bug
