### ISSUE TITLE
[Bug] Add to Library snackbar doesn't respect User's default category

### ISSUE THREAD

**Issue by NikhilNarayana** [inorichi/tachiyomi#2828] opened 2020-04-06 11:26 UTC
### Device information
* Tachiyomi version: r1973 (985bb445)
* Android version: 8.1.0
* Device: OnePlus 5

## Steps to reproduce
1. Set default category to a custom category
2. Find a new manga on a source
3. Download a chapter without adding the manga
4. Add manga to library via snackbar

### Expected behavior
Manga is added to the User's default category.

### Actual behavior
Manga is added to the `Default` category.

**Comment by arkon** [comment] 2020-04-06 12:19
Duplicate of #2767

**Closed by arkon** 2020-04-06 12:19 UTC
Labels: bug
