### ISSUE TITLE
[Feature Request] Multiple Source Combining

### ISSUE THREAD

**Issue by Mathew20kdroid** [inorichi/tachiyomi#3934] opened 2020-10-12 18:33 UTC
## Some Comics have chapters missing frome some sources
Sometimes a comic source have chapters missing.....it might be the last few chapters or in between chapters

##Select multiple sources for same Comic Or Manga
Even if a source has some comic chapters missing.....then it can find the missing chapters from other sources and complete the comic and the overall experience.......

**Comment by scb261** [comment] 2020-10-12 18:41
Duplicate of #886 (won't be added)

**Closed** 2020-10-12 19:20 UTC
Labels: feature
