### ISSUE TITLE
[Feature Request] Border Crop apply to black borders

### ISSUE THREAD

**Issue by furiseto** [inorichi/tachiyomi#4031] opened 2020-11-13 09:59 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
Many manga uses black borders for many purposes (usually in "flashback" chapters). Applying Auto Border Crop for both white and black borders will keep the reading experience consistent and good for mobile devices with small screens.

## What/Requirements
(explain how this feature would behave)
Same as the current Border Crop feature, now extend to black borders

**Comment by scb261** [comment] 2020-11-13 11:03
Duplicate of #3290

**Closed** 2020-11-13 12:09 UTC
Labels: feature
