### ISSUE TITLE
Folder system in categories

### ISSUE THREAD

**Issue by shubham81** [inorichi/tachiyomi#2069] opened 2019-06-05 17:02 UTC
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
0.8.4
**Android version:**
6.0 Marshmello
**Issue/Request:**
Folder or Grouping manga together within the app

create a Grouping or folder systerm within the category  to sort related manga together at one place so they easy to find all at one place
It could help in Grouping the original story and the parody of that manga or any other alternetive publishing
 Or grouping different manga from same author

**Other details:**

**Comment by hXtreme** [comment] 2019-07-01 06:55
I feel like a similar idea was shot down but I can't seem to find it.

**Comment by arkon** [comment] 2020-08-01 21:28
Duplicate of #1803

**Closed by arkon** 2020-08-01 21:28 UTC
Labels: feature
