### ISSUE TITLE
Feature request : random comic

### ISSUE THREAD

**Issue by cojoMan** [inorichi/tachiyomi#1290] opened 2018-03-05 16:28 UTC
Request:

I have lots of comics added to my collection and I've even separated them into plenty of categories for better organisation. But they still start to pile no matter how many I read - some of you might relate to this...
Can we have a feature that would open up a random comic ?

options could include/be :
- random comic from all library
- random comic from current category (why I opened this thread for)
- preferential treatment in the chosen queue for comics in progress
- exclusion of in progress comics from the random queue 

Let me know what you think !
Thanks.

**Comment by inorichi** [comment] 2018-03-05 18:48
Duplicate of #1248

**Closed by inorichi** 2018-03-05 18:48 UTC
