### ISSUE TITLE
[Feature Request] Migrate all the manga from one source to another source

### ISSUE THREAD

**Issue by mariodac** [inorichi/tachiyomi#4051] opened 2020-11-21 14:01 UTC
If I'm not mistaken, in previous versions it was possible to migrate all manga from one source to another source, now the migration is done manually.
If you are mistaken about this feature, please add this feature in the next versions

## Why/User Benefit/User Problem
Migrating mango from one source to another is done manually one by one

## What/Requirements
Selective migration, choosing which sleeve and source to migrate from

**Comment by scb261** [comment] 2020-11-21 14:13
Duplicate of #1729

**Closed** 2020-11-21 14:26 UTC
Labels: feature
