### ISSUE TITLE
[Bug] Zooming out in Continuous vertical mode

### ISSUE THREAD

**Issue by mrsfn** [inorichi/tachiyomi#3971] opened 2020-10-25 17:13 UTC
## Device information
* Tachiyomi version: Preview r2796
* Android version: 8.1.0
* Device: Meizu 16

## Steps to reproduce
1. Use Continuous vertical mode for reading.
2. Zoom out a bit.
3. Return to normal (double tap).
4. Go to last page.

### Expected behavior
Last page/pages should be fully accessible.

### Actual behavior
I see only a part of last page and can't flip through it. 

## Other details
If I zoom out/in a bit I can read it just fine.
This problem was in previous builds too.

**Comment by arkon** [comment] 2020-10-25 17:14
Duplicate of #3555

**Closed by arkon** 2020-10-25 17:14 UTC
Labels: bug
