### ISSUE TITLE
[Feature Request] Show number of pages in each chapter on the Chapters listing tab

### ISSUE THREAD

**Issue by Kovaelin** [inorichi/tachiyomi#1307] opened 2018-03-14 14:17 UTC
**App version:** v0.7.0

**Issue/Request:** For people that might want to be able to see how many pages a chapter has before deciding to open/download it, it would be handy to show the page count on the Chapters listing tab.

Thanks.

**Comment by CarlosEsco** [comment] 2018-03-14 14:55
please close duplicate of #857

**Closed** 2018-03-14 14:58 UTC
