### ISSUE TITLE
[UI] Transition to Library

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2635] opened 2020-02-27 01:37 UTC
### User Problem
When transitioning to Library the screen looks a bit janky, which is kinda disturbing/irritating.

### What/Requirements
This jank can be smoothed out by adding an animation to slide out the category tabs from under the top bar.

_(When navigating away from Library the category tabs seems to be well animated already)_

**Comment by arkon** [comment] 2020-03-07 22:13
> This jank can be smoothed out by adding an animation to slide out the category tabs from under the top bar.

This already happens, but could potentially be choppy if the library loading is slow.

Marking this as a duplicate of #2632.

**Closed by arkon** 2020-03-07 22:13 UTC
Labels: feature
