### ISSUE TITLE
[Feature Request] autorecognition of webtoons

### ISSUE THREAD

**Issue by tomodachikezo** [inorichi/tachiyomi#2945] opened 2020-04-23 21:04 UTC
Why/User Benefit/User Problem
1. So we don't have to change the reading mode everytime we read a webtoon

Requirements 
1. When I click on a Webtoon, the system should automatically recognize it as a Webtoon and change the reading mode

**Comment by arkon** [comment] 2020-04-23 21:50
Duplicate of #2898

**Closed by arkon** 2020-04-23 21:50 UTC
Labels: feature
