### ISSUE TITLE
[Feature Request] Virtual Folders to group together Manga Spin-Offs and One Shots like Fairytail, FairyTail Zero etc.

### ISSUE THREAD

**Issue by monMusu** [inorichi/tachiyomi#3750] opened 2020-09-04 11:26 UTC
Hi guys, we all know that Tachiyomi allows us to create categories, yeah. And that's fine. But the problem arises when a Manga Title has spin-offs and one-shots. Like FairyTail, FairyTail Zero, FairyTail Gaiden.....etc etc. We can of course catogerise them. But that ends up being messy and too many Tabs. So, I was wondering, if a **Virtual Folders** could be added to Tachiyomi to simplify this problem? For those who do not get it, here is a mock-up. I believe it will go a long way in enhancing manga segregation and reading pleasure.
![ScreenMaster_20200904_160831](https://user-images.githubusercontent.com/70755549/92233897-baa0de80-eece-11ea-94a0-e0e8a6826cc2.jpg)

**Comment by arkon** [comment] 2020-09-04 12:46
Duplicate of #1803

**Closed by arkon** 2020-09-04 12:46 UTC
Labels: feature
