### ISSUE TITLE
[Feature Request] Total chapter number on covers for easier migration

### ISSUE THREAD

**Issue by rishabh-karmakar** [inorichi/tachiyomi#4050] opened 2020-11-21 12:30 UTC
## Why/User Benefit/User Problem
When migrating from one source to another, often it is checked whether that source has the same or more number of chapters. Currently to do so, we have to click on the source and then again at the manga name to see its chapters. It becomes quite hectic when having many many sources. 

## What/Requirements
Having a small number on top of covers like in library would help exponentially. When migrating, it could show the number on covers and clicking that, would perform the same. It would help a lot while stuck on a particular source and migrating.

**Comment by scb261** [comment] 2020-11-21 12:37
That would require extra network calls for each manga and can lead to ip ban from a source. Maybe do it only if one manga found by the search

**Comment by arkon** [comment] 2020-11-21 13:48
Basically a duplicate of #2867

**Closed by arkon** 2020-11-21 13:48 UTC
Labels: feature
