### ISSUE TITLE
Add title from PC

### ISSUE THREAD

**Issue by mishugashu** [inorichi/tachiyomi#804] opened 2017-05-19 17:05 UTC
This is probably a huge feature request, and maybe not even doable, but I often find new titles to read when I'm browsing reddit on my PC or something similar. It's a chore to find where I put my phone, open Tachiyomi, back out to the menu, go to the sources, type into the keyboard, and finally select the manga, when the manga is already up on my PC screen.

Could there be a way to maybe read bato.to's follows or something, and then Tachiyomi will automatically import items if they're not on the list?

**Comment by pervertkirito** [comment] 2017-05-20 12:44
i know that feels... that's why i use [ARC Welder](https://chrome.google.com/webstore/detail/arc-welder/pnhfdpadgclmlnbhiklnioojellehplg?hl=en)
But on latest release, I no longer able to export/create backup... so yea, you can still use older version tho

**Comment by inorichi** [comment] 2017-05-20 19:18
Duplicate of #250

**Closed by inorichi** 2017-05-20 19:18 UTC
