### ISSUE TITLE
Save cover image to make libraries

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#677] opened 2017-02-06 18:51 UTC
"Save cover image to make libraries more compatible"

Great free and simple app. The best for me to download / catalogue / update manga. Good work!
But I use another free app to read them: Challenger Comics Viewer. Many more options (specially the crop image ones). -> https://challengerviewer.wordpress.com/

Could it be possible for tachiyomi to save the cover file inside the main comic folder? So other apps like Challenger could pick and use the same cover for their library. It just have to use the same same name as the comic.

IE: "Dragon Ball" folder -> "\comics\kissmanga\Dragon Ball\Dragon Ball.jpg"

Thank you!

**Comment by inorichi** [comment] 2017-02-06 20:43
Tachiyomi doesn't need a cover in its downloads and implementing compatibility for every app an user wants to use is out of my scope. For example, why does it need to be named like the series? Another app may try to load a "cover.jpg" instead.

If you want to use this as a download-only app, you have to deal with its disadvantages. That said, making a script that automatically does this for every folder shouldn't be that hard.

**Comment by 444nonymous** [comment] 2017-02-07 11:39
I think you are right.

What is the "standard" for covers in this case? What do most comic reader programs (or the most popular ones)? You could implement what most apps do, and we (users) could ask the others to comply with that.

Nothing wrong with your app, it's just I use a lot the "crop"  feature in the reader, to reduce empty margins. Maybe you could add that feature to the reader too.

Thanks.

**Comment by j2ghz** [comment] 2017-02-07 12:48
crop: #219

**Comment by 444nonymous** [comment] 2017-02-07 14:51
If #219 is already implemented, it's not working for me. 

The reason why some apps require matching covers to comics is because the use cbr format, so comic1.cbr needs a comic1.jpg cover. So you get automatic matching covers this way. 

In the case of downloaders like Tachiyomi, all comic images are stored in subfolders, so you could leave a cover.jpg file in the main folder. I does not really hurt. You can name it  cover.jpg or comic_name.jpg, or whatever the "standard" is.

Some apps allow you to manually select a cover, but all of them will show first that image as cover. If not the first image of the first chapter will be used. Because the folder hierarchy in Tachiyomi and other downloaders, as long as you put the image in the root folder, It will be always used as cover.

So, I agree that Tachiyomi does not have to support any other app. But if you copy the cover image to the root folder of each manga you will allow all of them to use that cover. And if the user wnats to cip the folders ina cbz for more convenient storage, the cover is already there.

Thank you and please consider it since it's easy to do and helps a lot.

**Comment by j2ghz** [comment] 2017-02-07 15:04
It is not, I was just pointing out that your request

> Maybe you could add that (crop) feature to the reader too.

is a duplicate of request #219

**Comment by inorichi** [comment] 2017-02-07 15:58
> But if you copy the cover image to the root folder of each manga you will allow all of them to use that cover. And if the user wants to zip the folders in a cbz for more convenient storage, the cover is already there. (In fact you could even create an option for that, "zip / rar a downloaded series."

But storing a cover there takes more space, and most users won't need it. Sure it can be leveraged by reencoding the covers with lower size or quality, but still, I don't like having something unused by the app taking space (nor users that don't benefit from this feature).

Anyways, this is quite troublesome with the current implementation of the downloader. Storing a cover there is easy, but most probably won't play well with the implementation. Compressing to zip is something I had in mind once but it's also troublesome with how things work internally.

I don't see this being supported soon (or at all) and I don't want to spend much time rewriting internal parts just for this (not to mention I'm rather busy lately). Sorry.

**Comment by 444nonymous** [comment] 2017-02-07 16:15
A cover is just a few KB in app that downloads hundreds of MB. Just name it "cover" of whatever and set the reader to ignore it. I think it's a good feature to have the cover in available to archive, or be used by others apps, instead of just having it stored in a private database.

**Comment by wopian** [comment] 2017-02-07 16:40
>A cover is just a few KB in app that downloads hundreds of MB

But for me that file is totally useless, and I have >400 manga in my Tachiyomi library. Thats around 10MB or more of wasted space that will never be accessed.

**Comment by 444nonymous** [comment] 2017-02-07 18:03
It's hard for me to determine when people is really serious or just joking.

A guy who downloads GBs of 400 mangas complaining about 10MB for 400 covers?
In an age where storage is cheaper than ever, and everybody has 32-64GB cards for a few bucks?

I don't think I'm hardcore enough to post here, so I'll leave before it's too late. I don't mind the answer "this is my app and I'm not doing it, period". After all it's true and I'm tankful for the work done. 

But this "one cover image per manga is taking too much space" whining where the whole purpose of the app is to download thousands of images is just crazy.

**Comment by wopian** [comment] 2017-02-07 22:25
>It's hard for me to determine when people is really serious or just joking.

I'm being **really** serious. I'm the sort of person who strips their music library of covers and leaves only a single album cover file in the root of the album - which itself is converted to webP to become over half the size it was. All my local manga is in webP format, and i've begun going through my Tachiyomi downloads to do the same.

>A guy who downloads GBs of 400 mangas complaining about 10MB for 400 covers?

Just because I have 400 manga doesn't mean I have GBs of them downloaded - I only have about 8 GB of manga chapters downloaded on my phone, the rest are on my PC...zipped & stored as webP...

>In an age where storage is cheaper than ever, and everybody has 32-64GB cards for a few bucks?

Not all phones have SD cards. I'm stuck with a measily 64GB of internal storage, generally with less than a GB free. Saving as much space as possible matters for me.

>But this "one cover image per manga is taking too much space" whining where the whole purpose of the app is to download thousands of images is just crazy.

I wasn't whining - I just presented a use case of where it's inconvenient to implement a feature that's not used by the app at all, and in my case would take up more space than the app itself (7 MB). The only functionality it serves is for extreme edge-cases that doesn't benefit the vast majority of Tachiyomi users.

Edit: It'd actually take up over double the app size since it'd be in `Tachiyomi/downloads/manganame` and in the devices' cache. ¯\\\_(ツ)\_/¯

>What is the "standard" for covers in this case? What do most comic reader programs (or the most popular ones)? You could implement what most apps do.

Went ahead and installed most of top 10 reader apps from searching "comic reader" and "manga reader" on Google Play Store to see how they handle their local files and if they support a cover file, either named `cover` or matching a folder.

None of the manga apps on the store supported this - with almost all of these not actually exposing their downloaded files.

Perfect Viewer is the only one that successfully used a supplied image instead of the first page of all the comic apps - although ACR may have supported it, but I couldn't get it to find anything after 10 minutes of attempting with various comics, file extensions and names. Of course there's probably a decent chunk of comic reader apps out there not on the play store that probably support it though - but this was already pretty time consuming itself.

| App | Format / Notes | Cover Image
|-|-|-
Tachiyomi | `app/downloads/source/manganame/chapter/page.ext` | No (source)
Tachiyomi | `app/local/manganame/chapter/page.ext` | No (page 1)
Manga Rock | Not in user data| N/A
Crunchyroll | Paid / Not in user data | N/A
Manga Bird | `app/source/manganame/chapter_page.ext` | No (source)
.Manga | Can't download / Online only | N/A
Manga Reader | Not in user data | N/A
Manga Searcher | Not in user data | N/A
comiXology | Paid / Not in user data | N/A
Comic Screen | Local comic reader only / Tested with `manganame/chapter.cbz`, plus as `.cbr`, `.zip` & as a `folder | No (page 1)
Astonishing Comic Reader | Same as Comic Screen / Couldn't get it to detect any comics | N/A
Perfect Viewer | Same as Comic Screen | Yes (page 1 fallback)
Comics Reader: CBR, CBZ, PDF | Same as Comic Screen| No (page 1)
Bubble | Same as Comic Screen | No (page 1)

**Comment by 444nonymous** [comment] 2017-02-08 08:42
All the apps make use of the cover file. The use the first image file in the first folder as cover. Same for cbr / cbz files. The first image is listed as cover. Tachiyomi should store its own cover there, in the root folder of each manga (if downloaded), so it would always be listed first in all apps / programs, in all file formats.

But anyway, I'm loosing my time. I'm not arguing with a guy obsessed with downloading, storing and reading 400 comics in a device without sdcard support and only 64GB of internal memory. Good luck with that. If your storage space were as important as you say, you  would get a proper device and stop complaining about 10MB.

**Comment by Rait0** [comment] 2017-02-08 23:48
I also support having the cover files downloaded as well. Periodically I'd lose all of my cover files for reasons I do not know (my internal has over 5gb of space left and my sdcard has 16gb left). I've also seen some people complain about this.

**Comment by inorichi** [comment] 2017-02-13 18:42
For the time being covers won't be created there.

@Rait0 this change wouldn't fix that issue, and it has been resolved already, see #647.

**Closed by inorichi** 2017-02-13 18:42 UTC
