### ISSUE TITLE
japscan source doesn't work

### ISSUE THREAD

**Issue by DiogoVieiraFerreira** [inorichi/tachiyomi#2558] opened 2020-02-01 14:19 UTC
### Device information
* Tachiyomi version: 0.8.4
* Android version: 10

## Steps to reproduce
1. open menu
2. go in catalog
3. try to look source with recent button

### Expected behavior
new chapters and pictures are visible and we can search data

### Actual behavior
chapters doesn't load and pictures of scan show cross. 

### Other details
we can see new chapters in blue icon on the top of picture, but impossible to open scan and chapters

**Comment by happywillow0** [comment] 2020-02-01 14:30
What extension version are you running?

Do you have a example of which manga and chapter you are having issues with?

What is your location? 

I'm testing on a USA connection and the mangas I'm testing load fine.

**Comment by DiogoVieiraFerreira** [comment] 2020-02-01 14:43
i use japscan 1.214

i try to open "Tales of demons and god" and i have retry button, same with haikyuu. 

i'm in switzerland

**Comment by DiogoVieiraFerreira** [comment] 2020-02-01 14:49
I have try to uninstall and reinstall source and i can look scans, but the home page of source always doesn't work
![Screenshot_20200201_154902_eu kanade tachiyomi](https://user-images.githubusercontent.com/47444284/73594020-6d105d80-450a-11ea-9187-edcdbfc582e7.jpg)

**Comment by happywillow0** [comment] 2020-02-01 15:05
What phone and system are you running? Do you have a custom rom?

What happens when you load the page via webview? Does it pass cloudflare and then load completely?

Tachiyomi 0.8.4 doesn't have the latest cloudflare bypass so that may be an issue. You can try the dev version.

**Comment by arkon** [comment] 2020-02-01 15:07
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2164

**Closed by arkon** 2020-02-01 15:07 UTC
Labels: bug

**Comment by DiogoVieiraFerreira** [comment] 2020-02-01 15:29
i have try with dev version and is work. 
my phone is huawei mate 20 pro

**Comment by supercop** [comment] 2020-03-11 12:18
Hello! The connection to Japscan doesn't work with the version 0.8.5...
I'm in Samsung Android E40.

**Comment by DiogoVieiraFerreira** [comment] 2020-03-11 18:31
Hello a new update of the application unlock an update for japscan extension and is work now !

**Comment by supercop** [comment] 2020-03-11 22:50
Thanks a lot, it works now for the download, but the scans doesn't load for just reading i have the feeling...
