### ISSUE TITLE
[Feature Request] disable crop borders for webtoon only

### ISSUE THREAD

**Issue by Svenare** [inorichi/tachiyomi#972] opened 2017-09-10 08:44 UTC
Webtoons don't look good with crop borders on, but disabling it turns it off for manga as well

**Comment by NoodleMage** [comment] 2017-09-10 08:48
Duplicate of #943.

**Comment by NoodleMage** [comment] 2017-09-10 08:49
Lol that's a weird way to open an issue :;)

**Comment by 444nonymous** [comment] 2017-09-11 05:13
No!. Crop for webtoon looks good and is a wanted feature by a lot of us.

https://github.com/inorichi/tachiyomi/issues/904

**Comment by NoodleMage** [comment] 2017-09-11 06:21
His request is to turn it off individually, not to remove it.

**Comment by inorichi** [comment] 2017-09-11 06:24
Me: 
![](https://user-images.githubusercontent.com/3521738/30260956-8996cd5e-96ca-11e7-909e-a572bbd6b605.png)

 So... two separate options and the setting from the reader depends on the current viewer.

**Comment by j2ghz** [comment] 2017-09-11 07:16
Would it be easier to make it manga-dependent?

**Comment by inorichi** [comment] 2017-09-11 08:04
Not really, the other way around.

**Comment by 444nonymous** [comment] 2017-09-11 09:58
Well, he can disable crop if he is using webtoon.

He already has to go to options to change webtoon to other thing. So once there he can also check the crop option.

I don't really understand his problem. If he sticks to webtoon with no crop borders, he does not need to change anything.

**Comment by bbtora** [comment] 2017-10-31 08:26
I would like to know the status with this issue too.
I am also currently having problem viewing webtoons with crop borders on, as it distorts the image alignment.
I don't know why not anyone else is having a problem with this. Crop borders work great with normal manga but it really is a bad choice with webtoons as they have intended white spaces with laid out panels.
And switching this option again and again is really annoying.

**Closed** 2018-04-27 14:54 UTC
Labels: feature

**Comment by RED-404** [comment] 2020-07-16 14:45
Re-open??? https://github.com/inorichi/tachiyomi/commit/1920568057eee522a7e77f523a5ebe322ee43249
