### ISSUE TITLE
[Feature Request] Update to Source migration

### ISSUE THREAD

**Issue by mrsfn** [inorichi/tachiyomi#2950] opened 2020-04-24 13:35 UTC
It is a very useful tool to use if a manga source goes down, but you have to move every manga one by one. Which is very inconvenient, because if you have a lot of following manga it takes forever to migrate.
It would be good if there was on option, where you select all your manga (from one source), then to what source you want to migrate. Then there will be shown a list of manga that failed to migrate.
Appreciate your hard work, thanks.

**Comment by arkon** [comment] 2020-04-24 13:42
Duplicate of #2948 1729

**Closed by arkon** 2020-04-24 13:42 UTC
Labels: feature
