### ISSUE TITLE
Loading Library updates takes forever

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#1082] opened 2017-11-25 03:56 UTC
I only have 30 mangas but it takes like 20-30 seconds to load Library updates. I thought it was broken.

It takes 1 second for the app ta launch and show "My library" (3 with download badges enabled).

Maybe you could implement some cache for the app to make it faster. Thanks.

Related to https://github.com/inorichi/tachiyomi/issues/1078

**Comment by CarlosEsco** [comment] 2017-11-25 12:41
Are you saving to a SD card or something? Pixel 2 with badges is less than second with over 100 manga.  Similar with my Nexus 6

**Comment by cd0rw0** [comment] 2017-11-25 13:18
@CarlosEsco 
for me yes, there is delay wt download badge
i did small testing wt 1+5 & Samsung tab A 2016  (download location in Sd card) 
both identical settings & both have 200 manga's in my library (downloaded 20+)
from my testing 

1+5 (latest tachiyomi)
without badge - instant 
with download badge - 6 second

S-Tab (build from #960 Pull Request) 
without badge - instant 
with download badge - 4 second

changes you made in #960 have some effect in load time bcos slow s-tab wt sd card can load faster then 1+5

**Comment by CarlosEsco** [comment] 2017-11-25 13:31
@cd0rw0 few things.
1.  Can you try not on a SD card and see what your times are.
2.  What class SD card you using?
3.  I can potentially look into caching the badge however can't guarantee anything, this was the reason inorichi wanted the badges as option in first place

**Comment by 444nonymous** [comment] 2017-11-25 13:44
@CarlosEsco My SD card is fine.

This is what I think happens: If I select a manga from "my library", it takes 0.5-2 seconds to load the chapter list. Since the last update it feels like "library updates" has to load all chapters for my 30 mangas = 30 seconds. 

Also there is the problem of going back from a manga to "my library" when badges enabled, it has to check them all every time. Wouldn't it be better to keep some info static in the database and only update it when something changes?

**Comment by 444nonymous** [comment] 2017-11-25 13:47
I also tried to clear and refresh everything, and to play with some options. It's just painfully slow.

**Comment by CarlosEsco** [comment] 2017-11-25 13:57
@444nonymous   Do you have any of these issues when download badges is not showing?

**Comment by inorichi** [comment] 2017-11-25 14:14
The real problem is the storage access framework, which is garbage, and is only used when you select a custom directory (because there's no other way). 

I agree about the cache for downloads, but there should be an invalidation by time, maybe 30 minutes, as we don't have control over when the files are deleted and the app can be running in background for days. It won't help with the first load though.

**Comment by cd0rw0** [comment] 2017-11-25 14:29
@CarlosEsco 
im using 2 dif ver of tachiyomi in 2 devices
in 1+5 i use latest ver. (btw 1+5 have no sd card) n since its use UFS 2.1 its should faster then sd card tablet 

in tablet i use 960 pull (wt all tab), (32 gb class 10 sd card)

**Comment by CarlosEsco** [comment] 2017-11-26 15:35
@444nonymous @cd0rw0 

Can you try this dev build?  Let me know.  I still need to add pull to refresh to force download badge update but this should be a little faster after the initial run.

https://www.dropbox.com/s/xkvstixmdypzjsk/app-dev-debug.apk?dl=0

**Comment by 444nonymous** [comment] 2017-11-26 16:24
@CarlosEsco.

Improvement. 
1. Loading the app with download badges on takes 2 seconds. Before 3. No badges = 1.
2. Going from a selected manga back to my library is instant now. No difference with no badges.

Same:
3. Libray updates still takes forever to load. It does not matter the badge setting.

**Comment by CarlosEsco** [comment] 2017-11-26 16:32
@444nonymous   for 3 are you talking about when you swipe to refresh the library?   If so how many manga do you?

**Comment by mrskizzex** [comment] 2017-11-26 16:38
@CarlosEsco I think he means "Library updates" tab in the left menu.

**Comment by CarlosEsco** [comment] 2017-11-26 16:48
Oh ok I've been reading it wrong there are 2 issue being discussed.

Issue 1 - Library Updates.  I will look into this separately after i finish looking into issue 2. 

Issue 2 -  download Badge caching - this is what I am addressing currently and will move this into the correct issue 1078.  this is also what @cd0rw0  was talking about when he came into this issue thread.

**Comment by 444nonymous** [comment] 2017-11-27 11:23
@CarlosEsco

What you are fixing is the badges problem from this other thread-> https://github.com/inorichi/tachiyomi/issues/1078

What needs to be fixed here is how slow the "Library updates" screen is loading (not "my library" screen being updated). It takes so long because it seems it has to read all manga chapters of all mangas and then determine what's new. 

What if you created a new specific chapter list for  "Library updates"? It would work like any single manga chapter list. And individual manga takes 0.5-2 seconds to load a full chapter list. An individual "Library updates" chapter list would take the same time.

I think "Library updates" only uses entries from 1 week ago, so It can be updated (also purging "expired") when new chapters are added after a full library refresh. It should not be a big chapter list and it would load instantly.

**Comment by inorichi** [comment] 2017-11-27 12:07
I'm working on a download cache that should improve loading speed in both screens. 

@444nonymous 
The slowdown in library updates should also be caused by the downloads check. Can you try temporarily setting the downloads dir to the first one shown in the setting?

@CarlosEsco
I took a quick look to the PR. I don't want to make the database downloads aware until totally necessary, so we'll first try with the download cache.

**Comment by inorichi** [comment] 2017-11-28 00:29
bff329a should have improved loading times.

**Comment by inorichi** [comment] 2017-11-29 18:16
Can this be closed now?

**Comment by 444nonymous** [comment] 2017-11-29 18:36
So, this is what happens in v0.6.5.

"Library updates" tab takes forever to load as usual, maybe even more time. But: 
1. only the fisrt time you use it. You can change to My lirabry and back instantly.
2. only if you don't close the app. Every time the app is launched it takes foerever again.

About the badges. Similar problem:
1. When i tested the fix, id did not take too long to load "My library" after closing the app. Now it takes much more time than loading "Library updates" (like +1.5-2 minutes).
2. Then it works fine, until you close the app.

So the problem is that the cache works, but it should stored to be loaded fast. I hope that the problem now is that the cache is created in memory every single time the app is run. Also it wold not hurt to have an icon moving to show the app is working and it did not halt.

Thanks

It would no hurt to

**Comment by inorichi** [comment] 2017-11-29 18:43
How many directories do you have? It'd help me to recreate a similar scenario.

I think I can optimize a bit the performance of SAF by forking a library. I'll try later. If you can afford writing to one of the predefined directories, use them. Those are the only ones where SAF is not a requirement.

**Comment by 444nonymous** [comment] 2017-11-29 18:49
31 mangas, 4694 chapters (= 4694 directories), +100.000 individual jpg images. Stored in SD card.

You can recreate a similar scenario pretty easy. Just pick 20-30 mangas and download more than 100 chapters each.

**Comment by 444nonymous** [comment] 2017-11-29 18:51
And also remeber this -> https://github.com/inorichi/tachiyomi/issues/918

**Comment by inorichi** [comment] 2017-11-29 21:27
[tachiyomi-listfilestest.apk.zip](https://github.com/inorichi/tachiyomi/files/1515594/tachiyomi-listfilestest.apk.zip)

How does this apk perform?

**Comment by 444nonymous** [comment] 2017-11-30 05:22
Can't install. "App Not installed" error.

**Comment by inorichi** [comment] 2017-11-30 07:43
https://a.uguu.se/LZKuWsa1FgKn_tachiyomi-listfilestest.apk

Uploaded as apk on a temporary file hosting. It should work now.

**Comment by 444nonymous** [comment] 2017-11-30 12:04
I had renamed the zip to apk. And android tries to install it but I get the error.

**Comment by inorichi** [comment] 2017-11-30 12:08
Have you tried the latter anyways? It's a different compilation.

**Comment by 444nonymous** [comment] 2017-11-30 13:08
Las one works.

It loads My Library fast (1-2 seconds) when launching the app. Then it also loads Libray Updates instantly.

Download badges are not shown even with the setting checked. So this is not working

**Comment by inorichi** [comment] 2017-11-30 13:43
I think your downloads directory is wrong/unset. The changes were very little and they work for me. They saved creating a cursor when querying the directory name (it should have gone from ~5000 cursors to ~40).

Also, I don't think the ZIP compression would help here. I don't even list the contents of the chapters.

**Comment by 444nonymous** [comment] 2017-11-30 14:02
It's working: My Library & Libray Updates (both load fast)

Not wroking: Badges (not showing).

**Comment by inorichi** [comment] 2017-11-30 14:03
In that case, the downloaded filter should not work, nor the "DOWNLOADED" text in the chapter list.

**Comment by 444nonymous** [comment] 2017-11-30 14:42
True, whatever it means.

**Comment by 444nonymous** [comment] 2017-11-30 15:59
If you are going to fix "download badges" so it loads that fast, maybe there is no reason to keep a setting a to show / hide them anymore. New chapters badge does not have that setting.

**Comment by inorichi** [comment] 2017-12-03 12:16
FYI, the change that improved the loading times is live now. Could you try again and confirm if this can be closed?

**Comment by 444nonymous** [comment] 2017-12-03 17:27
I tested the latest dev build. I works fine and loads fast all tabs.

Download badges do not work. Also the setting to show them is still there. Maybe you could just make remove it and show download badges by default like new chapters badges are shown.

Thanks

**Comment by inorichi** [comment] 2018-04-07 19:11
The described issue was already fixed some months ago. I forgot to close it.

**Closed by inorichi** 2018-04-07 19:11 UTC
Labels: bug
