### ISSUE TITLE
Problem in vertical reading 

### ISSUE THREAD

**Issue by LeitHunt** [inorichi/tachiyomi#778] opened 2017-05-02 08:59 UTC
Please make vertical reading of manga smooth means page will stop on any position so that I can keep my eyes at same level and move page up with my thumb reading panels horizontally.In present version you can only see 1 page at a time so you need to read from top right to all the way bottom left.

There's webtoon mode but in that problem is while zooming, when you zoom in your page goes below the previous page.So if by mistake if I zoom while the page break is at middle of screen ""only half screen is useful for reading zoom page as half screen is covered by previous page"".
So this is vary tedious in reading in webtoon mode and if I read on small screen in landscape mode the reading become even terrible in zooming.

So can you please make vertical reading smooth with proper zooming 
Or
 a webtoon mode in which page will not go under previous page instead it will push the previous page up? 
Thank you very much Tachiyomi developers :D.

**Comment by inorichi** [comment] 2017-05-14 18:01
Vertical reader won't be changed, it's based on a ViewPager and that's how it works. Zooming all the pages in webtoon is a duplicate of #745, which will probably take a while.

**Closed by inorichi** 2017-05-14 18:01 UTC
