### ISSUE TITLE
[Feature Request] MAL sync using Google account

### ISSUE THREAD

**Issue by FedNat** [inorichi/tachiyomi#3665] opened 2020-08-13 06:41 UTC
## Why/User Benefit/User Problem
To allow MAL user that connect throug Google accounts to sync theri reading lists

## What/Requirements
Allow to login to MAL using google accounts instead of MAL username and password

**Comment by arkon** [comment] 2020-08-13 12:19
Duplicate of #3215

**Closed by arkon** 2020-08-13 12:19 UTC
Labels: feature
