### ISSUE TITLE
[Feature Request] <A large History Section>

### ISSUE THREAD

**Issue by renzaluar** [inorichi/tachiyomi#3242] opened 2020-05-26 15:19 UTC
If I am not mistaken, there can be shown 25 mangas HISTORY in the app at a time, after removing a manga, I can see the older manga started to show up among the 25. My question is, is it possible to show a lot more manga at a time in the history section without removing any?
Thanks for your hard work.

**Comment by arkon** [comment] 2020-05-26 15:40
Duplicate of #2877, I guess

**Closed by arkon** 2020-05-26 15:40 UTC
Labels: feature
