### ISSUE TITLE
[Feature Request] Allow for manga to have titles in both english and japanese

### ISSUE THREAD

**Issue by MinitotheMax1** [inorichi/tachiyomi#2815] opened 2020-04-03 02:53 UTC
### Why/User Benefit/User Problem
While searching for manga in your library, you have to search the exact title that its recorded as, otherwise it will not show up in the search results. Sometimes, if your getting back into a manga that you have not read in a while or remember an alternate title, this can become an inconvenience especially if you have a very large library.

### What/Requirements
I have basically no technical knowledge but I imagine it would basically act like this. When adding manga from a catalogue, it automatically adds multiple titles if there are multiple present in the catalogue which is the case for most manga on MangaDex.

An example would be the manga titled Shuumatsu no Valkyrie. On MangaDex, these are all the alternate titles:
![Screenshot_20200402-224719_Tachiyomi](https://user-images.githubusercontent.com/45908027/78318986-23f17f80-7534-11ea-99bd-97bbf9a6ba5f.jpg)

But if I were to search for this manga using the title Record of Ragnarok which is more familiar to me, I would not find it when I search my library.
![Screenshot_20200402-225101_Tachiyomi](https://user-images.githubusercontent.com/45908027/78319115-73d04680-7534-11ea-8912-4b5f025327dc.jpg)

I know you can change the title by editing the manga information, but if you have hundreds of manga it can be quite a hassle. Even though this is such a small issue, it would make use of the app more seamless.

**Comment by CarlosEsco** [comment] 2020-04-03 04:14
Fyi none of the alternative titles are returned in mangadex api

**Comment by MinitotheMax1** [comment] 2020-04-03 08:30
Ohh I see. Is there any way for a feature like this to be introduced later
on or is it not possible? Thank you for your help and quick response.

**Comment by CarlosEsco** [comment] 2020-04-03 10:35
If their api changes then it would be possible but it still would need main app changes to support it

**Comment by arkon** [comment] 2020-08-01 21:42
Duplicate of #2190

**Closed by arkon** 2020-08-01 21:42 UTC
Labels: feature
