### ISSUE TITLE
the play button

### ISSUE THREAD

**Issue by 7sevenseven** [inorichi/tachiyomi#1971] opened 2019-04-13 08:50 UTC
Add an option to the play button in the settings.If someone chooses this option, when they use the button, they go to the page where they last viewed.
It can be very useful.
![Screenshot_20190413-160616](https://user-images.githubusercontent.com/49519653/56077217-1e26f980-5e0c-11e9-99a0-911fe52627a5.png)

**Comment by null-dev** [comment] 2019-04-13 09:18
This should already be the default behaviour of the play button.

**Comment by 7sevenseven** [comment] 2019-04-13 10:13
> This should already be the default behaviour of the play button.

My English is not very good. Please forgive me if I say something rude.
The default behaviour of the play button is to read the first unread.What I mean is to see where I saw a manga last time.These two things are different.
Like this image,when I use the play button,I hope it can start from the chapter10,page3.
And can you make this app to automatically record where you see and mark it clearly like this image.Of course,the form of the mark doesn't matter. I just need a prominent automatic mark.
![Screenshot_20190413-174442](https://user-images.githubusercontent.com/49519653/56078143-39e3cd00-5e17-11e9-86e5-24f538f9115a.png)

**Comment by AriaMoradi** [comment] 2019-10-19 13:40
is there any plans to implement this feature?
I suggest adding an item in settings->Reader menu for toggling the behavior of this button.

**Comment by arkon** [comment] 2020-01-04 20:41
Duplicate of #1399

**Closed by arkon** 2020-01-04 20:41 UTC
