### ISSUE TITLE
[Feature Request] Shuffle library

### ISSUE THREAD

**Issue by leonebachega** [inorichi/tachiyomi#2374] opened 2019-12-20 16:57 UTC
### Why/User Benefit/User Problem
A way to shuffle/randomize a big library, useful for when an user wants to read something but has too many options to make a decision and would like a comic/manga to be picked at a random for them.

### What/Requirements
A simple option among the others to organize the list (alphabetical, recently added, etc).  Just a Shuffle or Random option. Or perhaps just a "random"/"feeling lucky" button.

**Comment by arkon** [comment] 2020-01-19 22:32
Duplicate of #1248

**Closed by arkon** 2020-01-19 22:32 UTC
Labels: feature
