### ISSUE TITLE
[ISSUE] KissManga Download Chapters

### ISSUE THREAD

**Issue by Rait0** [inorichi/tachiyomi#637] opened 2017-01-18 09:26 UTC
http://imgur.com/a/YZTCA
I've experienced this a couple of times. Some manga doesn't complete downloading at kissanime. See image. I've tried restarting download, deleting and redownloading but nothing works. I know I can just download it from other sources (I really love kissanime and batoto but batoto has limited library) but still I wanna know if this is just me or really an issue with everyone.

This is my first ever post. I just want to let you know that this is imho the best reader for android. Great work and keep it up! :) ... we will keep on supporting you.

Version: v0.4.2
Android 6.0

**Comment by NoodleMage** [comment] 2017-01-18 09:43
I did some research on this manwha for you ( ͡° ͜ʖ ͡°).

It seems to error on http://kissmanga.com/Manga/Sweet-Guy/Chapter-001?id=310085#10. The rest of the files are downloaded but placed in Sweet Guy Chapter 001_tmp. a workaround for now is removing the tmp with a file explorer.

**Comment by Rait0** [comment] 2017-01-18 10:05
Woah man that was fast! XD
I did what you said. And it did fix the problem. It is now showing as downloaded. Chapter 01 is 47/48 and Chapter 02 is 46/49 in my screenshot. I checked the folders and it did download only 47 for ch01 and 46 for ch02. It doesn't  look that there's a page missing so I guess it did download successfully in the first place but the app thought they were 48 and 49 pages but there's no more page to download  so it just output an error?

**Comment by Rait0** [comment] 2017-01-18 10:26
Ahhh... sorrryyy... Forget what I said above... some files are really not downloaded. In chapter 01 page 10 isn't downloaded. I checked kissanime and it doesn't load that page. Guess it really was a problem on their side not on your app :)
I'll just look on other sources... Thank you very much!

**Comment by NoodleMage** [comment] 2017-01-18 14:29
I want to keep this one open, because it seems that something goes wrong. 

@inorichi if this is a known issue please close this one again ;)

**Comment by inorichi** [comment] 2017-01-18 17:52
Working as intended if the file isn't available in the browser either.

**Closed by inorichi** 2017-01-18 17:52 UTC
Labels: bug
