### ISSUE TITLE
[Feature Request] Double tap to bring to top of list.

### ISSUE THREAD

**Issue by Gamingappleh** [inorichi/tachiyomi#2992] opened 2020-04-30 10:31 UTC
The double tap on the library ion to bring to top of the list or two quick taps.(or double tap the library name is also alright.)

### Why/User Benefit/User Problem

I believe it can make going to the top of the list faster than before.

### What/Requirements
Similar to other apps there may be some problems differentiating between the one tap for the menu or two taps to the top.
(The menu in the Dev build may cause issues.)

**Comment by arkon** [comment] 2020-08-01 22:18
Duplicate of #2328

**Closed by arkon** 2020-08-01 22:18 UTC
Labels: feature
