### ISSUE TITLE
Can download extensions but there is en error while analyzing package when instaling

### ISSUE THREAD

**Issue by WH1T3No1SE** [inorichi/tachiyomi#1934] opened 2019-03-25 10:37 UTC
**App version:**
8.1 stable & r1474
**Android version:**
7.0
**Issue/Request:**
Can download extensions but there is en error while analyzing package when instaling
**Steps to reproduce (if applicable)**

 1. Try to download extension
 2. Extension Downloads
 3. Android opens installer and gives error message about error while analyzing package

**Other details:**
I do not use VPN or Adblock as described in #faq on Discord.
I tried changing default browser to see if thats the reason but it did not change anything.
Downloading and installing extensions directly from github works fine.

**Comment by inorichi** [comment] 2019-03-27 19:19
Can you elaborate on "error while analyzing package when instaling"? Does it say just that?

There's no information online when searching for that, only related to parsing the package.

**Comment by WH1T3No1SE** [comment] 2019-03-27 20:24
Tachiyomi after downloading extensions redirects to installer and before even installer screen is shown i have a message box with "Podczas analizowania pakietu wystąpił problem" which translates from Polish to English as "There was an error while analyzing package" and only option to this message box is "ok"

**Comment by WH1T3No1SE** [comment] 2019-03-27 20:25
When i press "ok" it just comes back to extensions screen in tachiyomi

**Comment by inorichi** [comment] 2019-03-27 21:24
Please set your device language to English temporarily and copy the error shown here.

**Comment by AmineI** [comment] 2019-03-27 21:32
Sound like this error message (got the example screenshot from google to show it there) ![image](https://user-images.githubusercontent.com/15179425/55113536-d4d26c80-50df-11e9-8f6e-d8fb4ec95b75.png)

Already happened to me for corrupted downloads, redownloading the apk I was installing usually did the trick.

**Comment by AmineI** [comment] 2019-03-27 21:37
I can picture the error message, translations use the word "analyze" in other languages as there's no easy translation of "parse", but in English I'd say it's the one you mentioned above related to parsing the package. I'll do a quick check on my device as I have a corrupt apk laying in my download folder

**Comment by AmineI** [comment] 2019-03-27 21:43
Can confirm that my "There was a problem parsing the package" error became his "Podczas analizowania pakietu wystąpił problem" when switching my device to Polish. It's a super generic error message that happened to me a few times, when an APK download was corrupt. Redownloading usually did the trick, not sure how it can happen all the time for all the extensions though.

**Comment by WH1T3No1SE** [comment] 2019-03-27 21:44
After changing system language to English it does say parsing, why does it corrupt the download though then? I can download and install it from github repo manually without an issue, i did not change my default browser from chrome to anything else or do not use any "faster downloaders" than default one, my phone isnt even rooted.

**Comment by WH1T3No1SE** [comment] 2019-03-27 21:45
It's happening to me even if i update or reinstall tachiyomi, on both stable and dev versions.

**Comment by inorichi** [comment] 2019-03-27 21:50
It's probably the DownloadManager not finding the apk for some reason. There's an SDK check and devices running N or later can directly open the apk without issues. Are you running a custom ROM or something? Which device is it?

**Comment by WH1T3No1SE** [comment] 2019-03-27 21:52
I'm running same android that was put on my phone in the factory.
Android 7.0
Sony Experia L1 G3311

**Comment by WH1T3No1SE** [comment] 2019-03-27 22:00
It's only app I'm experiencing this problem with if i make any other app download a apk file it can be installed without a problem (for example from direct download link for latest dev version in #announcements on discord)

**Comment by arkon** [comment] 2019-03-27 22:30
Can you try downloading one directly from GitHub? https://github.com/inorichi/tachiyomi-extensions/tree/repo/apk

**Comment by WH1T3No1SE** [comment] 2019-03-27 22:31
yes i have mentioned before that downloading and installing them manually works without a problem, only downloading through tachiyomi doesn't work

**Comment by AmineI** [comment] 2019-03-27 22:31
> Can you try downloading one directly from GitHub? https://github.com/inorichi/tachiyomi-extensions/tree/repo/apk

Said he could though, last line of the first post
>Downloading and installing extensions directly from github works fine.

Assumed he meant downloading from the GitHub repo you just linked

**Comment by arkon** [comment] 2019-03-27 22:32
Whoops, my bad. :P

**Comment by AIsage** [comment] 2020-02-17 19:11
I'm having this problem with Sony Xperia L1 G3312, Android 7.0, Tachiyomi 0.8.4.
.
Any solution yet? Is it because of Sony having done something weird with Xperia L1 series?

**Comment by arkon** [comment] 2020-04-09 19:28
Duplicate of #2107

**Closed by arkon** 2020-04-09 19:28 UTC
