### ISSUE TITLE
Please put a default chapter sorting in the settings... 

### ISSUE THREAD

**Issue by IamHeinous** [inorichi/tachiyomi#1080] opened 2017-11-23 19:55 UTC
Can you put an option inside setting to apply sorting chapters either up or down for all Manga?  

It should be Chapters inside a manga not the global sorting we already have. 

![screenshot_20171124-035822_1](https://user-images.githubusercontent.com/20397950/33187447-b2e7b48e-d0cc-11e7-8576-7ce3551b41c4.jpg)

**Comment by wopian** [comment] 2017-11-24 00:06
Duplicate of https://github.com/inorichi/tachiyomi/issues/484

**Closed** 2017-11-24 07:14 UTC
