### ISSUE TITLE
[Feature Request] Delete Downloaded From Library and Visual Requests

### ISSUE THREAD

**Issue by kenjiehimura96** [inorichi/tachiyomi#1892] opened 2019-03-16 16:24 UTC
**App version:** r1469

**Issue/Request:**
1. Petition to add delete downloaded chapters from library. As of now you can do this by long pressing the manga then pressing delete and checking delete downloaded but I kind of want a feature to **delete the downloads only and not remove it from the library**.

The work around is somewhat tedious, I have to go inside the manga chapters, long press one, press select all, then delete. Although workable it is tiresome when you repeat this for like 10 times in a row (since I download and delete large batches).

2. Rounded corners on manga covers and badges.

3. Use default system font for manga titles, title font does not follow system font changes. The cover titles have somewhat different font from what I changed from, it's really noticeable when you have a custom system font and it does not match.

**Other details:**
I wish the delete function from library would be implemented, I used to the that a lot when I was using Manga Rock. Thing is I downloaded like 8 ongoing manga with something like 10-14 chapters each so it is really tiresome to do the chapter deletion thingy.

Although I believe that the visual request will not be top priority I would be grateful if ever it could be implemented (or given a toggle mode). I could understand if the font was used because of space and character/ glyph issues.

**Comment by Jendrej** [comment] 2019-03-16 16:38
Ad.1: you can delete the downloads using a file manager.

**Comment by kenjiehimura96** [comment] 2019-03-16 17:02
Yeah, I guess that works better than selecting chapters. Did that once, totally forgot about it.

**Comment by CarlosEsco** [comment] 2019-03-16 17:13
Also for number 1. You can just go into manga swipe to the info page it's a little faster

**Comment by arkon** [comment] 2020-04-26 22:47
Duplicate of #156

**Closed by arkon** 2020-04-26 22:47 UTC
