### ISSUE TITLE
Sort by release date of the latest chapter

### ISSUE THREAD

**Issue by Infinine** [inorichi/tachiyomi#1666] opened 2018-10-16 19:17 UTC
App version: 0.8.0

Request: Add a sort option

Other details: Currently the app sorts them by the order they are added into the library if you use the "last updated" feature (at least from my understanding).

If possible, could you please add an option to sort the manga by the upload-date of the latest chapter.

**Comment by Jendrej** [comment] 2018-10-16 19:18
Filters > sorting

**Comment by Infinine** [comment] 2018-10-16 19:27
With this you can only sort the library by:

*Name
*Last read
*Last updated (to library)
*Unread
*Total chapters
*Source

But none of them sorts the manga by the upload-date.

**Comment by Lindsor** [comment] 2020-01-15 14:20
Any update on this one? I feel like this is a basic feature.
Its the 1 feature missing for my full conversion to Tachiyomi from MangaRock.

**Comment by vongdong** [comment] 2020-01-20 02:57
Over a year and hasn't been added????

**Comment by joseph619** [comment] 2020-01-20 03:00
@Lindsor Download TachiyomiJ2K, that has fixed the issue.

**Comment by arkon** [comment] 2020-01-20 03:18
Duplicate of #2217

**Closed by arkon** 2020-01-20 03:18 UTC
