### ISSUE TITLE
[Feature Request] Remove read chapter automatically from Updates tab 

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#3857] opened 2020-09-28 05:22 UTC
## Why/User Benefit/User Problem
After a chapter has been read, it's no longer relevant for updates tab, and just wastes space (user needs to scroll further down to see unread chapter updates). 

## What/Requirements
Auto remove chapter from updates tab once the chapter is read.

**Comment by scb261** [comment] 2020-09-28 07:52
Duplicate of #3365, I guess

**Closed** 2020-09-28 11:58 UTC
Labels: feature
