### ISSUE TITLE
Hide read chapters

### ISSUE THREAD

**Issue by Mano5JP** [inorichi/tachiyomi#3119] opened 2020-05-08 10:43 UTC
**Toggle option to auto hide read chapters**

Right now, it needs to be done manually on each manga.

It would be great to have switch that would hide all read chapters on manga's

**Comment by joseph619** [comment] 2020-05-08 10:44
You do realize you can turn on filters, right?

**Comment by Mano5JP** [comment] 2020-05-08 10:53
**As i remember you can open a manga then filter to show unread**

But it isn't possible to do repetitive process on 0.1k mangas. 

In **dev** there's already toggle option to download only.

**Comment by Mano5JP** [comment] 2020-05-08 11:01
> You do realize you can turn on filters, right?

**As i remember you can any a manga then turn on filter to show unread**

But it isn't efficient to repetitively to same things  on 0.1k/+ mangas. 

In **dev** there's already toggle option to download only.

**Comment by arkon** [comment] 2020-07-26 22:15
Duplicate of #3444

**Closed by arkon** 2020-07-26 22:15 UTC
Labels: feature

**Comment by Mano5JP** [comment] 2020-08-05 10:58
Many ideas have sprung lately.

This was my thoughts on having a Default Filters for Series.

Right now we need to set filter to individual series, which isn't an issue, but if we want the same filters for the rest of the series on the lib. that's gonna take a lot of time.

Having a feature as a mockup picture would be great.
![Tachiyomi_3 0](https://user-images.githubusercontent.com/64928088/89401754-762ef100-d71e-11ea-836d-9e7e7d5754a5.jpg)
This would minimized repetition over time.

### On second thought,

Maybe have a multi-filter selection option as
![Tachiyomi_3 1](https://user-images.githubusercontent.com/64928088/89401991-d6be2e00-d71e-11ea-9050-791436da3e18.jpg)
If you think this view is taking unnecessary space on the device, then maybe have this open once we toggle, then we can choose a filter.
Once we exit the setting, the filter view will collapse & we can bring it up by clicking on choose filter.
If new series are added, it accordingly set to given default filters.

This personally helps many, as they have to set and apply filter once. If users/readers want to change to different filter options for specific series on given times, then that could be done manually as this feature already exists.

I know this might be unnecessarily steps but has good impacts,

Maybe you can implement this on new UX or upcoming 0.10x update.

**Comment by arkon** [comment] 2020-08-05 11:54
@Mano5JP Please comment on the open issue instead.

**Comment by Mano5JP** [comment] 2020-08-05 11:57
Found one let me add there

Thx
