### ISSUE TITLE
[Feature Request] Pin in library

### ISSUE THREAD

**Issue by antocs** [inorichi/tachiyomi#3801] opened 2020-09-14 19:36 UTC
## Why/User Benefit/User Problem
When you decide to read a completed manga and add it to your library, it would go way down in the list if you use the latest updated sort type, cause of the updates that will come, this will keep the manga you pin always on top.

## What/Requirements
Similar to how you pin an extension in "browse", let it be able to pin manga in the library too, and keep them on top regardless of the sort type chosen.

**Comment by arkon** [comment] 2020-09-14 19:48
Duplicate of #3656

**Closed by arkon** 2020-09-14 19:48 UTC
Labels: feature
