### ISSUE TITLE
[Feature Request] More info after library update

### ISSUE THREAD

**Issue by kiskae491** [inorichi/tachiyomi#2317] opened 2019-11-07 17:58 UTC
I get random 403 and 404 errors on random mangas when I update it individually and Update Library option just skips them. If I go thru catalogs everything is fine and I have to re-add them to continue reading. If its possible it would be nice to get a notification after library update if some mangas failed to update. In big library is pain in the ass to update every manga individually.

**Comment by arkon** [comment] 2020-01-04 22:37
Duplicate of #2307

**Closed by arkon** 2020-01-04 22:37 UTC
