### ISSUE TITLE
[Bug] Crash on Tracking Screen

### ISSUE THREAD

**Issue by kaononymous** [inorichi/tachiyomi#4009] opened 2020-11-05 06:37 UTC
App version: 0.10.5-2804 (standard, 6675508, 51)
Android version: 9 (SDK 28)
Android build ID: PPR1.180610.011.N950FXXUDDTI3
Device brand: samsung
Device manufacturer: samsung
Device name: greatlte
Device model: SM-N950F
Device product name: greatltexx

Steps to reproduce
Click on manga
Click on Tracking
Click add tracking/manga name
Backspace on search
App crashes
Expected behavior
Backspace search query

Actual behavior
App crashes

Other details
Additional details and attachments
I am using beta version so I don't know if I should be reporting or not also couldn't find a matching post so sorry if it is an existing query

**Comment by scb261** [comment] 2020-11-05 06:53
I guess it's a duplicate of #3996

**Closed** 2020-11-06 12:31 UTC
Labels: bug
