### ISSUE TITLE
[Feature Request] Paginated chapterListParse

### ISSUE THREAD

**Issue by edgarMejia** [inorichi/tachiyomi#3476] opened 2020-07-15 14:51 UTC
### Why/User Benefit/User Problem
- Reduced loading times in sources with paginated chapters

### What/Requirements
I'm not sure if this is the correct place to submit this request.

This function would be similar to what is currently paged `popularMangaRequest(page: Int)`.

Actually when you make an extension we are assuming that we can get all the chapters list in one request but some sources like [Kumanga](https://www.kumanga.com/) uses paginated section to shows chapters list, so is necessary to make various request to get all the chapters, as a programmer this is not a problem but in all that time the user will only see a loading screen.

Let's imagine that the user is loading one piece: https://www.kumanga.com/manga/524/p/99/one-piece#cl
At this moment OP has 99 chapters, there would be 99 requests and a long waiting time for the user.

**Comment by arkon** [comment] 2020-07-15 15:41
Duplicate of #2024

**Closed by arkon** 2020-07-15 15:41 UTC
Labels: feature
