### ISSUE TITLE
[Feature Request]: Minor change to viewing individual manga

### ISSUE THREAD

**Issue by Puddintame349** [inorichi/tachiyomi#3591] opened 2020-08-04 05:56 UTC
The recent update brought a change to the individual manga viwing screen. One adverse change is that manga chapters are shown when opening the screen, in order of last at the top.

Though rare, some manga have spoilery chapter titles, and the default of seeing latest chapters at top can contribute to that. While the filter setting lets you reverse the order, this has to be done for each manga.

An easy remedy to this would be a global setting that dictates the default chapter order.

One last, very minor problem I have with the update is that it removed the labes Writer, Artist, Status, and Source. While it still shows those things, there is a clarity lost when the labels were removed, and the info now looks a bit jumbled. Would looker better with previous format.

**Comment by Puddintame349** [comment] 2020-08-04 06:01
![20200804_020129](https://user-images.githubusercontent.com/54298236/89258591-6f0cc380-d5f6-11ea-9f78-1885989cb094.jpg)

**Comment by arkon** [comment] 2020-08-04 12:17
Duplicate of #484

**Closed by arkon** 2020-08-04 12:18 UTC
Labels: feature
