### ISSUE TITLE
[Feature] Download and save as zip

### ISSUE THREAD

**Issue by AbdulrahmanHadz** [inorichi/tachiyomi#1519] opened 2018-06-29 20:20 UTC
Add a feature that lets us choose to download to a folder or to a zip. I think this is better as copying and and moving from sources would be easier as well as using the downloads to read on another device.

**Comment by inorichi** [comment] 2018-06-30 10:03
Duplicate of #918

**Closed by inorichi** 2018-06-30 10:03 UTC
