### ISSUE TITLE
[Bug][Anilist Tracking] Anilist tracking needs to default to Plan To Read after a recent anilist update so that start date remains sane

### ISSUE THREAD

**Issue by themagicalyang** [inorichi/tachiyomi#2171] opened 2019-08-09 00:16 UTC
**App version:** 8.4

**Android version:** 6

**Issue/Request:** Someone since last year, and most likely 4 months ago, anilist started adding start date once a manga is set to `Reading`. This means that when you search and add a new manga into tachiyomi to anilist tracking, the status is already `Reading` and start date is already set in anilist. But now if I set status to `Plan To Read` and then read 1st chapter days or months later, well the start date won't change in Anilist. The solution isn't really to ask Anilist to change their behaviour, because from their perspective the behavior makes some sense. The workflow generally goes -> planning -> reading and not reading -> planning. So my understanding is that it needs to change in tachiyomi.

**Steps to reproduce (if applicable)**

 1. Choose a new manga (say X) not in your Anilist list.
 2. Add Anilist tracking to manga X in tachiyomi
 3. Anilist tracking will show `Reading` status
 4. Visit anilist page for manga X. It will show date as current date.
 5. Change status in tachiyomi anilist tracking to Plan To Read.
 6. Visit anilist page for manga X. It will show date as current date.
 7. After a couple of days, increment anilist tracking in tachiyomi to chapter 1.
 8. Visit anilist page for manga X. It will show date as the date when manga X was first added to anilist.

**Other details:**
This https://github.com/inorichi/tachiyomi/issues/200 can also be relevant, as well the other issues which reference it.

**Comment by everyonus** [comment] 2019-08-18 23:27
This also applies to MAL and Kitsu, which is annoying having to go back and remove/edit the dates.

**Comment by arkon** [comment] 2020-09-11 14:40
Duplicate of #200

**Closed by arkon** 2020-09-11 14:40 UTC
Labels: bug
