### ISSUE TITLE
[Bug] When the background color of a manga is set to black, the switches under "Custom filter" become indistinguishable from the background

### ISSUE THREAD

**Issue by specterflare** [inorichi/tachiyomi#2857] opened 2020-04-10 19:30 UTC
### Device information
* Tachiyomi version: r2002
* Android version: 10
* Device: Pixel 3

### Steps to reproduce
1. Go into a manga chapter and set "Background color" under "Settings" to "Black"
2. Open up "Custom filter"

### Expected behavior
The switches for "Use custom color filter" and "Use custom brightness" should be visible against the background.

### Actual behavior
The switch knobs are the same color as the background, making the operation of the controls confusing at first.

**Comment by arkon** [comment] 2020-04-10 19:31
Duplicate of #2784

**Closed by arkon** 2020-04-10 19:31 UTC
Labels: bug
