### ISSUE TITLE
[Feature Request] Add option to edit MyAnimeList start and finish date from the Tracking view

### ISSUE THREAD

**Issue by zhantyzgz** [inorichi/tachiyomi#1358] opened 2018-04-09 21:56 UTC
**App version:** 0.7.2

**Issue/Request:** It would be nice if you could edit your personal start and finish date of a manga directly from Tachiyomi, just like you can edit your status and score.

**Other details:** Screenshot of the MyAnimeList edit panel: https://puu.sh/zZLTm/a68c15a79c.png

**Comment by Tixx7** [comment] 2019-11-29 19:27
**This**

**Comment by arkon** [comment] 2020-03-07 23:18
Marking as duplicate of #2670

**Closed by arkon** 2020-03-07 23:18 UTC
