### ISSUE TITLE
[Feature request] Compress manga in zip format

### ISSUE THREAD

**Issue by Heavyarms04** [inorichi/tachiyomi#2378] opened 2019-12-21 12:59 UTC
1. App version 0.8.4
 2. Android version 7
 3.Compress manga in zip format

It would be very good if you could compress manga in zip format so it would be more comfortable to save your collection and would prevent some pages from being seen in the gallery of the device because many are filter
I apologize for my mishandling of the language I hope you can read my request

**Comment by arkon** [comment] 2019-12-22 20:29
Duplicate of #918

**Closed by arkon** 2019-12-22 20:29 UTC
