### ISSUE TITLE
[Feature Request] dismiss the selection in the chapters list after an acrion is done

### ISSUE THREAD

**Issue by aakash37** [inorichi/tachiyomi#3099] opened 2020-05-06 19:21 UTC
### Why/User Benefit/User Problem
currently the selection is persistent even after we perfom an action(download/bookmark/read/previous as read) which is unnecessary. This doesn't happens with the library.

**Comment by arkon** [comment] 2020-05-06 20:02
Duplicate of #3004

**Closed by arkon** 2020-05-06 20:02 UTC
Labels: feature
