### ISSUE TITLE
Application crash when using the mode: "Continuous Vertical" reading

### ISSUE THREAD

**Issue by Gena1005** [inorichi/tachiyomi#2871] opened 2020-04-13 00:15 UTC
### Device information
* Tachiyomi version: 0.8.5-2024 (Dev)
* Android version: 10 | Pixel Experience Official
* Device: Xiaomi Redmi Note 5 | Whyred

## Steps to reproduce
1. Open "Tachiyomi" -> More -> Settings -> Reader -> In the "Reading direction" option, select the option: "Continuous-Vertical"
2. After all the manipulations in the "first step", open any manga / manhwa / manhua and continue reading until the "Tachiyomi" restarts by itself, then there will be a "Splash - Screen" and then you will be transferred to the "Main screen  libraries "!!!

### Expected behavior
The application should not restart, according to the logic of things ...

### Actual behavior
It all started after adding the reading option: Continuous Vertical

### Other details
Additional details and attachments.
[2020-04-13-06-05-01.txt](https://github.com/inorichi/tachiyomi/files/4467433/2020-04-13-06-05-01.txt)
----
Interesting fragments from the "crash log" (I apologize in advance, I can not throw texts into the "spoiler"))
04-13 06:01:00.949 W/tachiyomi.debu(30939): Accessing hidden method Lsun/misc/Unsafe;->putOrderedObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
04-13 06:00:58.744 I/FA      (30939): Tag Manager is not found and thus will not be used
04-13 06:00:58.756 W/yomi.debug:acr(30916): ClassLoaderContext shared library size mismatch. Expected=1, found=0 (PCL[]{PCL[/system/framework/org.apache.http.legacy.jar*2680228128]} | PCL[];PCL[/data/app/eu.kanade.tachiyomi.debug-_ACE2-LXOvJSLdr30fPtCQ==/base.apk*2575587912:/data/app/eu.kanade.tachiyomi.debug-_ACE2-LXOvJSLdr30fPtCQ==/base.apk!classes2.dex*1442462769:/data/app/eu.kanade.tachiyomi.debug-_ACE2-LXOvJSLdr30fPtCQ==/base.apk!classes3.dex*403129842])
04-13 06:00:58.761 V/chatty  (30939): uid=10184(eu.kanade.tachiyomi.debug) identical 1 line
04-13 06:00:58.805 D/BaseController(30939): Attach view for MangaController@c4a9805
04-13 06:00:58.806 D/BaseController(30939): Attach view for ChaptersController@b11728b
04-13 06:00:58.807 D/BaseController(30939): Attach view for MangaInfoController@3f816a5
04-13 06:00:58.808 D/BaseController(30939): Attach view for TrackController@a490545

**Comment by arkon** [comment] 2020-04-13 01:01
Does it crash with webtoon mode? This seems more like a ROM issue.

**Comment by Gena1005** [comment] 2020-04-13 01:12
> Does it crash with webtoon mode?
Hello! Yes, "Webtoon Mode"

> This seems more like a ROM issue.
Such a problem was also observed on the "Havoc OS Official" (Android 10)

**Comment by arkon** [comment] 2020-04-13 01:57
Actual crash from the logs:

```
04-13 06:00:55.612 E/ACRA    (17175): ACRA caught a KotlinNullPointerException for eu.kanade.tachiyomi.debug
04-13 06:00:55.612 E/ACRA    (17175): kotlin.KotlinNullPointerException
04-13 06:00:55.612 E/ACRA    (17175): 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.onPageSelected(WebtoonViewer.kt:167)
04-13 06:00:55.612 E/ACRA    (17175): 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.access$onPageSelected(WebtoonViewer.kt:25)
04-13 06:00:55.612 E/ACRA    (17175): 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$1.onScrolled(WebtoonViewer.kt:81)
04-13 06:00:55.612 E/ACRA    (17175): 	at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
04-13 06:00:55.612 E/ACRA    (17175): 	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5338)
04-13 06:00:55.612 E/ACRA    (17175): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
04-13 06:00:55.612 E/ACRA    (17175): 	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
04-13 06:00:55.612 E/ACRA    (17175): 	at android.view.Choreographer.doFrame(Choreographer.java:722)
04-13 06:00:55.612 E/ACRA    (17175): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
04-13 06:00:55.612 E/ACRA    (17175): 	at android.os.Handler.handleCallback(Handler.java:883)
04-13 06:00:55.612 E/ACRA    (17175): 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-13 06:00:55.612 E/ACRA    (17175): 	at android.os.Looper.loop(Looper.java:214)
04-13 06:00:55.612 E/ACRA    (17175): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-13 06:00:55.612 E/ACRA    (17175): 	at java.lang.reflect.Method.invoke(Native Method)
04-13 06:00:55.612 E/ACRA    (17175): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-13 06:00:55.612 E/ACRA    (17175): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Duplicate of #2870

**Closed by arkon** 2020-04-13 01:57 UTC
Labels: bug
