### ISSUE TITLE
[Bug] newest update click on manga results in crash

### ISSUE THREAD

**Issue by waterdrinker78** [inorichi/tachiyomi#2550] opened 2020-01-29 11:27 UTC
### Device information
* Tachiyomi version: r1679
* Android version: 7.1.2

## Steps to reproduce
1. Update to newest dev
2. Tap on manga chapter 

###expexted behavior: read manga

### Other details
Additional details and attachments.

**Comment by waterdrinker78** [comment] 2020-01-29 11:27
kotlin.KotlinNullPointerException
	at eu.kanade.tachiyomi.data.preference.PreferencesHelperKt.getOrDefault(PreferencesHelper.kt:19)
	at eu.kanade.tachiyomi.ui.manga.chapter.ChaptersAdapter.<init>(ChaptersAdapter.kt:35)
	at eu.kanade.tachiyomi.ui.manga.chapter.ChaptersController.onViewCreated(ChaptersController.kt:76)
	at eu.kanade.tachiyomi.ui.base.controller.BaseController$1.postCreateView(BaseController.kt:23)
	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:1019)
	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:813)
	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:783)
	at com.bluelinelabs.conductor.Router.setBackstack(Router.java:456)
	at com.bluelinelabs.conductor.ControllerHostedRouter.setBackstack(ControllerHostedRouter.java:107)
	at com.bluelinelabs.conductor.Router.setRoot(Router.java:336)
	at eu.kanade.tachiyomi.ui.manga.MangaController$MangaDetailAdapter.configureRouter(MangaController.kt:166)
	at com.bluelinelabs.conductor.support.RouterPagerAdapter.instantiateItem(RouterPagerAdapter.java:80)
	at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:19886)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:693)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2319)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1410)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1663)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
	at android.view.Choreographer.doFrame(Choreographer.java:623)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by arkon** [comment] 2020-01-29 12:24
Duplicate of #2548

**Closed by arkon** 2020-01-29 12:24 UTC
Labels: bug
