### ISSUE TITLE
[Feature Request] The ability to hide certain scan groups from the chapter listing.

### ISSUE THREAD

**Issue by qwuzzy** [inorichi/tachiyomi#3565] opened 2020-08-02 08:35 UTC
### Why/User Benefit/User Problem
I find it very annoying when I'm reading something from mangadex and there are multiple versions of chapters that were made by different groups, which means the quality of the scanlation differs. It would be nice if I were able to hide all chapters from the group I don't want to see.

### What/Requirements
The ability to simply filter out groups from the listing is what I had in mind.

**Comment by scb261** [comment] 2020-08-02 08:41
Duplicate of #969

**Closed** 2020-08-02 13:45 UTC
Labels: feature
