### ISSUE TITLE
Filter batoto by source / skip same number chapter

### ISSUE THREAD

**Issue by BlackSynder** [inorichi/tachiyomi#688] opened 2017-02-17 13:50 UTC
From what I've been thinking, this problem could have at least two solutions.
The problem itself, is that on batoto due to multiple sources, there are duplicates of chapters. For example, say I want to read Tokyo ghoul:re, there are both imperial scans and twisted hel scans. After reading chapter 1 from twisted hel I would then get the same chapter from imperial scans. Solutions to this problem may be either filter by the source on batoto (which I assume is a bit more difficult, due to it being something on their side) or skipping chapters with the same chapter number in continuous reading.

**Comment by jshap70** [comment] 2017-02-17 16:28
I think this might be a dup of https://github.com/inorichi/tachiyomi/issues/107

**Comment by BlackSynder** [comment] 2017-02-17 16:40
I've seen that, but it's not really what I'm saying. I don't want the name itself, I would like the ability to filter it. Also skipping chapters if you've read the same number isn't there.

**Comment by j2ghz** [comment] 2017-02-17 16:49
If you use Sorting mode: by chapter number it skips chapters with the same chapter number, doesn't it?

**Comment by wopian** [comment] 2017-02-18 06:35
^ The downside of that is you'll get given the good release and the shitty release of the same chapter depending on which came first.

**Comment by inorichi** [comment] 2017-02-18 23:53
I consider this a duplicate of the linked issue. Both require to include a scanlator field in the database. Adding a filter by scanlator should be easy if the other one is implemented. I'm still not sure if we'll support that though.

**Closed by inorichi** 2017-02-18 23:53 UTC
