### ISSUE TITLE
[Feature Request] Setting default manga sort / chapter display options

### ISSUE THREAD

**Issue by Camology** [inorichi/tachiyomi#3444] opened 2020-07-10 16:25 UTC
**Benefit**
Currently I have to set display: unread and sort:ascending every time I open up a new manga. I know some other users have different wants so I think it would be handy to set what we want on our own. 

**Requirements**
Think this only needs to be set once in the options on a new field, and then when a new manga entry is created it pulls from these fields (will leave default as they are)

**Comment by Camology** [comment] 2020-07-10 16:26
Creating this issue for myself, as I am going to fork and take a stab at it.

**Comment by Mano5JP** [comment] 2020-08-05 11:59
@arkon 

Many ideas have sprung lately.

This was my thoughts on having a Default Filters for Series.

Right now we need to set filter to individual series, which isn't an issue, but if we want the same filters for the rest of the series on the lib. that's gonna take a lot of time.

Having a feature as a mockup picture would be great.
![Tachiyomi_3 0](https://user-images.githubusercontent.com/64928088/89401754-762ef100-d71e-11ea-836d-9e7e7d5754a5.jpg)
This would minimized repetition over time.

### On second thought,

Maybe have a multi-filter selection option as
![Tachiyomi_3 1](https://user-images.githubusercontent.com/64928088/89401991-d6be2e00-d71e-11ea-9050-791436da3e18.jpg)
If you think this view is taking unnecessary space on the device, then maybe have this open once we toggle, then we can choose a filter.
Once we exit the setting, the filter view will collapse & we can bring it up by clicking on choose filter.
If new series are added, it accordingly set to given default filters.

This personally helps many, as they have to set and apply filter once. If users/readers want to change to different filter options for specific series on given times, then that could be done manually as this feature already exists.

I know this might be unnecessarily steps but has good impacts,

Maybe you can implement this on new UX or upcoming 0.10x update.

_Originally posted by @Mano5JP in https://github.com/inorichi/tachiyomi/issues/3119#issuecomment-669127576_

**Comment by Camology** [comment] 2020-08-13 01:30
that looks good to me!

**Comment by Camology** [comment] 2020-08-13 01:36
sorry got real busy with work havent had a chance to even look at this 😆

**Comment by lmj0011** [comment] 2020-08-13 02:25
This looks likes a duplicate of https://github.com/inorichi/tachiyomi/issues/3444 

@Camology see https://github.com/inorichi/tachiyomi/pull/3622

**Comment by arkon** [comment] 2020-08-13 02:27
Indeed, will close in favour of #484

**Closed by arkon** 2020-08-13 02:27 UTC
