### ISSUE TITLE
[Feature Request] Include Source selection in backup

### ISSUE THREAD

**Issue by ghus3rz** [inorichi/tachiyomi#3113] opened 2020-05-08 00:17 UTC
### Why/User Benefit/User Problem
Would help reduce restore steps especially for those using multi-sources extensions and have disabled some of them. 

### What/Requirements
Ideally to have additional option, "Source Selection" in backup option. This mean if user have extension A,B,C,D where B is a multi-source with 3 sources enabled, the same 3 selection will be the only ones renabled from the multi source extension once user restore the back up file.

**Comment by arkon** [comment] 2020-05-08 00:44
As far as I can remember, it doesn't matter if they're enabled or not, just that they're installed. Is that not the case?

**Comment by ghus3rz** [comment] 2020-05-08 02:50
To clarify, currently if I have Mangabox and I enabled only Manganelo. If i tried to restore the backup to another Tachi with the same extensions, I will still get all the sources under Mangabox enabled. So my ask will be, would it be possible that backup can remember which sources that is enabled and which sources that are not and restore the same state? Is the example better?  Unless I am also not reading your comments right. (or  i have managed to miss that in backup/restore options)

**Comment by arkon** [comment] 2020-05-08 03:01
Yeah, that's not the same thing. Backup/restore is your library, not your settings. 

Duplicate of #1857

**Closed by arkon** 2020-05-08 03:01 UTC
Labels: feature
