### ISSUE TITLE
[Feature Request] Exclude keywords from the automatic download

### ISSUE THREAD

**Issue by o01210o** [inorichi/tachiyomi#1925] opened 2019-03-23 15:32 UTC
**App version:** 0.8.1

**Request:**
*Add the possibility to exclude keywords from the automatic download.*
I want to exclude chapters with the word "SPOILER" from the automatic download and completely ignore them.

**Details**
I essentially use the french source "Japscan" and on some mangas they add a "pre-chapter" with the spoilers of the chapter.
I use the automatic download and the app downloads that pre-chapter, that's normal.

(I already delete it in this screenshot)
![op](https://user-images.githubusercontent.com/45663409/54867934-f5579b00-4d5c-11e9-882f-792f5837effc.png)

But later, when they change the chapter with the real one, the app doesn't download it again because it considers that the chapter had already be downloaded and I have to do it manually.

![op2](https://user-images.githubusercontent.com/45663409/54867936-f7b9f500-4d5c-11e9-89bc-dadedddbce49.png)

(Also if I don't delete that "pre-chapter" directly from the list, I have to delete from the file explorer because I can't acces to it anymore from the app because the name had changed)

**Comment by AmineI** [comment] 2019-03-23 18:44
The "excluding keywords" request aside, what are those "pre-chapters" in JapScan ? Previews maybe ? If that's the case, I think they should be removed from the chapter list altogether, as they litteraly aren't chapters, shouldn't they ?
I think I could easily update the extension to filter out chapters containing "Spoiler SPOILER" from the chapter list. But if they are of any use to someone / they are more than only previews it shouldn't be forced… Maybe with a setting like MangaDex extension's settings ?

**Comment by pokke456** [comment] 2019-03-23 21:39
> what are those "pre-chapters" in JapScan ?

Litteraly this : https://scantrad.fr/mangas/spoilers/937
Japscan first released that "pre-chapter" and then changed the pages with the good pages when the translation is released.

> To me it looks like it'd be better to fix the JapScan extension for that than adding such a feature - I don't really see any other use case for excluding keywords...

Maybe there is best solution for this, since I don't really know about the technical part. I just think that excluding keywords may be a solution. If it can be solved otherwise, then do for it :) 

> to filter out chapters containing "Spoiler SPOILER" from the chapter list. 

That's actually what I really want. But the problem is that the chapter with "Spoiler SPOILER" is **replaced** (it's not removed and no new chapter is pushibled) by the good chapter. If those chapter are removed, will the good one be visible when it released ?

**Comment by AmineI** [comment] 2019-03-25 12:07
Should be fine. For the extension issue, does the "prechapter" name always contain "Spoiler SPOILER" or does that name change ?


For the actual request - excluding keywords from the downloads - I'll let others say if it's out of scope or not a planned feature. I personally don't see any use for that except when websites do weird things like that, which I'd see as an extension issue.

**Comment by pokke456** [comment] 2019-03-25 16:26
> does the "prechapter" name always contain "Spoiler SPOILER" or does that name change ?

No, it doesn't change. I personnaly always see "Spoiler SPOILER".

**Closed** 2019-10-31 18:06 UTC
