### ISSUE TITLE
[Feature Request] auto change reading mode

### ISSUE THREAD

**Issue by TxXDRAGONXxT** [inorichi/tachiyomi#4112] opened 2020-12-12 19:42 UTC
## explanation 
Add new setting by enabling it, it can change the reading mode from webtoon to manga and vice-versa automatically 

## Why/User Benefit/User Problem
The benefits for the user is just convenience so it can be a low priority feature

## What/Requirements
By using the dimensions of the picture you will be able to recognize and differentiate between webtoon and a manga since the both has different hight to width ratio

**Comment by scb261** [comment] 2020-12-15 15:22
Duplicate of #1664

**Closed** 2020-12-15 15:28 UTC
Labels: feature
