### ISSUE TITLE
[Bug] Installing extensions does not immediately update sources list

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi#3017] opened 2020-05-02 00:06 UTC
### Device information
* Tachiyomi version: Stable 0.9
* Android version: 8.1.0

## Steps to reproduce
1. Install any extension
2. Check sources list

### Other details
Just like #2999

**Comment by arkon** [comment] 2020-05-02 00:44
Duplicate of #3002

**Closed by arkon** 2020-05-02 00:44 UTC
Labels: bug

**Comment by vengiare** [comment] 2020-05-02 00:46
oopsie
