### ISSUE TITLE
[Feature Request] Ability to Merge Same Series from Different Sources

### ISSUE THREAD

**Issue by GrenadeSpamr** [inorichi/tachiyomi#1390] opened 2018-04-29 20:58 UTC
**App version:**
- 0.7.3

**Issue/Request:** 
- Some series had their chapters cut when they moved them to another source, but newer source doesn't have the old chapters
(i.e Source 1 has chapters 1-92, Source 2 has chapters 93-Latest)
as such, the ability to merge these sources might be a great help.

Edit: It seems issue #1388 is similar to this, though for a different reason.

**Comment by inorichi** [comment] 2018-05-01 19:43
Duplicate of #886

**Closed by inorichi** 2018-05-01 19:43 UTC
