### ISSUE TITLE
[Feature Request] Save Searches

### ISSUE THREAD

**Issue by ptoump** [inorichi/tachiyomi#2885] opened 2020-04-17 16:25 UTC
### Why/User Benefit/User Problem
Having the possibility to save Searches (per source) will bring great convenience to those who repeatedly search for the same things (e.g. all isekai manga in Mangadex sorted by update time descending)

### What/Requirements
I would suggest to have a new button in "Sources" next to the search button with saved Searches. I would also suggest to have a "save search" button in the search dialog of each source that would save the search field as have been entered at that moment. 
After saving one should be able to invoke the search right from the saved Searches .

Hope that makes sense..

**Comment by arkon** [comment] 2020-04-18 23:12
Duplicate of #779

**Closed by arkon** 2020-04-18 23:12 UTC
Labels: feature
