### ISSUE TITLE
[Feature Request] <Add hide read entries button in updates page>

### ISSUE THREAD

**Issue by jashanprt** [inorichi/tachiyomi#3784] opened 2020-09-12 13:53 UTC
Hi

I generally use updates page to see what I need to read and sometimes I miss last 2 days update and start reading using that window.

But when u have read and unread entries in there there are lot of entries. 
Can we have an option in updates window to hide(not remove) the already read updates?

## Why/User Benefit/User Problem
The updates list become quite long after a certain days and u forget/ miss few entries if they are 3 days or a week ago if u just left 1 series update to be read for another day. 
This will give user a way to just see unread updates for few days even if it's from 4 days without the clutter of what's already been read and need no attention now.

## What/Requirements
Hide/show button for read/ unread entries in updates page.

**Comment by arkon** [comment] 2020-09-12 14:50
Duplicate of #3365

**Closed by arkon** 2020-09-12 14:50 UTC
Labels: feature
