### ISSUE TITLE
[Bug] Manga disappearing

### ISSUE THREAD

**Issue by elithielle** [inorichi/tachiyomi#3826] opened 2020-09-21 02:48 UTC
## Device information
* Tachiyomi version: r2703
* Android version: 6.0.1
* Device: vivo y53

### Expected behavior
The manga should not disappear. And it will be Visible on my library.

### Actual behavior
When i search a certain manga that I favourited before it doesn't appear on my library after i search it on the a certain manga extension, I saw that its not on my favorite anymore.

## Other details
The chapter where i left off in the "disappearing manga" is also gone and my bookmarks too. The extension that i usually use is mangahasu and mangadex.

**Comment by scb261** [comment] 2020-09-21 09:36
Duplicate of #3390

**Closed** 2020-09-21 10:52 UTC
Labels: bug
