### ISSUE TITLE
Add filter by Non-Tracking

### ISSUE THREAD

**Issue by ZeDeedIsDone** [inorichi/tachiyomi#2448] opened 2020-01-06 12:16 UTC
### Why/User Benefit/User Problem
Sometimes I forget to add a manga to the Tachiyomi tracker and would like an easy way to see which ones I need to start tracking.

### What/Requirements
In My Library > Add a non-tracking filter alongside the other filters (downloaded, unread, completed)

It should only be a filter if you've started using the Tachiyomi tracker, to not confused the non-tracker readers.

**Comment by arkon** [comment] 2020-01-06 12:37
Duplicate of #1899

**Closed by arkon** 2020-01-06 12:37 UTC
Labels: feature
