### ISSUE TITLE
Manga not being removed from Local source after being deleted

### ISSUE THREAD

**Issue by linoth** [inorichi/tachiyomi#3461] opened 2020-07-12 15:58 UTC
Opening bug on recommendation of josephgomes619 in the July support thread on Reddit.

### Device information
* Tachiyomi version: 0.9.2
* Android version: Fire OS 7.3.1.4 (based on Pie)
* Device: Kindle Fire HD 8 Plus

## Steps to reproduce
1. Copy manga onto SD card in /Tachiyomi/Local/
2. Delete manga

### Expected behavior
Manga should be removed from Local Source

### Actual behavior
Manga remained in Local Source, showing a chapter available until Clear Database was used, at which point the Chapter disappeared, but the manga did not.

### Other details
Steps attempted to correct:
- Clear database, Clear Chapter cache, Refresh library metadata
- Clear database, close app, Force stop, relaunch app
- Copy folder back onto SD card, then verify manga is found with viewable chapter, and delete, before repeating above step.

Brief history of this directory, in case it may be important.
- Created on a Kindle Fire 7 (5th Gen.)  Uncertain if behavior was similar or not.
- Moved SD card to Kindle Fire HD 8 Plus
- Moved manga downloaded from Extensions into Local source, as well as copying from PC
- Read a few, deleted the folders, manga were not removed
- Attempted steps in Advanced, attempted force stop myself, no change.  Posted on reddit, repeated steps, no change.

**Comment by arkon** [comment] 2020-07-12 16:06
Duplicate of #1770

**Closed by arkon** 2020-07-12 16:06 UTC
Labels: bug
