### ISSUE TITLE
Fairy tail chapter no 491 not displaying in the list

### ISSUE THREAD

**Issue by sm7297** [inorichi/tachiyomi#367] opened 2016-06-27 13:04 UTC
I have to use unread filter to access it

Version: r797 or v0.0.0
(other relevant info like OS)
Android 4.4.2

**Comment by NoodleMage** [comment] 2016-06-27 14:46
Which catalogue?

And what do you exactly mean by having to use unread filter to access it?

**Comment by sm7297** [comment] 2016-06-27 16:58
on kiss manga catalogue like today update my library it after updating it say one new chapter in fairytail
then i open fairy tail i did not find latest chapter 491 instead the last chapter was 490 i tried reloading but no use then i use filter and check unread after that chapter 491 show up

**Comment by inorichi** [comment] 2016-06-28 10:33
This doesn't look like a bug to me. Probably some other chapter readded triggered the notification, and by chance when you updated the list manually, 491 was released.

Anyways it worked after manually updating. I can't reproduce this and the behavior is consistent in my case, so I'm closing this.

**Closed by inorichi** 2016-06-28 10:33 UTC
Labels: bug
