### ISSUE TITLE
Enquiry on the downloaded manga status

### ISSUE THREAD

**Issue by blackdevil91** [inorichi/tachiyomi#1013] opened 2017-09-30 13:34 UTC
Hi,

May iknow is there any downloaded status in my library list. So far, the manga is shown based on which manga we mark as favourites. May i know is there any option or setting to see which manga that i have downloaded so far? i need to resume manga which not downloaded but are in my library.

Thanks

**Comment by j2ghz** [comment] 2017-09-30 13:35
Duplicate of #826 #895

**Comment by blackdevil91** [comment] 2017-09-30 13:49
regarding the option under display, i am not able to see any 'download badges'

**Comment by cd0rw0** [comment] 2017-10-04 06:28
#895  the " download badges" still under in work progress

**Closed** 2017-10-05 08:21 UTC
