### ISSUE TITLE
[Feature Request] offline tracking/tachi tracking and able to sync once online 

### ISSUE THREAD

**Issue by vipzzx** [inorichi/tachiyomi#4027] opened 2020-11-10 18:32 UTC
## What/Requirements
Since the tracking offered are all online and don't work when reading offline.

Have a way to track while offline when when you are back online, when you sync tracking it will sync the tracker on tachi to the online trackers.

**Comment by CrepeTF** [comment] 2020-11-10 18:36
Duplicate of #2397

**Closed** 2020-11-10 18:40 UTC
Labels: feature
