### ISSUE TITLE
[Feature Request] Change default reading mode for categories

### ISSUE THREAD

**Issue by DustJead** [inorichi/tachiyomi#3995] opened 2020-11-02 09:08 UTC
I think tachiyomi should add the feature to change the default reading mode of your categories.

## Why/User Benefit/User Problem
I sort all my manga and comics into separate categories, so it would be convenient to be able to just change the reading mode by category, rather than having to change the reading mode of each and every thing manually.

## What/Requirements
When making a category, you would have a drop down menu that lets you change the default reading mode of everything in the category. 

Alternatively, a feature that lets you select multiple series and change the reading mode of all selected series would suffice.

**Comment by scb261** [comment] 2020-11-02 09:15
Duplicate of #2518

**Closed** 2020-11-02 13:00 UTC
Labels: feature
