### ISSUE TITLE
Notification opens "Libary updates"

### ISSUE THREAD

**Issue by RaidenHUN** [inorichi/tachiyomi#831] opened 2017-06-05 08:23 UTC
Hi!
I have a request or an "idea". In most manga readers if you open notification about the new mangas it automatically open and lead you to the new updated pages, pretty much a same page as "Libary updates" in this app.

If I open the app I like to get to the favourites rather then the updates, however if I set the bookmarks as my "start up page", the notifications bring me here, the same page as well.

It would be great if you add an option so when I open the app from notification it brings me to Libary updates, if I open the app from app drawer it brings me to the prevously set "start up page" - which is my bookmarks in my case.

Thanks,
R.

(App version: 0.5.2
Galaxy S7 edge
OS. Android 7.0

**Comment by null-dev** [comment] 2017-06-05 08:26
Not sure, but I think this is a duplicate of #808 (which has already been fixed). If it is, you can be assured that this feature will be in the next release.

**Comment by RaidenHUN** [comment] 2017-06-05 08:30
Yep, looks like the same request.

**Comment by inorichi** [comment] 2017-06-05 08:37
Yup, it was changed yesterday. :)

**Closed by inorichi** 2017-06-05 08:37 UTC
