### ISSUE TITLE
Auto Download new chapters when title exists in multiple categories

### ISSUE THREAD

**Issue by Quiksmage** [inorichi/tachiyomi#2341] opened 2019-11-23 22:10 UTC
**App version:**
DEV and Stable

**Android version:**
9.0

**Issue/Request:**
When a title exists in 2 categories and you set one of those categories to auto-download, the download never takes place.

**Steps to reproduce (if applicable)**

 1. Add a title into 2 categories IE. Download and Reading
 2. Add another title to just the "Download" category
 3. Set the "Download" category to download automatically  (Downloads > Categories to include in download).
 4. Wait for a new chapter to come out for both of these titles
 5. The title in both categories in step 1 will not download, but the title in step 2 will download

**Other details:**

**Comment by arkon** [comment] 2019-11-23 22:11
I believe this is a duplicate of #2325

**Closed by arkon** 2019-11-23 22:11 UTC
