### ISSUE TITLE
[Feature Request] Filter By Untracked

### ISSUE THREAD

**Issue by Nexr0n** [inorichi/tachiyomi#4055] opened 2020-11-23 19:46 UTC
## Why/User Benefit/User Problem
Would make adding tracking to library significantly easier, the only real solution currently is to check your library one manga at a time to see if you remembered to add tracking to it. 

## What/Requirements
Just a filter, same as all the others. Only show manga which the user has not added tracking to.

**Comment by arkon** [comment] 2020-11-23 19:48
Duplicate of #1899

**Closed by arkon** 2020-11-23 19:48 UTC
Labels: feature
