### ISSUE TITLE
[Feature suggestion/request] Is it possible to have a "part" scrolling similar to Comicrack?

### ISSUE THREAD

**Issue by borouj-rashid-UOIT** [inorichi/tachiyomi#1400] opened 2018-05-04 00:21 UTC
It would be a great feature to have, especially for apps that are for small handhelds.

its a bit hard to explain but how it works is that, if you zoom into a page and then go to the "next part" it pans to the right every step, then down if you next part again. 
so basically, it divides the page into sections of your zoom size and then we go through each section in english reading order everytime we go "next part", then as we leave the page it zooms out completely to show the full view(this can be done before entering a page too).

its also like comixology's scrolling but not as specific. i guess the best way to understand it would be to try the ComicRack app.

thank you.

**Comment by salfedev** [comment] 2019-05-06 00:34
+1

**Comment by arkon** [comment] 2020-01-04 18:49
Duplicate of #2046

**Closed** 2020-01-04 18:50 UTC
