### ISSUE TITLE
[Feature Request] Sort by Date in chapter list

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#2674] opened 2020-03-07 04:28 UTC
### Why/User Benefit/User Problem
I have noticed this issue in a particular series and source called Cyanide & Happiness where the chapter name consists of date and that screws up the sort by chapter number.

### What/Requirements
Simply sorts the chapter list with the latest chapter uploaded. This also makes it easier to see what new chapters have been uploaded regardless of their chapter number, be it a new chapter or a special chapter of an old volume of the series.

**Comment by happywillow0** [comment] 2020-03-07 04:33
There is always sort by source which should sort it the way the website has it which normally in itself is by date.

**Comment by hXtreme** [comment] 2020-03-07 23:18
is that what sort by source means? I always thought that it meant sort based on release groups (source for the release).

**Comment by arkon** [comment] 2020-04-02 04:06
Duplicate of #1962

**Closed** 2020-04-02 04:06 UTC
Labels: feature
